Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-07, with the labels that each got.

#2043 [AdminBundle] fixed BC break in CreateUserCommand
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
Labels: Priority: High, Profile: Backend, Type: Bugfix

#2052 [GeneratorBundle] Fix xpath for publish modal in behat tests
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/PageContext.php
Labels: Priority: High, Profile: Backend, Type: Bugfix

#2051 [NodeSearchBundle] Backport elasticsearch 6.2 compatibility fix from 5.0
  src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
Labels: Priority: Normal, Profile: Backend, Type: Bugfix

#2056 [AdminListBundle] fixed form options source in admin list controller
  src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
Labels: Type: Bugfix

#2055 [KunstmaanTranslatorBundle] export all translations, use correct locales
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
  src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
  src/Kunstmaan/TranslatorBundle/Tests/app/config/parameters.yml
Labels: Profile: Backend, Type: Bugfix

#2053 [AdminBundle][MultidomainBundle] Check if container has service before changing it
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/DomainConfigurationPass.php
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/CompilerPass/MultidomainConfigurationPass.php
Labels: Priority: Normal, Profile: Backend, Type: Bugfix

#2058 [MediaBundle] Add web_root configuration to support both web and public as the root dir for uploads
  src/Kunstmaan/MediaBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/MediaBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MediaBundle/Tests/Utils/SymfonyVersionTest.php
  src/Kunstmaan/MediaBundle/Utils/SymfonyVersion.php
Labels: Priority: Low, Priority: Normal, Profile: Backend, Type: Bugfix, Type: Feature, sf4-compatibility

#2045 [AllBundles] Fix BC break after upgrading to sensio/framework-extra-bundle 5.0
  src/Kunstmaan/DashboardBundle/Controller/DashboardController.php
  src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
  src/Kunstmaan/MediaBundle/Controller/ChooserController.php
  src/Kunstmaan/MediaBundle/Controller/FolderController.php
  src/Kunstmaan/MediaBundle/Controller/IconFontController.php
  src/Kunstmaan/MediaBundle/Controller/MediaController.php
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
Labels: Priority: High, Profile: Backend, Type: BC break, Type: Bugfix, Type: Feature, sf4-compatibility

#2046 [AdminBundle] Add compatibility with the new symfony Role class
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
Labels: Priority: Normal, Profile: Backend, Type: Bugfix, sf4-compatibility

#2040 [MediaBundle] fixed BackgroundFilterLoader issue
  UPGRADE-5.1.md
  src/Kunstmaan/MediaBundle/Helper/Imagine/BackgroundFilterLoader.php
Labels: Priority: Low, Profile: Backend, Type: Deprecation

#2025 [AllBundles] Remove unused symfony/swiftmailer-bundle
  UPGRADE-5.1.md
  composer.json
  src/Kunstmaan/TranslatorBundle/Tests/app/AppKernel.php
  src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2023 [AllBundles] Remove unused sensio/distribution-bundle
  UPGRADE-5.1.md
  composer.json
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2060 [AdminBundle] Don't depend on monolog implementation of the logger
  src/Kunstmaan/AdminBundle/EventListener/LoginListener.php
  src/Kunstmaan/AdminBundle/Tests/EventListener/LoginListenerTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Improvement

#2010 [AllBundles] Allow fos/user-bundle 2.1
  UPGRADE-5.1.md
  composer.json
  src/Kunstmaan/AdminBundle/Helper/AdminPanel/DefaultAdminPanelAdaptor.php
  src/Kunstmaan/AdminBundle/Resources/config/routing.yml
  src/Kunstmaan/AdminBundle/Resources/views/Resetting/check_email.html.twig
  src/Kunstmaan/UserManagementBundle/Resources/config/routing.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility
