Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-02, with the labels that each got.

#1813 [KunstmaanNodeBundle] admin styles no longer have .min extension
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
Labels: Profile: Frontend, Type: Bugfix

#1817 [Leadgenerationbundle]: abstract functions should be public
  src/Kunstmaan/LeadGenerationBundle/Entity/Popup/AbstractPopup.php
Labels: Profile: Backend, Type: Bugfix

#1823 [AdminBundle] fixed delete pagepart modal issue
  src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
Labels: Priority: High, Profile: Frontend, Target audience: Administrators, Type: Bugfix

#1827 [AdminBundle] refactor media token transformer
  src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#1825 [AdminListBundle] Fix Export Exception namespace
  src/Kunstmaan/AdminListBundle/Exception/ExportException.php
  src/Kunstmaan/AdminListBundle/Service/ExportService.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#1789 [UtilitiesBundle][5.1] Commands as services and mark commands as final
  src/Kunstmaan/UtilitiesBundle/Command/CipherCommand.php
  src/Kunstmaan/UtilitiesBundle/DependencyInjection/KunstmaanUtilitiesExtension.php
  src/Kunstmaan/UtilitiesBundle/Resources/config/commands.yml
Labels: Profile: Backend, Type: Deprecation, Type: Improvement

#1791 [NodeBundle][5.1] Commands as services and mark commands as final
  src/Kunstmaan/NodeBundle/Command/CronUpdateNodeCommand.php
  src/Kunstmaan/NodeBundle/Command/InitAclCommand.php
  src/Kunstmaan/NodeBundle/Resources/config/commands.yml
Labels: Profile: Backend, Type: Deprecation, Type: Feature

#1788 [TranslatorBundle][5.1] Commands as services and mark commands as final
  composer.json
  src/Kunstmaan/TranslatorBundle/Command/ExportTranslationsCommand.php
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
  src/Kunstmaan/TranslatorBundle/Command/MigrationsDiffCommand.php
  src/Kunstmaan/TranslatorBundle/Command/TranslationCacheCommand.php
  src/Kunstmaan/TranslatorBundle/Command/TranslationFlagCommand.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
  src/Kunstmaan/TranslatorBundle/Resources/config/commands.yml
  src/Kunstmaan/TranslatorBundle/composer.json
Labels: Profile: Backend, Type: Deprecation, Type: Improvement

#1769 [AdminListBundle][5.1] Deprecate direct container access in controllers
  src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
  src/Kunstmaan/MenuBundle/Controller/MenuAdminListController.php
  src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
  src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
Labels: Profile: Backend, Type: Deprecation, Type: Improvement

#1767 [AllBundle] Fix unused method, property, variable or parameter
  src/Kunstmaan/AdminBundle/Helper/AdminRouteHelper.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
  src/Kunstmaan/ArticleBundle/Resources/config/services.yml
  src/Kunstmaan/ArticleBundle/Twig/ArticleTwigExtension.php
  src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
  src/Kunstmaan/ConfigBundle/Resources/config/services.yml
  src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
Labels: Profile: Backend, Type: Bugfix, Type: Deprecation

#1838 [AllBundles]: Backport pr #1767 but keeping BC
  src/Kunstmaan/AdminBundle/Helper/AdminRouteHelper.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
  src/Kunstmaan/ArticleBundle/Resources/config/services.yml
  src/Kunstmaan/ArticleBundle/Twig/ArticleTwigExtension.php
  src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
  src/Kunstmaan/ConfigBundle/Resources/config/services.yml
  src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
Labels: Profile: Backend, Type: Deprecation

#1849 [PagePartBundle] Fix for PHP 7.2 - value passed to count() cannot be null
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix

#1829 [AdminBundle]: re-add the extrajavascript block
  src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig
Labels: Profile: Frontend, Target audience: Developers, Type: Bugfix

#1834 [MediaBundle] Bulk file upload fix
  src/Kunstmaan/MediaBundle/Controller/MediaController.php
Labels: Profile: Backend, Type: Bugfix

#1846 [AdminListBundle]: ->loadTemplate() is only for internal use..
  src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
Labels: Profile: Backend, Type: Bugfix
