Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-09, with the labels that each got.

#2091 [NodeSearchBundle] Fix search index of childpages of a structured node
  composer.json
  src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
  src/Kunstmaan/NodeSearchBundle/Tests/EventListener/NodeIndexUpdateEventListenerTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix

#2104 [AdminBundle] Fixed issue with locale in kuma:user:create command
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
Labels: Profile: Backend, Type: Bugfix

#2103 [AdminBundle] Fixed issue when running kuma:user:create with --no-interaction flag
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
Labels: Profile: Backend, Type: Bugfix

#2100 [MediaBundle] Fix issues with CreatePdfPreviewCommand
  src/Kunstmaan/MediaBundle/Command/CreatePdfPreviewCommand.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#2099 [AdminBundle] Fix icons CKeditor
  src/Kunstmaan/AdminBundle/Resources/public/default-theme/ckeditor/plugins/icons.png
  src/Kunstmaan/AdminBundle/Resources/public/default-theme/ckeditor/plugins/icons_hidpi.png
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2105 [KunstmaanAdminBundle] check if command is not null on console error
  src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionSubscriber.php
Labels: Profile: Backend, Type: Bugfix

#2115 [NodeBundle] Node choice type fix
  src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2118 [FormBundle] Show full path to file in form export
  src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/FileFormSubmissionField.php
Labels: Priority: Low, Profile: Backend, Target audience: Administrators, Type: Bugfix

#2119 [AdminBundle] use full version of CKeditor
  package.json
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js.map
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js.map
  src/Kunstmaan/DashboardBundle/Resources/public/css/dashboard.css
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2120 [NodeSearchBunde] [SearchBundle] Add parameters for ES authentication and use them in version check
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
  src/Kunstmaan/SearchBundle/Resources/config/services.yml
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2123 [AllBundles] Revert PR 2097
  src/Kunstmaan/AdminBundle/Controller/BaseSettingsController.php
  src/Kunstmaan/AdminBundle/Controller/Symfony3BaseSettingsController.php
  src/Kunstmaan/AdminBundle/Controller/Symfony4BaseSettingsController.php
  src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
  src/Kunstmaan/AdminListBundle/Controller/ContainerDeprecationController.php
  src/Kunstmaan/AdminListBundle/Controller/Symfony3ContainerDeprecationController.php
  src/Kunstmaan/AdminListBundle/Controller/Symfony4ContainerDeprecationController.php
Labels: Priority: High, Target audience: Developers

#2122 [TranslatorBundle] Fix random failing test because of race condition
  src/Kunstmaan/TranslatorBundle/Tests/Repository/TranslationRepositoryTest.php
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2133 [NodeBundle] Revert "Fix bug in NodeChoiceType (#2115)"
  src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2121 [DashboardBundle] Fixed duplicate service id and missing command in command services config
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigFlushCommand.php
  src/Kunstmaan/DashboardBundle/Resources/config/commands.yml
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#2134 [AdminBundle] revert CKeditor to original version
  package.json
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js.map
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2125 [MediaBundle] Folder types as constants
  src/Kunstmaan/MediaBundle/DataFixtures/ORM/FolderFixtures.php
  src/Kunstmaan/MediaBundle/Entity/Folder.php
  src/Kunstmaan/MediaBundle/Form/FolderType.php
Labels: Type: Feature, Type: Needs work

#2150 [MediaBundle] Folder types as constants (part 2)
  src/Kunstmaan/MediaBundle/DataFixtures/ORM/FolderFixtures.php
  src/Kunstmaan/MediaBundle/Entity/Folder.php
Labels: Type: Feature

#2143 [AdminListBundle] Feature/sortable adminlist
  src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
Labels: Type: Bugfix
