Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-10, with the labels that each got.

#2162 [NodeBundle] Improved error shown when a page does not have a view path
  src/Kunstmaan/NodeBundle/Controller/SlugController.php
Labels: Type: Bugfix

#2163 [NodeBundle] Fixed issue where date in passed could be selected when publishing later
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_publish.html.twig
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix, Type: Needs work

#2168 [AdminBundle] Remove duplicate set in sidebar template
  src/Kunstmaan/AdminBundle/Resources/views/Default/sidebar.html.twig
Labels: Type: Bugfix

#2166 [Docs] Fix the links in the github contributing.md file
  .github/CONTRIBUTING.md
Labels: Type: Bugfix

#2159 [AdminListBundle] use datepicker for DateTimeType filters
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-group.scss
  src/Kunstmaan/AdminListBundle/Resources/views/FilterType/dateTimeFilter.html.twig
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix, Type: Improvement

#2156 [TranslatorBundle] fix non-unique locales in TranslationAdminConfigurator
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
Labels: Priority: Low, Profile: Backend, Target audience: Developers, Type: Bugfix

#2167 [AdminBundle][AdminListBundle] Revert code changes for container access deprecation to make symfony 4 upgrade easier
  src/Kunstmaan/AdminBundle/Controller/BaseSettingsController.php
  src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, sf4-compatibility

#2148 [NodeBundle] fix issue finding disctinct classes for deleted files
  src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
Labels: Profile: Backend, Type: Bugfix

#2147 [VotingBundle] [Test] fix namespace tests
  src/Kunstmaan/VotingBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/VotingBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/VotingBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/VotingBundle/Tests/bootstrap.php
  src/Kunstmaan/VotingBundle/Tests/unit.suite.yml
  src/Kunstmaan/VotingBundle/Tests/unit/Controller/VotingControllerTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/DependencyInjection/KunstmaanVotingExtensionTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Entity/AbstractVoteTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/Facebook/FacebookLikeEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/Facebook/FacebookSendEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/LinkedIn/LinkedInShareEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/UpDown/DownVoteEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/UpDown/UpVoteEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/EventListener/Security/MaxNumberByIpEventListenerTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Services/RepositoryResolverTest.php
  src/Kunstmaan/VotingBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2146 [UtilitiesBundle][Tests] fix namespace tests and old mocks
  src/Kunstmaan/UtilitiesBundle/Tests/Helper/DummyClass.php
  src/Kunstmaan/UtilitiesBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/UtilitiesBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/UtilitiesBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit.suite.yml
  src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/KunstmaanUtilitiesExtensionTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/Cipher/CipherTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/Cipher/UrlSafeCipherTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/ClassLookupTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/Shell/ShellTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/SlugifierTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/UrlTransactionNamingStrategyTest.php
  src/Kunstmaan/UtilitiesBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2145 [UsermanagementBundle] [Tests] fix namespace tests
  src/Kunstmaan/UserManagementBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/UserManagementBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/UserManagementBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/UserManagementBundle/Tests/unit.suite.yml
  src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/KunstmaanUserManagementExtensionTest.php
  src/Kunstmaan/UserManagementBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2142 [TaggingBundle] [Tests] fix namespace tests
  src/Kunstmaan/TaggingBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/TaggingBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/TaggingBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/TaggingBundle/Tests/unit.suite.yml
  src/Kunstmaan/TaggingBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagManagerTest.php
  src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagTest.php
  src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TaggableTraitTest.php
  src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TaggingTest.php
  src/Kunstmaan/TaggingBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2141 [SitemapBundle][Tests] fix namespace tests
  src/Kunstmaan/SitemapBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/SitemapBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/SitemapBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/SitemapBundle/Tests/unit.suite.yml
  src/Kunstmaan/SitemapBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/SitemapBundle/Tests/unit/DependencyInjection/KunstmaanSiteMapExtensionTest.php
  src/Kunstmaan/SitemapBundle/Tests/unit/Entity/SiteMapPageTest.php
  src/Kunstmaan/SitemapBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2140 [SeoBundle][Tests] fix namespace tests
  src/Kunstmaan/SeoBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/SeoBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/SeoBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/SeoBundle/Tests/unit.suite.yml
  src/Kunstmaan/SeoBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/DependencyInjection/KunstmaanSeoExtensionTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/Entity/RobotsTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/Entity/SeoTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/Twig/TwigExtensionTests.php
  src/Kunstmaan/SeoBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2139 [SearchBundle][Tests] fix namespace tests
  src/Kunstmaan/SearchBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/SearchBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/SearchBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/SearchBundle/Tests/unit.suite.yml
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Compiler/SearchConfigurationCompilerPassTest.php
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Compiler/SearchProviderCompilerPassTest.php
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Configuration/SearchConfigurationChainTest.php
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/KunstmaanSearchExtensionTest.php
  src/Kunstmaan/SearchBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2138 [RedirectBundle][Tests] fix namespace tests
  src/Kunstmaan/RedirectBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/RedirectBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/RedirectBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/RedirectBundle/Tests/unit.suite.yml
  src/Kunstmaan/RedirectBundle/Tests/unit/AdminList/RedirectAdminListConfiguratorTest.php
  src/Kunstmaan/RedirectBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/RedirectBundle/Tests/unit/DependencyInjection/KunstmaanRedirectExtensionTest.php
  src/Kunstmaan/RedirectBundle/Tests/unit/Entity/RedirectTest.php
  src/Kunstmaan/RedirectBundle/Tests/unit/Form/RedirectAdminTypeTest.php
  src/Kunstmaan/RedirectBundle/Tests/unit/Router/RedirectRouterTest.php
  src/Kunstmaan/RedirectBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2137 [PagePartBundle][Tests] fix namespace tests and remove old mocks
  src/Kunstmaan/PagePartBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/PagePartBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/PagePartBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/PagePartBundle/Tests/unit.suite.yml
  src/Kunstmaan/PagePartBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/DependencyInjection/KunstmaanPagePartExtensionTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/AbstractPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/HeaderPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/LinePagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/LinkPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/PagePartRefTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/PageTemplateConfigurationTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/RawHTMLPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/TextPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/ToTopPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/TocPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/EventListener/CloneListenerTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/HeaderPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/LinePagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/LinkPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/PagePartAdminTypeTestCase.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/RawHTMLPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/TextPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/ToTopPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/TocPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/PagePartConfigurationReader/LocatingKernelStub.php
  src/Kunstmaan/PagePartBundle/Tests/unit/PagePartConfigurationReader/PagePartConfigurationParserTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/PagePartConfigurationReader/Resources/config/pageparts/main-extended.yml
  src/Kunstmaan/PagePartBundle/Tests/unit/PagePartConfigurationReader/Resources/config/pageparts/main.yml
  src/Kunstmaan/PagePartBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2136 [NodeSearchBundle][Tests] fix namespace tests
  src/Kunstmaan/NodeSearchBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/NodeSearchBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/NodeSearchBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit.suite.yml
  src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/KunstmaanNodeSearchExtensionTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Entity/AbstractSearchPageTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Entity/NodeSearchTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Event/IndexNodeEventTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/EventListener/NodeIndexUpdateEventListenerTest.php
  src/Kunstmaan/NodeSearchBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature
