Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-05, with the labels that each got.

#1960 [NodeBundle] Deprecate container usage in the slug router
  UPGRADE-5.1.md
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/Router/SlugRouter.php
Labels: Priority: Normal, Profile: Backend, Type: Deprecation, sf4-compatibility

#1905 [AdminlistBundle] [MediaBundle] Changeablelimitinterface implemented and fixes some bugs
  docs/bundles/adminlist-bundle/configuring-adminlists.md
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/ChangeableLimitInterface.php
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/limit.html.twig
  src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
  src/Kunstmaan/AdminListBundle/Traits/ChangeableLimitTrait.php
  src/Kunstmaan/MediaBundle/AdminList/MediaAdminListConfigurator.php
  src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix, Type: Feature

#1967 [AdminListBundle] fixes forgotten commit new feature changeablelimitinterface
  src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
Labels: Priority: High, Target audience: Developers, Type: Bugfix

#1971 [AdminBundle][AdminListBundle]Fixed yaml translation file deprecations
  src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.pl.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1970 [TranslatorBundle] Mark the translator service aliases as public
  src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1969 [NodeBundle] Mark the router service alias as public
  src/Kunstmaan/NodeBundle/DependencyInjection/Compiler/FixRouterPass.php
  src/Kunstmaan/NodeBundle/KunstmaanNodeBundle.php
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1964 [ConfigBundle] Set the correct configuration entity as active
  src/Kunstmaan/ConfigBundle/Helper/Menu/ConfigMenuAdaptor.php
Labels: Profile: Backend, Type: Bugfix

#1976 [KunstmaanFormBundle] batchsize is not initialized
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
Labels: Profile: Backend, Type: Bugfix

#1939 [UtilitiesBundle] Make parameter kunstmaan_utilities.cipher.secret op…
  src/Kunstmaan/UtilitiesBundle/DependencyInjection/KunstmaanUtilitiesExtension.php
  src/Kunstmaan/UtilitiesBundle/Resources/config/services.yml
  src/Kunstmaan/UtilitiesBundle/Resources/doc/UtilitiesBundle.md
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix, Type: Improvement

#1973 [GeneratorBundle] Fix unquoted parameter in routing generator
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/routing_partial.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1962 [FormBundle] Change form labels to required
  src/Kunstmaan/FormBundle/Form/CheckboxPagePartAdminType.php
  src/Kunstmaan/FormBundle/Form/EmailPagePartAdminType.php
  src/Kunstmaan/FormBundle/Form/MultiLineTextPagePartAdminType.php
  src/Kunstmaan/FormBundle/Form/SingleLineTextPagePartAdminType.php
  src/Kunstmaan/FormBundle/Form/SubmitButtonPagePartAdminType.php
Labels: Profile: Backend, Type: Bugfix, Type: Improvement

#1977 [UtilitiesBundle] Fix UtilitiesExtensionTest after upmerge from 5.0
  src/Kunstmaan/UtilitiesBundle/Tests/DependencyInjection/KunstmaanUtilitiesExtensionTest.php
Labels: Priority: Normal, Profile: Backend

#1978 [SearchBundle] Deprecate service container usage in commands
  UPGRADE-5.1.md
  src/Kunstmaan/SearchBundle/Command/DeleteIndexCommand.php
  src/Kunstmaan/SearchBundle/Command/PopulateIndexCommand.php
  src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
  src/Kunstmaan/SearchBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1974 [MediaBundle] Deprecate service container usage in commands
  UPGRADE-5.1.md
  src/Kunstmaan/MediaBundle/Command/CleanDeletedMediaCommand.php
  src/Kunstmaan/MediaBundle/Command/CreatePdfPreviewCommand.php
  src/Kunstmaan/MediaBundle/Command/RebuildFolderTreeCommand.php
  src/Kunstmaan/MediaBundle/Command/RenameSoftDeletedCommand.php
  src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Type: Deprecation, sf4-compatibility

#1979 [AllBundles] Mark services used in controllers as public
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
  src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1981 [AdminBundle] Extend Role from base symfony class
  src/Kunstmaan/AdminBundle/Entity/Role.php
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1991 [AdminBundle] marked service as public
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1992 [AdminBundle][MultiDomainBundle] deprecated service container usage i…
  UPGRADE-5.1.md
  src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
Labels: Priority: Normal, Profile: Backend, sf4-compatibility
