Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-06, with the labels that each got.

#1986 [NodeBundle] Select correct root node for the urlchooser in a multidomain setup
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
Labels: Priority: Normal, Profile: Backend, Type: Bugfix

#2008 [GeneratorBundle] Update gulp version
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
Labels: Profile: Frontend, Target audience: Developers, Type: Improvement

#2005 [TranslatorBundle] Fix container deprecations with translation loaders
  UPGRADE-5.1.md
  src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPass.php
  src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
  src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
  src/Kunstmaan/TranslatorBundle/Tests/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPassTest.php
Labels: Priority: Normal, Profile: Backend, Type: Deprecation, sf4-compatibility

#1997 [UserManagementBundle] marked service as public using compilerpass
  src/Kunstmaan/UserManagementBundle/DependencyInjection/Compiler/FixUserManagerPass.php
  src/Kunstmaan/UserManagementBundle/KunstmaanUserManagementBundle.php
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1998 [UserManagementBundle][SeoBundle] Deprecate direct container access i…
  UPGRADE-5.1.md
  src/Kunstmaan/AdminBundle/Controller/BaseSettingsController.php
  src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
  src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
  src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#1999 [AdminBundle][NodeBundle] added new AclManager to handle acl dependen…
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Service/AclManager.php
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Feature, sf4-compatibility

#2004 [NodeBundle] Reword deprecation message and provide alternative to the end-user
  UPGRADE-5.1.md
  src/Kunstmaan/NodeBundle/Entity/AbstractPage.php
  src/Kunstmaan/NodeBundle/Entity/PageInterface.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2006 [AdminBundle][MultiDomainBundle] Inject correct services/parameters so our code doesn't trigger deprecations
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminListBundle/Tests/Helper/DomainConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/KunstmaanMultiDomainExtension.php
  src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/MultiDomainBundle/Resources/config/services.yml
  src/Kunstmaan/MultiDomainBundle/Tests/DependencyInjection/KunstmaanMultiDomainExtensionTest.php
  src/Kunstmaan/TranslatorBundle/Tests/app/config/parameters.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix, Type: Feature, sf4-compatibility

#2001 [AdminBundle] updated aclUpdateCommand to use AclManager
  src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Service/AclManager.php
Labels: Priority: Normal, Type: Deprecation, Type: Feature, sf4-compatibility

#2019 [FormBundle] added deletable formsubmissions
  UPGRADE-5.1.md
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionAdminListConfigurator.php
  src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
  src/Kunstmaan/FormBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/FormBundle/DependencyInjection/KunstmaanFormExtension.php
  src/Kunstmaan/FormBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/FormBundle/Resources/views/FormSubmissions/edit.html.twig
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Feature

#2017 [AllBundles] Bump the framework-extra-bundle version for sf4 support
  composer.json
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2016 [AllBundles] Remove unused "symfony/assetic-bundle" dependency
  UPGRADE-5.1.md
  composer.json
Labels: Priority: Normal, Profile: Backend, Type: Improvement, sf4-compatibility

#2015 [AllBundles] Use the same version constraints as symfony for egulias/email-validator
  composer.json
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Feature, Type: Improvement, sf4-compatibility

#2013 [NodeBundle][TranslatorBundle] Mark extra services public
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2018 [AdminBundle][MultidomainBundle] Move parameter checks and service definition changes to compiler pass
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/DomainConfigurationPass.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
  src/Kunstmaan/AdminBundle/Tests/KunstmaanAdminBundleTest.php
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/CompilerPass/MultidomainConfigurationPass.php
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/KunstmaanMultiDomainExtension.php
  src/Kunstmaan/MultiDomainBundle/KunstmaanMultiDomainBundle.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix, Type: Feature

#2012 [TranslatorBundle][UserManagementBundle] Replace getParameter calls so our code doesn't trigger deprecations
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix, Type: Feature, sf4-compatibility

#2003 [AdminBundle] updated aclApplyCommand to use AclManager
  UPGRADE-5.1.md
  src/Kunstmaan/AdminBundle/Command/ApplyAclCommand.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Service/AclManager.php
Labels: Profile: Backend, Type: Feature, sf4-compatibility

#2014 [AdminBundle] Deprecate service container usage in commands
  UPGRADE-5.1.md
  src/Kunstmaan/AdminBundle/Command/CreateGroupCommand.php
  src/Kunstmaan/AdminBundle/Command/CreateRoleCommand.php
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
  src/Kunstmaan/AdminBundle/Command/ExceptionCommand.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Resources/config/commands.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation, sf4-compatibility

#1996 [AdminBundle] fixed create user command #1995
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#1990 [Docs] set correct paths
  README.md
Labels: Type: Bugfix, Type: Documentation

#1989 [KunstmaanAdminBundle] fix js for collections
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js.map
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_nested-form.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/app.js
Labels: Priority: High, Profile: Frontend, Type: Bugfix

#1987 [GeneratorBundle] Replace deprecated twig raw tag in scss file
  composer.json
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/general/_colors.scss
  src/Kunstmaan/GeneratorBundle/composer.json
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix

#1803 [NodeBundle] save on (un)publish
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
  src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_publish.html.twig
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_unpublish.html.twig
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
Labels: Priority: High, Profile: Backend, Type: Bugfix

#1963 [MediaBundle] Add target blank to download link
  src/Kunstmaan/MediaBundle/Resources/views/Media/File/show.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Media/Image/show.html.twig
Labels: Profile: Backend, Target audience: Developers, Type: Feature

#1953 [Docs] remove vagrant references and put some small snippet about docker in
  docs/contributing/pull-requests.md
  docs/getting-started/index.md
  docs/images/wizard.png
  docs/installation/demo-environment.md
  docs/installation/development-environment.md
  docs/installation/index.md
  docs/installation/system-requirements.md
Labels: Target audience: Developers, Type: Documentation, Type: Improvement

#2027 [NodeBundle] Split off logic of NodeAdminController in helper class
  src/Kunstmaan/NodeBundle/Exception/NoNodeTranslationException.php
  src/Kunstmaan/NodeBundle/Helper/NodeHelper.php
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/Tests/Helper/NodeHelperTest.php
Labels: Profile: Backend, Target audience: Developers, Type: Improvement

#2038 [AdminBundle] added missing translations to main language
  src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
Labels: Priority: Low, Profile: Backend, Target audience: Developers, Type: Bugfix

#2041 [AdminBundle] remove hardcopy of ckeditor
  groundcontrol/admin-bundle.tasks.js
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/public/default-theme/ckeditor/ckeditor.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js.map
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js.map
  src/Kunstmaan/DashboardBundle/Resources/public/css/dashboard.css
Labels: Profile: Frontend, Target audience: Developers, Type: Bugfix
