Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-11, with the labels that each got.

#2170 [GeneratorBundle] Remove unnecessary roles on dom nodes
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Layout/submenu.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/SearchPage/pagetemplate.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_breadcrumbs.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_footer.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_header.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_mobile-nav.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Resources/views/Pages/SearchPage/view.html.twig
Labels: Priority: Normal, Profile: Frontend, Target audience: Developers, Type: Bugfix

#2151 [AllBundles] Disable styleci checks for 5.0
  .styleci.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2131 [MultiDomainBundle] [tests] fix namespace tests
  src/Kunstmaan/MultiDomainBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/MultiDomainBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/MultiDomainBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit.suite.yml
  src/Kunstmaan/MultiDomainBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/DependencyInjection/KunstmaanMultiDomainExtensionTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/EventListener/HostOverrideListenerTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/AdminPanel/SitesAdminPanelAdaptorTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/DomainConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/HostOverrideCleanupHandlerTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Router/DomainBasedLocaleRouterTest.php
  src/Kunstmaan/MultiDomainBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2130 [MenuBundle] [Tests] fix tests namespace
  src/Kunstmaan/MenuBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/MenuBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/MenuBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/MenuBundle/Tests/unit.suite.yml
  src/Kunstmaan/MenuBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MenuBundle/Tests/unit/DependencyInjection/KunstmaanMenuExtensionTest.php
  src/Kunstmaan/MenuBundle/Tests/unit/Entity/BaseMenuTest.php
  src/Kunstmaan/MenuBundle/Tests/unit/Entity/MenuItemTest.php
  src/Kunstmaan/MenuBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2129 [MediaPagePartBundle] [tests] fix namespace tests
  src/Kunstmaan/MediaPagePartBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/MediaPagePartBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/MediaPagePartBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit.suite.yml
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/DependencyInjection/KunstmaanMediaPagePartExtensionTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/AudioPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/DownloadPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/ImagePagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/SlidePagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/VideoPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2128 [MediaBundle] [tests] fix namespace tests
  src/Kunstmaan/MediaBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/MediaBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/MediaBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/MediaBundle/Tests/unit.suite.yml
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/Compiler/MediaHandlerCompilerPassTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/KunstmaanMediaExtensionTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Entity/FolderTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Entity/MediaTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Files/sample.pdf
  src/Kunstmaan/MediaBundle/Tests/unit/Form/AbstractTypeTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/File/FileHelperTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/File/PdfHandlerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/FolderManagerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/MediaManagerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/RemoteAudio/RemoteAudioHelperTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/RemoteSlide/RemoteSlideHelperTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/RemoteVideo/RemoteVideoHandlerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/RemoteVideo/RemoteVideoHelperTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/Transformer/PdfTransformerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Utils/SymfonyVersionTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Validator/Constraints/MediaValidatorTest.php
  src/Kunstmaan/MediaBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2127 [LeadGenerationBundle] [Tests] fix namespace tests
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Configurator/AbstractDoctrineORMAdminListConfiguratorTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/LeadGenerationBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/LeadGenerationBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit.suite.yml
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/DependencyInjection/KunstmaanLeadGenerationExtensionTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Popup/AbstractPopupTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Popup/Popup.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/AfterXScrollPercentRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/AfterXSecondsRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/LocaleBlacklistRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/LocaleWhitelistRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/MaxXTimesRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/OnExitIntentRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/RecurringEveryXTimeRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/UrlBlacklistRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/UrlWhitelistRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2113 [FixturesBundle] [tests] fix namespace tests
  src/Kunstmaan/FixturesBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/FixturesBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/FixturesBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/FixturesBundle/Tests/unit.suite.yml
  src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/Compiler/BuilderCompilerPassTest.php
  src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/Compiler/ParserCompilerPassTest.php
  src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/Compiler/PopulatorCompilerPassTest.php
  src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/Compiler/ProviderCompilerPassTest.php
  src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/KunstmaanFixturesExtensionTest.php
  src/Kunstmaan/FixturesBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2112 [DashboardBundle] [Tests] fix namespace tests
  src/Kunstmaan/DashboardBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/DashboardBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/DashboardBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/DashboardBundle/Tests/unit.suite.yml
  src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/Compiler/WidgetCompilerPassTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/KunstmaanDashboardExtensionTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsConfigTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsGoalTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsOverviewTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsSegmentTest.php
  src/Kunstmaan/DashboardBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2110 [BehatBundle] [Tests] fix namespace tests
  src/Kunstmaan/BehatBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/BehatBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/BehatBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/BehatBundle/Tests/unit.suite.yml
  src/Kunstmaan/BehatBundle/Tests/unit/.gitkeep
  src/Kunstmaan/BehatBundle/codeception.yml
Labels: Type: Bugfix, Type: Feature

#2172 [GeneratorBundle] fix gulp dependency
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
Labels: Priority: High, Profile: Frontend, Target audience: Developers, Type: Bugfix

#2174 [AdminBundle] Fix icons ckeditor again
  src/Kunstmaan/AdminBundle/Resources/public/default-theme/ckeditor/plugins/icons.png
  src/Kunstmaan/AdminBundle/Resources/public/default-theme/ckeditor/plugins/icons_hidpi.png
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2158 [MediaBundle] Added image sizes to media chooser
  src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
Labels: Profile: Backend, Profile: Frontend, Type: Feature

#2178 [Docs] Fix slack channel link
  README.md
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2179 [GeneratorBundle] update FE buildtools
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/js/app.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/js/demoMsg.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/js/search.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/js/videolink.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/blocks/_buttons.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/footer/_main-footer.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/footer/_sub-footer.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/forms/_form-widget.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/forms/_radio-checkbox.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/header/_language-nav.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/header/_main-header.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/header/_search-form.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/pageparts/_download-pp.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/pageparts/_link-pp.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/pageparts/_service-pp.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/pageparts/_text-pp.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_breadcrumb-nav.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_cookie-consent.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_demosite-msg.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_filters.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_newsletter.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_pagination.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_search-results.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_submenu.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/general/_colors.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/general/_sizes.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/vendors/_bootstrap-imports.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/vendors/_bootstrap-vars.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/general/typography/_iconfont.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/helpers/mixins/_horizontal-list.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/styleguide/scss/config/_config.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/styleguide/scss/config/vendors/_prism-imports.scss
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/styleguide/templates/layout.hbs
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/.eslintrc
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/.nvmrc
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/.stylelintrc
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.admin-extra.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.app.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.default.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.styleguide.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/configured-tasks.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/console-arguments.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/bundle.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/clean.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/copy.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/css.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/eslint.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/inject.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/jest.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/livingcss.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/server.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/stylelint.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/gulpfile.babel.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
Labels: Profile: Frontend, Target audience: Developers, Type: Improvement

#2180 [AllBundles] Changes for upcoming travis-ci infra migration
  .travis.yml
Labels: Priority: Normal, Target audience: Developers

#2090 [AllBundles] Bump minimum php version to 7.1
  .travis.yml
  composer.json
  docs/installation/system-requirements.md
  docs/introduction/index.md
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/ArticleBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/DashboardBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/GeneratorBundle/composer.json
  src/Kunstmaan/LeadGenerationBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/MediaPagePartBundle/composer.json
  src/Kunstmaan/MenuBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/composer.json
  src/Kunstmaan/PagePartBundle/composer.json
  src/Kunstmaan/RedirectBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/SeoBundle/composer.json
  src/Kunstmaan/SitemapBundle/composer.json
  src/Kunstmaan/TaggingBundle/composer.json
  src/Kunstmaan/TranslatorBundle/composer.json
  src/Kunstmaan/UserManagementBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2183 [MediaBundle] Fix php 5.6 incompatibilty with the ChangeableLimitTrait
  src/Kunstmaan/MediaBundle/AdminList/MediaAdminListConfigurator.php
Labels: Priority: Normal, Type: Bugfix
