Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-03, with the labels that each got.

#1859 [LeadGenerationBundle]: remove jquery dependency leadgeneration bundle
  src/Kunstmaan/LeadGenerationBundle/Resources/public/js/popup/Popup.js
  src/Kunstmaan/LeadGenerationBundle/Resources/public/js/popup/PopupManager.js
  src/Kunstmaan/LeadGenerationBundle/Resources/public/js/rule/AfterXScrollPercentRule.js
  src/Kunstmaan/LeadGenerationBundle/Resources/views/Newsletter/thanks.html.twig
Labels: Profile: Frontend, Type: Bugfix, Type: Deprecation

#1862 [AdminBundle]: redirect to previous page when logging in with Google
  src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
Labels: Profile: Backend, Type: Bugfix

#1860 [GeneratorBundle]: fixes for article generator
  src/Kunstmaan/ArticleBundle/Router/TagCategoryRouter.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminTypePartial.php.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/pagetemplate.html.twig
Labels: Profile: Backend, Type: Bugfix

#1851 [SeoBundle]: fields are not required
  src/Kunstmaan/SeoBundle/Form/SeoType.php
Labels: Profile: Backend, Type: Bugfix

#1840 [NodeBundle]: deprecate service function
  src/Kunstmaan/NodeBundle/Entity/AbstractPage.php
  src/Kunstmaan/NodeBundle/Entity/PageInterface.php
Labels: Profile: Backend, Target audience: Developers, Type: Deprecation

#1819 [NodeBundle] Check for mapping exception when multiple entity manager…
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
Labels: Priority: Low, Profile: Backend, Target audience: Developers, Type: Bugfix

#1864 [GeneratorBundle] Fixed bundle namespace in article generator pagepart config
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/pageparts/main.yml
Labels: Profile: Backend, Type: Bugfix

#1869 [KunstmaanAdminBundle]: fix permissions
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
Labels: Priority: High, Profile: Backend, Type: Bugfix

#1854 [AdminBundle] Make it possible to search in all PagePartChoosers
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/config.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/index.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/pagepart-search/initSearch.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/pagepart-search/resetSearch.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/pagepart-search/updateSearch.js
Labels: Profile: Frontend, Type: Bugfix

#1867 [All] Linting changes
  groundcontrol/admin-bundle.tasks.js
  groundcontrol/dashboard-bundle.tasks.js
  groundcontrol/media-bundle.tasks.js
  groundcontrol/translator-bundle.tasks.js
  gulpfile.babel.js
Labels: Profile: Frontend, Type: Improvement

#1871 [GeneratorBundle] Fixed limit in generated article repository
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/PageRepositoryPartial.php.twig
Labels: Profile: Backend, Type: Bugfix

#1870 [GeneratorBundle] Add imagemin to Groundcontrol tasks
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/configured-tasks.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/images.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/gulpfile.babel.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
Labels: Profile: Frontend, Target audience: Developers, Type: Improvement

#1865 [LeadGenerationBundle]: times should not be blank
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/RecurringEveryXTimeRule.php
Labels: Profile: Backend, Type: Bugfix

#1790 [NodeBundle] allow to set icon for tree
  UPGRADE-5.1.md
  src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
  src/Kunstmaan/NodeBundle/Helper/PagesConfiguration.php
  src/Kunstmaan/NodeBundle/Helper/TreeIconInterface.php
Labels: Profile: Backend, Type: Feature

#1874 [GeneratorBundle] Change logic of page title
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
Labels: Profile: Backend, Profile: Frontend, Type: Bugfix

#1642 Set default list template in constructor instead of hard coded getter
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractPageAdminListConfigurator.php
Labels: Priority: Low, Profile: Backend, Target audience: Developers, Type: Improvement

#1690 [SensiolabsInsight] Changed method visibility for non-action methods in controller classes
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
  src/Kunstmaan/LeadGenerationBundle/Controller/PopupsAdminListController.php
  src/Kunstmaan/LeadGenerationBundle/Controller/RulesAdminListController.php
  src/Kunstmaan/MediaBundle/Controller/MediaController.php
  src/Kunstmaan/MenuBundle/Controller/MenuAdminListController.php
  src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
  src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
  src/Kunstmaan/TaggingBundle/Controller/TagAdminListController.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
Labels: Profile: Backend, Type: BC break, Type: Bugfix

#1715 [AdminBundle] - Fix MultiDomainAdminTwigExtension::switchedHostIsCurr…
  src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
  src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
Labels: Profile: Backend, Type: Improvement

#1875 [NodeSearchBundle] Elastic search version 6 support
  composer.json
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
  src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
  src/Kunstmaan/NodeSearchBundle/Resources/doc/ElasticSearch.md
Labels: Type: Improvement
