Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-12, with the labels that each got.

#2184 [AllBundles] Replace deprecated Route/Method annotations
  src/Kunstmaan/AdminBundle/Controller/DefaultController.php
  src/Kunstmaan/AdminBundle/Controller/ExceptionController.php
  src/Kunstmaan/AdminBundle/Controller/ModulesController.php
  src/Kunstmaan/AdminBundle/Controller/SettingsController.php
  src/Kunstmaan/CacheBundle/Controller/VarnishController.php
  src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
  src/Kunstmaan/DashboardBundle/Controller/DashboardController.php
  src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsAJAXController.php
  src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
  src/Kunstmaan/DashboardBundle/Widget/DashboardWidget.php
  src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/Controller/EntityAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/CategoryAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/TagAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/bundle/DefaultController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/BikeAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/DefaultController.php
  src/Kunstmaan/LeadGenerationBundle/Controller/AbstractNewsletterController.php
  src/Kunstmaan/LeadGenerationBundle/Controller/AbstractRedirectController.php
  src/Kunstmaan/LeadGenerationBundle/Controller/PopupsAdminListController.php
  src/Kunstmaan/LeadGenerationBundle/Controller/RulesAdminListController.php
  src/Kunstmaan/MediaBundle/Controller/AviaryController.php
  src/Kunstmaan/MediaBundle/Controller/ChooserController.php
  src/Kunstmaan/MediaBundle/Controller/FolderController.php
  src/Kunstmaan/MediaBundle/Controller/IconFontController.php
  src/Kunstmaan/MediaBundle/Controller/MediaController.php
  src/Kunstmaan/MenuBundle/Controller/MenuAdminListController.php
  src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
  src/Kunstmaan/MultiDomainBundle/Controller/SiteSwitchController.php
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
  src/Kunstmaan/NodeBundle/Controller/UrlReplaceController.php
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/PagePartBundle/Controller/PagePartAdminController.php
  src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
  src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
  src/Kunstmaan/SeoBundle/Controller/RobotsController.php
  src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
  src/Kunstmaan/TaggingBundle/Controller/TagAdminListController.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
  src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
  src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
  src/Kunstmaan/VotingBundle/Controller/VotingController.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2098 [MediaBundle] Liip imagine bundle version 2 support
  composer.json
  src/Kunstmaan/MediaBundle/DependencyInjection/Compiler/MediaHandlerCompilerPass.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaBundle/Helper/Transformer/PreviewTransformerInterface.php
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/KunstmaanMediaExtensionTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2061 [AllBundles] Require individual symfony packages
  UPGRADE-5.2.md
  composer.json
  src/Kunstmaan/AdminBundle/Tests/unit/EventListener/PasswordCheckListenerTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/AbstractFormPageTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/AppKernel.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/config/config.yml
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/config/security.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2185 [AdminBundle] Remove unused RoleInterface on the group entity
  UPGRADE-5.2.md
  src/Kunstmaan/AdminBundle/Entity/Group.php
  src/Kunstmaan/AdminBundle/Entity/GroupPropertiesTrait.php
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2188 [ConfigBundle] Remove route service annotation as default route is already provided as service
  src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
  src/Kunstmaan/ConfigBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix

#2192 [FormBundle] Mark services used in controllers as public
  src/Kunstmaan/FormBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2190 [AdminBundle] Only use session in toolbar listener if it was started before
  src/Kunstmaan/AdminBundle/EventListener/ToolbarListener.php
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2191 [NodeSearchBundle] Added tag for node searcher services
  UPGRADE-5.2.md
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/Compiler/NodeSearcherCompilerPass.php
  src/Kunstmaan/NodeSearchBundle/KunstmaanNodeSearchBundle.php
  src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
  src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/Compiler/NodeSearcherCompilerPassTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Services/SearchServiceTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2193 [MediaBundle] Fix incorrect service name in media compilerpass
  src/Kunstmaan/MediaBundle/DependencyInjection/Compiler/MediaHandlerCompilerPass.php
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/Compiler/MediaHandlerCompilerPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix, sf4-compatibility

#2195 [DashboardBundle] Set correct template path for widget action
  src/Kunstmaan/AdminBundle/Controller/DefaultController.php
  src/Kunstmaan/AdminBundle/Controller/ModulesController.php
  src/Kunstmaan/AdminBundle/Controller/SettingsController.php
  src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
  src/Kunstmaan/TaggingBundle/Controller/TagAdminListController.php
Labels: Priority: High, Profile: Backend, Type: BC break, Type: Bugfix

#2202 [AllBundles] Add php-cs-fixer cache to gitignore
  .gitignore
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2044 [NodeBundle] Add tabs
  UPGRADE-5.1.md
  src/Kunstmaan/NodeBundle/Entity/PageTabInterface.php
  src/Kunstmaan/NodeBundle/EventListener/EntityTabListener.php
  src/Kunstmaan/NodeBundle/EventListener/NodeListener.php
  src/Kunstmaan/NodeBundle/EventListener/NodeTabListener.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/NodeTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Helper/NodeHelperTest.php
  src/Kunstmaan/NodeBundle/ValueObject/PageTab.php
  src/Kunstmaan/NodeBundle/entity-tabs.md
Labels: Profile: Backend, Target audience: Administrators, Type: Feature, Type: Improvement

#2204 [AllBundles] Improve travis test suite
  .travis.yml
Labels: Priority: Normal, Target audience: Developers

#2201 [AdminBundle] Move websitetitle to bundle config to remove extra parameter
  src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/KunstmaanAdminExtensionTest.php
  src/Kunstmaan/SeoBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2198 [AllBundles] Ignore generated files from codeception
  .gitignore
  src/Kunstmaan/AdminBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/AdminListBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/ArticleBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/BehatBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/ConfigBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/DashboardBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/FixturesBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/FormBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/GeneratorBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/LeadGenerationBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/MediaBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/MediaPagePartBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/MenuBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/MultiDomainBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/NodeBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/NodeSearchBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/PagePartBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/RedirectBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/SearchBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/SeoBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/SitemapBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/TaggingBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/TranslatorBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/UserManagementBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/UtilitiesBundle/Tests/_support/_generated/UnitTesterActions.php
  src/Kunstmaan/VotingBundle/Tests/_support/_generated/UnitTesterActions.php
Labels: Priority: Normal, Target audience: Developers

#2197 [UtilitiesBundle] Deprecate direct set of parameter and use kernel.secret by default
  src/Kunstmaan/UtilitiesBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/UtilitiesBundle/DependencyInjection/KunstmaanUtilitiesExtension.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/KunstmaanUtilitiesExtensionTest.php
Labels: Priority: Normal, Target audience: Developers, Type: Deprecation

#2189 [ArticleBundle] Improve deprecation messages and add missing line in upgrade doc
  UPGRADE-5.1.md
  src/Kunstmaan/ArticleBundle/Entity/AbstractAuthor.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractCategory.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractTag.php
Labels: Priority: Normal, Target audience: Developers

#2200 [NodeSearchBundle] Mark search service public for use in search commands
  src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2203 [AllBundles] Add php 7.3 to travis build
  .travis.yml
  src/Kunstmaan/AdminBundle/Tests/unit/Form/MediaTokenTransformerTest.php
Labels: Priority: Normal, Target audience: Developers

#2196 [AdminBundle] Provide fos/user-bundle default values for from_email config
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2205 [AdminBundle] fixed sf4 deprecation in OAuthAuthenticator
  src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
Labels: Priority: High, Profile: Backend, Type: Deprecation, sf4-compatibility
