Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-08, with the labels that each got.

#2062 [composer] readd swiftmailer bundle
  UPGRADE-5.1.md
  composer.json
Labels: Priority: High, Profile: Backend, Type: Bugfix

#2064 [AdminBundle] #2050 Fixed issue in refreshing ck editor (don't do a destroy if the …
  src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js
Labels: Profile: Frontend, Target audience: Developers, Type: Bugfix

#2067 [NodeBundle] Remove unused vardumper use
  src/Kunstmaan/ArticleBundle/Router/TagCategoryRouter.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2066 [MediaBundle] Skip test if ghostscript is not installed
  src/Kunstmaan/MediaBundle/Tests/Helper/Transformer/PdfTransformerTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix

#2028 [MediaBundle] Fixed BackgroundFilterLoader issue
  src/Kunstmaan/MediaBundle/Helper/Imagine/BackgroundFilterLoader.php
Labels: Priority: High, Profile: Backend, Type: Bugfix

#2049 [AdminBundle] Remove id of nested form item containers
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
Labels: Profile: Frontend, Target audience: Developers, Type: Bugfix

#2068 [AllBundles] Support symfony/swiftmailerBundle 3
  composer.json
  src/Kunstmaan/FormBundle/Helper/FormMailer.php
  src/Kunstmaan/FormBundle/Tests/Helper/FormMailerTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2069 [AllBundles] Explicitly set the template path for user bundle templates
  src/Kunstmaan/AdminBundle/Controller/DefaultController.php
  src/Kunstmaan/MediaBundle/Controller/FolderController.php
  src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
  src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
Labels: Priority: High, Profile: Backend, Type: BC break, Type: Bugfix

#2065 [PagePartBundle] Add has_page_parts Twig function
  src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
Labels: Profile: Backend, Profile: Frontend, Type: Feature

#1994 [KunstmaanNodeBundle] add configuration option for export page template
  UPGRADE-5.1.md
  src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
  src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/NodeBundle/Tests/DependencyInjection/KunstmaanNodeExtensionTest.php
Labels: Profile: Backend, Type: Feature, Type: Improvement

#2021 [AdminBundle] moved acl commands service registrations to commands.yml
  src/Kunstmaan/AdminBundle/Command/ApplyAclCommand.php
  src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
  src/Kunstmaan/AdminBundle/Resources/config/commands.yml
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Type: Improvement, sf4-compatibility

#2076 [MediaBundle] add return to load function
  src/Kunstmaan/MediaBundle/Helper/Imagine/BackgroundFilterLoader.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#2075 [KunstmaanNodeSearchBundle] use hosts in useVersion6 check
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
  src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#1948 [Translations] New Crowdin translations
  src/Kunstmaan/AdminBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/AdminBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/AdminBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/AdminBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/AdminBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/AdminBundle/Resources/translations/messages.pl.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.pl.yml
  src/Kunstmaan/ArticleBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/ArticleBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/ArticleBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/ArticleBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/ArticleBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/ArticleBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/ArticleBundle/Resources/translations/messages.pl.yml
  src/Kunstmaan/CacheBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/CacheBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/DashboardBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.pl.yml
  src/Kunstmaan/GeneratorBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/LeadGenerationBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/LeadGenerationBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/MenuBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/MenuBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/MultiDomainBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/MultiDomainBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/NodeSearchBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/PagePartBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/PagePartBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/RedirectBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/SeoBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/SeoBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/SeoBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/TaggingBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/UserManagementBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/UserManagementBundle/Resources/translations/messages.hu.yml
Labels: Type: Translations

#2073 [NodeBundle] Deprecate unused TemplateEngine constructor argument
  src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2078 [NodeSearchBundle] check if params exist while building container
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#2080 [AdminBundle] Fix broken console exception tests
  src/Kunstmaan/AdminBundle/Tests/EventListener/ConsoleExceptionListenerTest.php
  src/Kunstmaan/AdminBundle/Tests/EventListener/ConsoleExceptionSubscriberTest.php
  src/Kunstmaan/AdminBundle/Tests/KunstmaanAdminBundleTest.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix, Type: Feature

#2086 [NodeBundle] Add missing upgrade note for PR #2073
  UPGRADE-5.1.md
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Documentation

#2026 [TranslatorBundle] add status field on translations for later use in rest api
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
  src/Kunstmaan/TranslatorBundle/Entity/Translation.php
  src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/TranslatorBundle/Tests/Repository/TranslationRepositoryTest.php
  src/Kunstmaan/TranslatorBundle/Tests/files/fixtures.yml
Labels: Profile: Backend, Target audience: Administrators, Type: Feature

#2088 [Translations] New Crowdin translations
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.pl.yml
Labels: Profile: Backend, Target audience: Administrators

#2022 [DashboardBundle] Deprecated service container usage in dashboard com…
  UPGRADE-5.1.md
  src/Kunstmaan/DashboardBundle/Command/DashboardCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigFlushCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigsListCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataFlushCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsListCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsSegmentsListCommand.php
  src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
  src/Kunstmaan/DashboardBundle/Resources/config/commands.yml
Labels: Priority: Normal, Profile: Backend, Type: Deprecation, sf4-compatibility

#2089 [AllBundles] Add php 7.2 to test matrix
  .travis.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers
