Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2018-04, with the labels that each got.

#1883 [AllBundles] Deprecate unused controller actions and document changes
  UPGRADE-5.1.md
  src/Kunstmaan/ArticleBundle/Controller/AbstractArticleEntityAdminListController.php
  src/Kunstmaan/MediaBundle/Controller/MediaController.php
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
Labels: Profile: Backend, Type: Deprecation

#1885 [AdminBundle] Fix Bootstrap modals on smaller screens
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/config/vendors/bootstrap/_bootstrap-vars.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__content.scss
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#1882 [MediaBundle]: bulk move media in folders
  groundcontrol/media-bundle.tasks.js
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js.map
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/structures/_media-thumbnail.scss
  src/Kunstmaan/DashboardBundle/Resources/public/css/dashboard.css
  src/Kunstmaan/MediaBundle/Controller/MediaController.php
  src/Kunstmaan/MediaBundle/Form/BulkMoveMediaType.php
  src/Kunstmaan/MediaBundle/Repository/MediaRepository.php
  src/Kunstmaan/MediaBundle/Resources/public/js/media-bundle.min.js
  src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/MediaBundle/Resources/ui/js/_bulk-move.js
  src/Kunstmaan/MediaBundle/Resources/ui/js/app.js
  src/Kunstmaan/MediaBundle/Resources/views/Folder/bulk-move-modal.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Folder/bulk-move-modal_form.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
Labels: Profile: Backend, Type: Feature

#1877 [NodeSearchBundle] [SearchBundle] ElasticSearch Backport so we can support bundles 3.6 websites on servers with ES6
  .travis.yml
  composer.json
  docs/04-05-adding-a-search-engine.md
  src/Kunstmaan/AdminBundle/Resources/config/console_listener.yml
  src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
  src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
  src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
  src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
  src/Kunstmaan/NodeSearchBundle/Helper/IndexablePagePartsService.php
  src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
  src/Kunstmaan/NodeSearchBundle/Resources/config/update_listener.yml
  src/Kunstmaan/NodeSearchBundle/Resources/doc/ElasticSearch.md
  src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
  src/Kunstmaan/SearchBundle/Command/PopulateIndexCommand.php
  src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
  src/Kunstmaan/SearchBundle/Configuration/SearchConfigurationInterface.php
  src/Kunstmaan/SearchBundle/DependencyInjection/KunstmaanSearchExtension.php
  src/Kunstmaan/SearchBundle/Resources/config/services.yml
  src/Kunstmaan/SearchBundle/Search/AbstractAnalysisFactory.php
  src/Kunstmaan/SearchBundle/Search/Search.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: BC break, Type: Bugfix, Type: Deprecation, Type: Feature

#1887 [FormBundle]: add batchsize to export list
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
Labels: Profile: Backend, Type: Bugfix

#1891 [NodeBundle]: node data collector should go to node id
  src/Kunstmaan/NodeBundle/Toolbar/NodeDataCollector.php
Labels: Profile: Backend, Target audience: Administrators, Type: Bugfix

#1890 [AdminListBundle] Start and end form using tab pane form view, if it exists
  src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig
Labels: Profile: Backend, Target audience: Administrators, Type: Bugfix

#1868 [KunstmaanAdminBundle]: access level for google should add groups
  docs/cookbook/enabling-google-auth-login.md
  src/Kunstmaan/AdminBundle/Helper/Security/OAuth/OAuthUserCreator.php
Labels: Profile: Backend, Type: Bugfix

#1889 [MultiDomainBundle]: host override should be set before getting default locale
  src/Kunstmaan/MultiDomainBundle/Controller/SiteSwitchController.php
Labels: Profile: Backend, Type: Bugfix

#1912 [GeneratorBundle] Fix article generator for no-interaction
  src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#1914 [AdminBundle] Update add new translation
  src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
Labels: Priority: Low, Profile: Backend, Target audience: Administrators, Type: Bugfix

#1916 [AdminBundle] Change default value enable toolbar helper
  src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
Labels: Priority: Low, Profile: Backend, Target audience: Developers, Type: Improvement

#1917 [Generator][[Translator] Trusted proxies is deprecated
  src/Kunstmaan/GeneratorBundle/Tests/data/app/config/config.yml
  src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
Labels: Profile: Backend, Target audience: Developers, Type: Deprecation

#1911 [Documentation] remove addition to upgrade guide that was merged in incorrectly
  UPGRADE-5.0.md
Labels: Priority: Low, Profile: Backend, Target audience: Developers, Type: Bugfix

#1925 [AdminlistBundle] fixed type from string to array
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
Labels: Profile: Backend, Target audience: Developers

#1932 [MenuBundle] Change new window required
  src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
Labels: Priority: Normal, Profile: Backend, Target audience: Administrators, Type: Bugfix

#1934 [FormBundle] Change label required for choice pagepart
  src/Kunstmaan/FormBundle/Form/ChoicePagePartAdminType.php
Labels: Priority: Normal, Profile: Backend, Target audience: Administrators, Type: Bugfix

#1933 [Form] Update regex translation
  src/Kunstmaan/FormBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/FormBundle/Resources/translations/messages.pl.yml
Labels: Profile: Backend, Type: Bugfix, Type: Improvement

#1585 [TranslatorBundle] Allow importing translations from an external xlsx, ods, csv file.
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsFromFileCommand.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
  src/Kunstmaan/TranslatorBundle/Form/TranslationsFileUploadType.php
  src/Kunstmaan/TranslatorBundle/Resources/config/commands.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/TranslatorBundle/Resources/views/Translator/list.html.twig
  src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/CSVFileExporter.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
Labels: Priority: Low, Profile: Backend, Target audience: Developers, Type: Feature

#1500 [MediaBundle] Create runtime config hash using the original image path
  src/Kunstmaan/MediaBundle/Helper/Imagine/CacheManager.php
Labels: Profile: Backend, Type: Bugfix

#1942 [KunstmaanUtilitiesBundle]: assert bundle is only installed in dev
  src/Kunstmaan/UtilitiesBundle/Helper/Cipher/Cipher.php
Labels: Profile: Backend, Type: Bugfix

#1943 [Travis][Tests] fix tests + update travis config
  .travis.yml
  src/Kunstmaan/AdminBundle/Tests/Helper/Security/OAuth/OAuthUserCreatorTest.php
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix, Type: Feature

#1945 [SensioInsights] adjust sensiolabs config
  .sensiolabs.yml
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#1944 [Docs] Add slack channel to README.md
  README.md
Labels: Priority: Low, Profile: UX, Target audience: Administrators, Target audience: Developers, Target audience: Visitors, Type: Documentation

#1941 [AdminBundle]: toolbar should check if logged in in main firewall
  src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/EventListener/ToolbarListener.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
Labels: Profile: Backend, Type: Bugfix

#1940 [NodeSearchBundle]: elasticsearch util should check the running version of elasticsearch
  src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
Labels: Profile: Backend, Type: Bugfix

#1921 [ArticleBundle] Add deprecation error when using entities directly th…
  src/Kunstmaan/ArticleBundle/Entity/AbstractAuthor.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractCategory.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractTag.php
Labels: Priority: Low, Profile: Backend, Target audience: Developers, Type: Deprecation

#1920 [ArticleBundle] Make entities abstract that are extended by default (…
  src/Kunstmaan/ArticleBundle/Entity/AbstractAuthor.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractCategory.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractTag.php
Labels: Priority: Low, Profile: Backend, Target audience: Developers, Type: BC break, Type: Improvement

#1909 [AdminListBundle] avoid translations freakout when the key is true or false without escaping
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.pl.yml
Labels: Priority: Low, Profile: Backend, Type: Bugfix

#1952 [AdminListBundle] Fixed incorrect indentation
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
Labels: Priority: Low, Type: Bugfix

#1947 [TranslatorBundle]: change toolbar data collector to show message instead of key
  src/Kunstmaan/AdminBundle/Resources/views/Toolbar/toolbar_item.html.twig
  src/Kunstmaan/TranslatorBundle/Resources/views/Toolbar/translations.html.twig
  src/Kunstmaan/TranslatorBundle/Toolbar/TranslatorDataCollector.php
Labels: Profile: Backend, Type: Feature

#1950 [GeneratorBundle] Remove unused .babelrc
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/.babelrc
Labels: Profile: Frontend, Target audience: Developers, Type: Improvement

#1954 [AdminBundle] Messages are already translated by symfony
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
Labels: Target audience: Administrators, Type: Bugfix

#1946 [AdminBundle] Update frontend packages
  package.json
  src/Kunstmaan/AdminBundle/bower.json
Labels: Priority: Normal, Profile: Frontend, Target audience: Developers, Type: Bugfix
