Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-09, with the labels that each got.

#2544 [AllBundles] Allow Imagegick pdf read/write to fix travis tests
  .travis.yml
Labels: Target audience: Developers

#2538 [NodeSearchBundle] Fix missing geopoint option for elastic mapping
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
Labels: Profile: Backend, Target audience: Administrators, Target audience: Developers, Type: Bugfix

#2533 [AdminListBundle] Mark export service public to fix sf4 incompatibility in form submission export
  src/Kunstmaan/AdminListBundle/Resources/config/services.yml
Labels: Type: Bugfix

#2532 [FormBundle] Fix sf4 compatibility in the form submission directory
  src/Kunstmaan/FormBundle/DependencyInjection/KunstmaanFormExtension.php
  src/Kunstmaan/FormBundle/Tests/unit/DependencyInjection/KunstmaanFormExtensionTest.php
Labels: Type: Bugfix

#2547 [AdminBundle] fix jQuery deprecated size()
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_app-filter.js
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2527 [GeneratorBundle] Add missing parameter in article adminlist controller
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
Labels: Priority: Normal, Type: Bugfix

#2539 [AdminBundle] rewrite method in aclhelpers to fix deprecation message
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclHelperTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclNativeHelperTest.php
Labels: Type: Bugfix
