Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-02, with the labels that each got.

#2331 [BehatBundle] upgraded dev dependencies
  src/Kunstmaan/BehatBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2330 [NodeSearchBundle] upgraded dev dependencies
  src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/Compiler/NodeSearcherCompilerPassTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/KunstmaanNodeSearchExtensionTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Entity/AbstractSearchPageTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Entity/NodeSearchTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Event/IndexNodeEventTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/EventListener/NodeIndexUpdateEventListenerTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Services/SearchServiceTest.php
  src/Kunstmaan/NodeSearchBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2329 [PagePartBundle] upgraded dev dependencies
  src/Kunstmaan/PagePartBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/DependencyInjection/KunstmaanPagePartExtensionTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/AbstractPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/HeaderPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/LinePagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/LinkPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/PagePartRefTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/PageTemplateConfigurationTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/RawHTMLPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/TextPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/ToTopPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/TocPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/EventListener/CloneListenerTest.php
  src/Kunstmaan/PagePartBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2328 [NodeBundle] upgraded dev dependencies
  src/Kunstmaan/NodeBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/DependencyInjection/KunstmaanNodeExtensionTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/AbstractControllerActionTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/NodeIteratorTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/NodeTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/NodeTranslationTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/NodeVersionLockTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/NodeVersionTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/QueuedNodeTranslationActionTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/StructureNodeTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Event/AdaptFormEventTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Event/ConfigureActionMenuEventTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Event/CopyPageTranslationNodeEventTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Event/NodeEventTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Event/RecopyPageTranslationNodeEventTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Event/RevertNodeActionTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Event/SlugEventTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Event/SlugSecurityEventTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Helper/Menu/ActionsMenuBuilderTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Helper/NodeHelperTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Router/SlugRouterTest.php
  src/Kunstmaan/NodeBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2326 [MultiDomainBundle] upgraded dev dependencies
  src/Kunstmaan/MultiDomainBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/DependencyInjection/KunstmaanMultiDomainExtensionTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/EventListener/HostOverrideListenerTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/AdminPanel/SitesAdminPanelAdaptorTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/DomainConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/HostOverrideCleanupHandlerTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Router/DomainBasedLocaleRouterTest.php
  src/Kunstmaan/MultiDomainBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2314 [GeneratorBundle] upgraded dev requirements
  src/Kunstmaan/GeneratorBundle/Tests/unit/Generator/DefaultSiteGeneratorTest.php
  src/Kunstmaan/GeneratorBundle/Tests/unit/Helper/GeneratorUtilsTest.php
  src/Kunstmaan/GeneratorBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2324 [SearchBundle] upgraded dev dependencies
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Configuration/SearchConfigurationChainTest.php
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/KunstmaanSearchExtensionTest.php
  src/Kunstmaan/SearchBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2323 [SeoBundle] upgraded dev dependencies
  src/Kunstmaan/SeoBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/DependencyInjection/KunstmaanSeoExtensionTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/Entity/RobotsTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/Entity/SeoTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/Twig/TwigExtensionTests.php
  src/Kunstmaan/SeoBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2321 [TaggingBundle] upgraded dev dependencies
  src/Kunstmaan/TaggingBundle/.gitignore
  src/Kunstmaan/TaggingBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagManagerTest.php
  src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagTest.php
  src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TaggableTraitTest.php
  src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TaggingTest.php
  src/Kunstmaan/TaggingBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2320 [UserManagementBundle] upgraded dev dependencies
  src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/KunstmaanUserManagementExtensionTest.php
  src/Kunstmaan/UserManagementBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2319 [UtitiliesBundle] upgraded dev dependencies
  src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/KunstmaanUtilitiesExtensionTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/Cipher/CipherTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/Cipher/UrlSafeCipherTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/ClassLookupTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/Shell/ShellTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/SlugifierTest.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/UrlTransactionNamingStrategyTest.php
  src/Kunstmaan/UtilitiesBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2318 [VotingBundle] upgraded dev dependencies
  src/Kunstmaan/VotingBundle/Tests/unit/DependencyInjection/KunstmaanVotingExtensionTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Entity/AbstractVoteTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/Facebook/FacebookLikeEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/Facebook/FacebookSendEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/LinkedIn/LinkedInShareEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/UpDown/DownVoteEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Event/UpDown/UpVoteEventTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/EventListener/Security/MaxNumberByIpEventListenerTest.php
  src/Kunstmaan/VotingBundle/Tests/unit/Services/RepositoryResolverTest.php
  src/Kunstmaan/VotingBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2317 [MediaPagePartBundle] upgraded dev dependencies
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/DependencyInjection/KunstmaanMediaPagePartExtensionTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/AudioPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/DownloadPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/ImagePagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/SlidePagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/VideoPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2316 [MediaBundle] upgraded dev dependencies
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/KunstmaanMediaExtensionTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Entity/FolderTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Entity/MediaTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/File/FileHelperTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/File/PdfHandlerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/FolderManagerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/MediaManagerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/RemoteAudio/RemoteAudioHelperTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/RemoteSlide/RemoteSlideHelperTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/RemoteVideo/RemoteVideoHandlerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/RemoteVideo/RemoteVideoHelperTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/Transformer/PdfTransformerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Utils/SymfonyVersionTest.php
  src/Kunstmaan/MediaBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2315 [LeadGeneratorBundle] upgraded dev dependencies
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/DependencyInjection/KunstmaanLeadGenerationExtensionTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Popup/AbstractPopupTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/AfterXScrollPercentRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/AfterXSecondsRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/LocaleBlacklistRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/LocaleWhitelistRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/MaxXTimesRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/OnExitIntentRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/RecurringEveryXTimeRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/UrlBlacklistRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/UrlWhitelistRuleTest.php
  src/Kunstmaan/LeadGenerationBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2311 [FormBundle] upgraded dev requirements
  src/Kunstmaan/FormBundle/Tests/unit/AdminList/FormPageAdminListConfiguratorTest.php
  src/Kunstmaan/FormBundle/Tests/unit/AdminList/FormSubmissionAdminListConfiguratorTest.php
  src/Kunstmaan/FormBundle/Tests/unit/AdminList/FormSubmissionExportListConfiguratorTest.php
  src/Kunstmaan/FormBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/FormBundle/Tests/unit/DependencyInjection/KunstmaanFormExtensionTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/AbstractFormPageTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/BooleanFormSubmissionFieldTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/ChoiceFormSubmissionFieldTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/EmailFormSubmissionFieldTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/FileFormSubmissionFieldTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/StringFormSubmissionFieldTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/TextFormSubmissionFieldTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/AbstractFormPagePartTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/CheckboxPagePartTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/ChoicePagePartTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/EmailPagePartTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/FileUploadPagePartTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/MultiLineTextPagePartTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/SingleLineTextPagePartTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/SubmitButtonPagePartTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Event/SubmissionEventTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Helper/FormMailerTest.php
  src/Kunstmaan/FormBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2310 [CacheBundle] updated dev dependencies
  src/Kunstmaan/CacheBundle/.gitignore
  src/Kunstmaan/CacheBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2305 [FixturesBundle] upgraded dev requirements
  src/Kunstmaan/FixturesBundle/.gitignore
  src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/KunstmaanFixturesExtensionTest.php
  src/Kunstmaan/FixturesBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2300 [DashboardBundle] upgraded dev requirements
  src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/KunstmaanDashboardExtensionTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsConfigTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsGoalTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsOverviewTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsSegmentTest.php
  src/Kunstmaan/DashboardBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2299 [ConfigBundle] upgraded dev requirements
  src/Kunstmaan/ConfigBundle/.gitignore
  src/Kunstmaan/ConfigBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/ConfigBundle/Tests/unit/DependencyInjection/KunstmaanConfigExtensionTest.php
  src/Kunstmaan/ConfigBundle/Tests/unit/Entity/AbstractConfigTest.php
  src/Kunstmaan/ConfigBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2298 [ArticleBundle] upgraded dev requirements
  src/Kunstmaan/ArticleBundle/.gitignore
  src/Kunstmaan/ArticleBundle/Tests/unit/AdminList/AbstractArticleAuthorAdminListConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/AdminList/AbstractArticlePageAdminListConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/DependencyInjection/KunstmaanArticleExtensionTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Entity/AbstractArticleOverviewPageTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Entity/AbstractArticlePageTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Entity/AbstractAuthorTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Form/AbstractArticleOverviewPageAdminTypeTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Form/AbstractArticlePageAdminTypeTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Form/AbstractAuthorAdminTypeTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/PagePartAdmin/AbstractArticleOverviewPagePagePartAdminConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/PagePartAdmin/AbstractArticlePagePagePartAdminConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Repository/AbstractArticleOverviewPageRepositoryTest.php
  src/Kunstmaan/ArticleBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2297 [AdminListBundle] upgraded dev requirements
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListFactoryTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/BulkAction/SimpleBulkActionTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractDoctrineDBALAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractDoctrineORMAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/ExportListTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FieldTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterBuilderTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterType/DBAL/AbstractDBALFilterTypeTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterType/ORM/AbstractORMFilterTypeTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Helper/DoctrineDBALAdapterTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/ItemAction/SimpleItemActionTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/ListAction/SimpleListActionTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/DependencyInjection/KunstmaanAdminListExtensionTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/Event/AdminListEventTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/Helper/DomainConfigurationTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/Service/EntityVersionLockServiceTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/Service/ExportServiceTest.php
  src/Kunstmaan/AdminListBundle/composer.json
Labels: Priority: Normal, Profile: Backend

#2274 [TranslationsBundle] upgraded dev requirements
  src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPass.php
  src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
  src/Kunstmaan/TranslatorBundle/Tests/unit/BaseTestCase.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Controller/TranslatorControllerTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/KunstmaanTranslatorExtensionTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Entity/TranslationTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Repository/TranslationRepositoryTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Exporter/ExportCommandHandlerTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Exporter/ExporterTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Importer/ImportCommandHandlerTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Importer/ImporterTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Migrations/MigrationsServiceTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Translator/CacheValidatorTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Translator/LoaderTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/WebTestCase.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/AppKernel.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/TranslatorBundleTest/bundles.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/TranslatorBundleTest/config.yaml
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/bootstrap.php
  src/Kunstmaan/TranslatorBundle/codeception.yml
  src/Kunstmaan/TranslatorBundle/composer.json
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2309 [AdminBundle] Deprecate service class parameters
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
  src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/KunstmaanAdminBundleTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2308 [AdminListBundle] Deprecate service class parameters
  src/Kunstmaan/AdminListBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/AdminListBundle/KunstmaanAdminListBundle.php
  src/Kunstmaan/AdminListBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2306 [ConfigBundle] Deprecate service class parameters
  src/Kunstmaan/ConfigBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/ConfigBundle/KunstmaanConfigBundle.php
  src/Kunstmaan/ConfigBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2303 [FormBundle] Deprecate service class parameters
  src/Kunstmaan/FormBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/FormBundle/KunstmaanFormBundle.php
  src/Kunstmaan/FormBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2307 [CacheBundle] Deprecate service class parameters
  src/Kunstmaan/CacheBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/CacheBundle/KunstmaanCacheBundle.php
  src/Kunstmaan/CacheBundle/Tests/_support/.gitkeep
  src/Kunstmaan/CacheBundle/Tests/_support/Helper/Unit.php
  src/Kunstmaan/CacheBundle/Tests/_support/UnitTester.php
  src/Kunstmaan/CacheBundle/Tests/unit.suite.yml
  src/Kunstmaan/CacheBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
  src/Kunstmaan/CacheBundle/codeception.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2304 [DashboardBundle] Deprecate service class parameters
  src/Kunstmaan/DashboardBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/DashboardBundle/KunstmaanDashboardBundle.php
  src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2302 [LeadGenerationBundle] Deprecate service class parameters
  src/Kunstmaan/LeadGenerationBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/LeadGenerationBundle/KunstmaanLeadGenerationBundle.php
  src/Kunstmaan/LeadGenerationBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2296 [MenuBundle] Deprecate service class parameters
  src/Kunstmaan/MenuBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/MenuBundle/KunstmaanMenuBundle.php
  src/Kunstmaan/MenuBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2301 [MediaBundle] Deprecate service class parameters
  src/Kunstmaan/MediaBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/MediaBundle/KunstmaanMediaBundle.php
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2295 [MultiDomainBundle] Deprecate service class parameters
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/CompilerPass/DeprecateClassParametersPass.php
  src/Kunstmaan/MultiDomainBundle/KunstmaanMultiDomainBundle.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2294 [NodeBundle] Deprecate service class parameters
  src/Kunstmaan/NodeBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/NodeBundle/KunstmaanNodeBundle.php
  src/Kunstmaan/NodeBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2293 [NodeSearchBundle] Deprecate service class parameters
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/NodeSearchBundle/KunstmaanNodeSearchBundle.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2290 [RedirectBundle] Deprecate service class parameters
  src/Kunstmaan/RedirectBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/RedirectBundle/KunstmaanRedirectBundle.php
  src/Kunstmaan/RedirectBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2288 [TranslatorBundle] Deprecate service class parameters
  src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/TranslatorBundle/KunstmaanTranslatorBundle.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2289 [SearchBundle] Deprecate service class parameters
  src/Kunstmaan/SearchBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/SearchBundle/KunstmaanSearchBundle.php
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2291 [PagePartBundle] Deprecate service class parameters
  src/Kunstmaan/PagePartBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/PagePartBundle/KunstmaanPagePartBundle.php
  src/Kunstmaan/PagePartBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2287 [UserManagementBundle] Deprecate service class parameters
  src/Kunstmaan/UserManagementBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/UserManagementBundle/KunstmaanUserManagementBundle.php
  src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2286 [UtilitiesBundle] Deprecate service class parameters
  src/Kunstmaan/UtilitiesBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/UtilitiesBundle/KunstmaanUtilitiesBundle.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2292 [AdminListBundle] refactored/simplified AdminListTest
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/Model/ConcreteConfigurator.php
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2284 [MediaBundle] Move aviary_api_key parameter to media bundle config instead of parameter
  UPGRADE-5.2.md
  src/Kunstmaan/MediaBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/KunstmaanMediaExtensionTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2276 [SearchBundle] Move search parameters to search_bundle config instead of parameters
  UPGRADE-5.2.md
  src/Kunstmaan/SearchBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/SearchBundle/DependencyInjection/KunstmaanSearchExtension.php
  src/Kunstmaan/SearchBundle/Resources/config/services.yml
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Configuration/ConfigurationTest.php
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/KunstmaanSearchExtensionTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2273 [AdminBundle] Move admin locale parameters to admin_bundle config instead of parameters
  UPGRADE-5.2.md
  src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/KunstmaanAdminExtensionTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/DomainConfigurationTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/Helper/DomainConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Resources/config/services.yml
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/DomainConfigurationTest.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/KunstmaanTranslatorExtensionTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2281 [SearchBundle] Move searchindexprefix parameter to search bundle
  UPGRADE-5.2.md
  src/Kunstmaan/SearchBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/SearchBundle/DependencyInjection/KunstmaanSearchExtension.php
  src/Kunstmaan/SearchBundle/Resources/config/services.yml
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Configuration/ConfigurationTest.php
  src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/KunstmaanSearchExtensionTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2264 [TranslatorBundle] Speed up bulk import of large translation files
  src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
  src/Kunstmaan/TranslatorBundle/Service/TranslationGroupManager.php
Labels: Type: Bugfix, Type: Feature

#2280 [DashboardBundle] Move google api parameters to dashboard bundle config instead of parameters
  UPGRADE-5.2.md
  src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
  src/Kunstmaan/DashboardBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
  src/Kunstmaan/DashboardBundle/Resources/config/services.yml
  src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/KunstmaanDashboardExtensionTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2333 [AllBundles] Test latest symfony version and supported lts
  .travis.yml
  src/Kunstmaan/AdminBundle/Tests/unit/EventListener/ConsoleExceptionListenerTest.php
  src/Kunstmaan/GeneratorBundle/Tests/unit/Generator/DefaultSiteGeneratorTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2336 [SearchBundle] Make search analysis service public for kuma:search:setup command
  src/Kunstmaan/SearchBundle/Resources/config/services.yml
Labels: Priority: Normal, Target audience: Developers, sf4-compatibility

#2340 [SearchBundle] Don't require value if we provide a default value
  src/Kunstmaan/SearchBundle/DependencyInjection/Configuration.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2342 [MenuBundle] Mark menu service as public
  src/Kunstmaan/MenuBundle/Resources/config/services.yml
Labels: Priority: High, Profile: Backend, Target audience: Developers, sf4-compatibility

#2335 [MediaPagePartBundle] Fixed last remaining extend of old phpunit testcase class
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2339 [AdminBundle] Use new admin bundle parameters instead of the old deprecated
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2338 [AdminListBundle] added getViewUrl to adminlist config. interface
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AdminListConfiguratorInterface.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListTest.php
Labels: Priority: Normal, Profile: Backend, Type: Bugfix

#2313 [SeoBundle] Added option to provide caching for og image dimension calls
  src/Kunstmaan/SeoBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/SeoBundle/DependencyInjection/KunstmaanSeoExtension.php
  src/Kunstmaan/SeoBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/DependencyInjection/KunstmaanSeoExtensionTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/Twig/TwigExtensionTest.php
  src/Kunstmaan/SeoBundle/Tests/unit/files/150.png
  src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
Labels: Priority: Normal, Profile: Backend, Type: Feature

#2279 [NodeSearchBundle] Deprecate container access in NodeIndexUpdateEventListener
  UPGRADE-5.2.md
  src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
  src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
  src/Kunstmaan/NodeSearchBundle/Resources/config/update_listener.yml
  src/Kunstmaan/NodeSearchBundle/Tests/unit/EventListener/NodeIndexUpdateEventListenerTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2341 [TranslatorBundle] Deprecated the MigrationsDiffCommand & DiffCommand
  UPGRADE-5.2.md
  src/Kunstmaan/TranslatorBundle/Command/MigrationsDiffCommand.php
  src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
  src/Kunstmaan/TranslatorBundle/Service/Command/DiffCommand.php
Labels: Priority: Normal, Profile: Backend, Type: Deprecation

#2334 [ArticleBundle] Fixed missing sprintf with classname in deprecation message
  src/Kunstmaan/ArticleBundle/Entity/AbstractAuthor.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractCategory.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractTag.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Entity/AbstractAuthorTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2337 [AllBundles] Fix sf4 rootNode deprecation
  src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/AdminListBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/ArticleBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/ConfigBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/DashboardBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/FixturesBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/FormBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/LeadGenerationBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/MediaBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/MediaPagePartBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/MenuBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/PagePartBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/RedirectBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/SearchBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/SeoBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/SitemapBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/TaggingBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/UserManagementBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/UtilitiesBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/VotingBundle/DependencyInjection/Configuration.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2283 [AdminBundle] Revert PR #2049 changes
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
Labels: Priority: Normal, Profile: Frontend, Type: Bugfix

#2352 [AdminBundle] fix error state for select2 & wysiwyg fields
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js.map
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js.map
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-group.scss
Labels: Priority: Low, Profile: Frontend, Target audience: Administrators, Type: Bugfix, Type: Improvement

#2353 [CacheBundle] Fixed incorrect composer autoload namespace
  src/Kunstmaan/CacheBundle/composer.json
Labels: Priority: High, Target audience: Developers, Type: Bugfix

#2356 [AllBundles] Added missing items in upgrade doc for 5.2
  UPGRADE-5.2.md
Labels: Priority: Normal, Target audience: Developers, Type: Documentation

#2354 [AdminBundle][MediaBundle] Configure bundle dependencies by default
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2344 [AdminListBundle] refactored the AbstractAdminListConfiguratorTest
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/Model/ConcreteConfigurator.php
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2345 [AdminListBundle] refactored the AbstractDoctrineORMAdminListConfigur…
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractDoctrineORMAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/composer.json
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2346 [AdminListBundle] refactored the AbstractDoctrineDBALAdminListConfigu…
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineDBALAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractDoctrineDBALAdminListConfiguratorTest.php
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2348 [AdminBundle] refactored the CloneListenerTest
  src/Kunstmaan/AdminBundle/Tests/unit/EventListener/CloneListenerTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Validator/Constraints/PasswordRestrictionsValidatorTest.php
  src/Kunstmaan/AdminBundle/composer.json
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2351 [AdminBundle] refactored the VersionCheckTest
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/VersionCheck/VersionCheckTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/VersionCheck/testdata/composer_broken.lock
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/VersionCheck/testdata/composer_bundleless.lock
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/VersionCheck/testdata/composer_ok.lock
  src/Kunstmaan/AdminBundle/composer.json
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2360 [AdminBundle] added ModulesMenuAdaptorTest
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/ModulesMenuAdaptorTest.php
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2365 [MediaBundle][SearchBundle] Provide default config for bundles to work on sf4
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/SearchBundle/Resources/config/services.yml
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2363 [GeneratorBundle] Fixed not supported template naming for SF34
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/PageAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/OverviewPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/pagetemplate.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/Page/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/BikesListPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/PageBannerPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/ServicePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/UspPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/ContentPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/FormPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/HomePage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/SearchPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pagetemplates/contentpage-with-submenu.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Error/error.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/ContentPage/pagetemplate.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/ContentPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/FormPage/pagetemplate.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/FormPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/HomePage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/SearchPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/KunstmaanSitemapBundle/views/SitemapPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/TwigBundle/views/Exception/error.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/TwigBundle/views/Exception/error404.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/TwigBundle/views/Exception/error500.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/TwigBundle/views/Exception/error503.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/AbstractFormPagePart/AbstractFormPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/AudioPagePart/AudioPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ButtonPagePart/ButtonPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/CheckboxPagePart/CheckboxPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ChoicePagePart/ChoicePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/DownloadPagePart/DownloadPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/EmailPagePart/EmailPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ExtraFunctions.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/FileUploadPagePart/FileUploadPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/HeaderPagePart/HeaderPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ImagePagePart/ImagePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/IntroTextPagePart/IntroTextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/LinePagePart/LinePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/LinkPagePart/LinkPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/MultiLineTextPagePart/MultiLineTextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/RawHtmlPagePart/RawHtmlPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/SingleLineTextPagePart/SingleLineTextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/SubmitButtonPagePart/SubmitButtonPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/TextPagePart/TextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ToTopPagePart/ToTopPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/TocPagePart/TocPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/VideoPagePart/VideoPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Entity/Pages/SearchPage.php
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Bugfix

#2358 [PagePartBundle] Make sure column names are independent of the doctrine naming strategy
  src/Kunstmaan/PagePartBundle/Entity/PagePartRef.php
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2361 [AdminBundle] added SimpleMenuAdaptorTest
  src/Kunstmaan/AdminBundle/Helper/Menu/SimpleMenuAdaptor.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/SimpleMenuAdaptorTest.php
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2359 [GeneratorBundle] Use new multi language parameter as the check is broken on empty install
  src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php
  src/Kunstmaan/GeneratorBundle/Tests/unit/Generator/DefaultSiteGeneratorTest.php
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2349 [AdminBundle] refactored the MenuBuilderTest
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/MenuBuilderTest.php
  src/Kunstmaan/AdminBundle/composer.json
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2364 [AdminBundle] added SettingsMenuAdaptorTest
  src/Kunstmaan/AdminBundle/Helper/Menu/SettingsMenuAdaptor.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/SettingsMenuAdaptorTest.php
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2347 [AdminListBundle] Refactored exportlist test
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/ExportListTest.php
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2367 [TranslatorBundle] fixed sf4 translations issue
  src/Kunstmaan/TranslatorBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
  src/Kunstmaan/TranslatorBundle/README.md
  src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/KunstmaanTranslatorExtensionTest.php
Labels: Priority: High, Profile: Backend, sf4-compatibility

#2366 [GeneratorBundle] fixed adminlist generator messages
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
Labels: Priority: Normal, Profile: Backend, Type: Improvement

#2369 [NodeBundle] Fix incorrect routing config for controller-as-service
  src/Kunstmaan/NodeBundle/Resources/config/routing.yml
Labels: Priority: High, Type: Bugfix, sf4-compatibility

#2355 [AdminListBundle] Fix getStringValue to allow displaying \DateTimeImmutable objects
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Feature

#2385 [GeneratorBundle] fixed multilanguage parameter in article generator
  src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
Labels: Priority: High, Profile: Backend, Type: Bugfix

#2382 [GeneratorBundle] Fixed Page(part) generating
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php
Labels: Type: Bugfix

#2387 [NodeBundle] fixed multilanguage parameter in WidgetController
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
Labels: Priority: High, Profile: Backend, Type: Bugfix

#2389 [AdminBundle] alignment of date, time & datetime widgets
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/_components.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_date-time-group.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_widget.scss
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
Labels: Target audience: Administrators, Type: Bugfix, Type: Improvement
