Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-05, with the labels that each got.

#2434 [AdminListBundle] [TranslatorBundle] Option to filter on empty fields in StringFilterType.
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_app-filter.js
  src/Kunstmaan/AdminListBundle/AdminList/FilterType/DBAL/StringFilterType.php
  src/Kunstmaan/AdminListBundle/AdminList/FilterType/ORM/StringFilterType.php
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/AdminListBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/AdminListBundle/Resources/views/FilterType/stringFilter.html.twig
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
Labels: Profile: Backend, Target audience: Administrators, Type: Feature

#2436 [FormBundle][GeneratorBundle] Fix constraints on form pageparts
  src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
  src/Kunstmaan/FormBundle/Form/BooleanFormSubmissionType.php
  src/Kunstmaan/FormBundle/Form/ChoiceFormSubmissionType.php
  src/Kunstmaan/FormBundle/Form/EmailFormSubmissionType.php
  src/Kunstmaan/FormBundle/Form/FileFormSubmissionType.php
  src/Kunstmaan/FormBundle/Form/StringFormSubmissionType.php
  src/Kunstmaan/FormBundle/Form/TextFormSubmissionType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/CheckboxPagePart/CheckboxPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ChoicePagePart/ChoicePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/EmailPagePart/EmailPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/FileUploadPagePart/FileUploadPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/MultiLineTextPagePart/MultiLineTextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/SingleLineTextPagePart/SingleLineTextPagePart.php
Labels: Priority: High, Profile: Backend, Target audience: Administrators, Type: Bugfix

#2446 [AdminBundle] fix JS error in datepicker
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_datepicker.js
Labels: Type: Bugfix

#2438 [AllBundles] Re-add file to make the 5.0 doc build pass again
  docs/contributing/groundcontrol.md
Labels: Type: Bugfix, Type: Documentation

#2439 [AllBundles] Backport page rename fix in docs config file
  mkdocs.yml
Labels: Type: Bugfix, Type: Documentation

#2451 [AllBundles] Fix sensiolabs insight config to make the run start again
  .sensiolabs.yml
Labels: Priority: Normal, Target audience: Developers

#2441 [FormBundle] Missing symfony/css-selector dependency
  src/Kunstmaan/FormBundle/composer.json
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2442 [AllBundles] Clean up replace section and add missing packages
  composer.json
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2450 [AllBundle] Code style fixes
  src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsFromFileCommand.php
  src/Kunstmaan/TranslatorBundle/Model/Translation/TranslationGroup.php
  src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
Labels: Target audience: Developers, Type: Bugfix, Type: Improvement

#2454 [RedirectBundle] Re-add utf8 route fix
  src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
Labels: Priority: Normal, Type: Bugfix

#2456 [GeneratorBundle] Fix default generator twig override paths
  src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php
  src/Kunstmaan/GeneratorBundle/Tests/unit/Generator/DefaultSiteGeneratorTest.php
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2457 [GeneratorBundle] Fix error in media pp twig view for new pp's
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ImagePagePart/view.html.twig
Labels: Priority: High, Type: Bugfix

#2458 [NodeSearchBundle] Correctly index page with utf8 characters
  src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
Labels: Priority: Normal, Type: Bugfix

#2459 [AllBundles] Install imagick extension/ghostscript to skip less unit tests
  .travis.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Improvement

#2460 [DashboardBundle] Update incorrect documentation url
  src/Kunstmaan/DashboardBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/DashboardBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/DashboardBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/DashboardBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/DashboardBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/DashboardBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/DashboardBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/DashboardBundle/Resources/translations/messages.pl.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix

#2455 [AllBundles] Remove php 7.3 check as php-cs-fixer supports it now
  .travis.yml
Labels: Priority: Normal, Type: Bugfix, Type: Improvement

#2443 [NodeBundle] Added missing translation keys
  src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
Labels: Priority: Normal, Type: Bugfix, Type: Translations

#2445 [NodeBundle][NodeSearchBundle] Fix code style issues
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
  src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
Labels: Type: Bugfix
