Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-11, with the labels that each got.

#2535 [AllBundles] Enable testing against php 7.4
  .travis.yml
Labels: Target audience: Developers

#2586 [MediaBundle] Fixed imagine ignoring EXIF orientation data
  src/Kunstmaan/MediaBundle/Resources/config/imagine_filters.yml
Labels: Type: Bugfix

#2590 [NodeBundle] Fix url chooser to allow # and #! urls
  src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserFormSubscriber.php
  src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserLinkTypeSubscriber.php
  src/Kunstmaan/NodeBundle/Tests/unit/Validator/Constraint/ValidExternalUrlValidatorTest.php
  src/Kunstmaan/NodeBundle/Validator/Constraint/ValidExternalUrl.php
  src/Kunstmaan/NodeBundle/Validator/Constraint/ValidExternalUrlValidator.php
Labels: Type: Bugfix

#2579 [AdminBundle] Fix bootstrap-colorpicker
  package-lock.json
  package.json
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2575 [AdminListBundle] Added missing limit dropdown caret
  src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/limit.html.twig
Labels: Type: Bugfix

#2577 [TranslatorBundle] implement changeablelimitinterface on translationadminlist
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
Labels: Type: Feature

#2554 [AdminBundle] Switch fos_user mailer to twig mailer
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
Labels: Target audience: Developers, Type: Improvement

#2593 [AllBundles] Fix symfony 4.4 test failures
  src/Kunstmaan/SeoBundle/Tests/unit/DependencyInjection/KunstmaanSeoExtensionTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPassTest.php
Labels: Type: Bugfix

#2449 [AllBundles] Replace deprecated twig namespaces by the new namespace format
  src/Kunstmaan/AdminBundle/EventListener/ToolbarListener.php
  src/Kunstmaan/AdminBundle/Twig/AdminPermissionsTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/AdminRouteHelperTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/DateByLocaleExtension.php
  src/Kunstmaan/AdminBundle/Twig/FormToolsExtension.php
  src/Kunstmaan/AdminBundle/Twig/GoogleSignInTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/LocaleSwitcherTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/MenuTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/SidebarTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/TabsTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/ToolbarTwigExtension.php
  src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
  src/Kunstmaan/ArticleBundle/Twig/ArticleTwigExtension.php
  src/Kunstmaan/ConfigBundle/Twig/ConfigTwigExtension.php
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Twig/BikesTwigExtension.php
  src/Kunstmaan/LeadGenerationBundle/Twig/PopupTwigExtension.php
  src/Kunstmaan/MenuBundle/Service/RenderService.php
  src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php
  src/Kunstmaan/MultiDomainBundle/Twig/MultiDomainTwigExtension.php
  src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
  src/Kunstmaan/NodeBundle/Twig/PagesConfigurationTwigExtension.php
  src/Kunstmaan/NodeBundle/Twig/UrlReplaceTwigExtension.php
  src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
  src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartAdminTwigExtension.php
  src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
  src/Kunstmaan/PagePartBundle/Twig/Extension/PageTemplateTwigExtension.php
  src/Kunstmaan/SeoBundle/Twig/GoogleAnalyticsTwigExtension.php
  src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
  src/Kunstmaan/SitemapBundle/Twig/SitemapTwigExtension.php
  src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Improvement

#2447 [GeneratorBundle] Improved the generated article classes
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/AuthorAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/CategoryAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/PageAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/TagAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/ArticleController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/CategoryAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/TagAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Author.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Category.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/OverviewPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Tag.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/AuthorAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/OverviewPageAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminTypePartial.php.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Helper/Menu/MenuAdaptor.php
Labels: Priority: Normal, Target audience: Developers, Type: Improvement

#2556 [AdminListBundle] Deprecate setter injection and usage of symfony templating
  UPGRADE-5.4.md
  src/Kunstmaan/AdminListBundle/Resources/config/services.yml
  src/Kunstmaan/AdminListBundle/Service/ExportService.php
  src/Kunstmaan/AdminListBundle/Tests/unit/Service/ExportServiceTest.php
Labels: Target audience: Developers, Type: Deprecation, Type: Improvement

#2545 [AllBundles ] Fix self deprecations triggered in tests
  src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/KunstmaanAdminExtensionTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/EventListener/ConsoleExceptionSubscriberTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/DomainConfigurationTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/Helper/DomainConfigurationTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Entity/AbstractAuthorTest.php
  src/Kunstmaan/FormBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/DomainConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/unit/Router/DomainBasedLocaleRouterTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Router/SlugRouterTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/config/config.yml
Labels: Target audience: Developers, Type: Improvement
