Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-03, with the labels that each got.

#2386 [TranslatorBundle] Fixed --globals flag for kuma:translator:import command
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
Labels: Type: Bugfix

#2376 [AdminBundle] fix multiple 'new' url-choosers
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js.map
  src/Kunstmaan/AdminBundle/Resources/ui/js/_url-chooser.js
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2383 [AllBundles] Fix correct symfony/security packages
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
Labels: Type: Bugfix

#2397 [TranslatorBundle] Fix translations import on sf4 applications
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
  src/Kunstmaan/TranslatorBundle/Service/TranslationFileExplorer.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/translations/messages.en.yml
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/translations/messages.nl.yml
  src/Kunstmaan/TranslatorBundle/Tests/unit/app/translations/newdomain.de.yml
Labels: Priority: High, Target audience: Developers, Type: Bugfix, sf4-compatibility

#2398 [AdminBundle] Added missing monolog dependency
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
Labels: Target audience: Developers, Type: Bugfix, sf4-compatibility

#2399 [GeneratorBundle] Fix typo in table name of article generator
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Category.php
Labels: Priority: Normal, Type: Bugfix

#2384 [FormBundle] Replace Gemdo urlizer class with behat transliterator
  src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/FileFormSubmissionField.php
  src/Kunstmaan/FormBundle/composer.json
Labels: Priority: Normal, Target audience: Developers, Type: Improvement

#2402 [GeneratorBundle] Fix old optional parameter usages
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/DataFixtures/ORM/SearchPageGenerator/SearchFixtures.php
Labels: Priority: Normal, Type: Bugfix, sf4-compatibility

#2403 [ConfigBundle] Fixed and replaced not working validation in ConfigCompilerPass
  src/Kunstmaan/ConfigBundle/DependencyInjection/Compiler/KunstmaanConfigConfigurationPass.php
  src/Kunstmaan/ConfigBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/ConfigBundle/KunstmaanConfigBundle.php
  src/Kunstmaan/ConfigBundle/Tests/unit/DependencyInjection/Compiler/KunstmaanConfigConfigurationPassCompilerPassTest.php
  src/Kunstmaan/ConfigBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix, Type: Deprecation

#2406 [GeneratorBundle] fix image-pp & add srcset polyfill for IE11
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/js/app.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ImagePagePart/view.html.twig
Labels: Profile: Frontend, Target audience: Developers, Target audience: Visitors, Type: Bugfix

#2404 [AdminBundle] Better position/styling for characters left indicator
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-control.scss
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
Labels: Priority: Low, Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2391 [FormBundle] Moved FormMailer dependency to separate listener
  src/Kunstmaan/FormBundle/Event/SubmissionEvent.php
  src/Kunstmaan/FormBundle/EventListener/SendEmailListener.php
  src/Kunstmaan/FormBundle/Helper/FormHandler.php
  src/Kunstmaan/FormBundle/Resources/config/services.yml
Labels: Profile: Backend, Target audience: Developers, Type: Improvement

#2388 [MediaBundle] Add image width and height to media module as done in PP media chooser
  src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
Labels: Type: Feature

#2407 [AllBundles] Fix risky tests
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclHelperTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclNativeHelperTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterType/DBAL/AbstractDBALFilterTypeTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterType/ORM/AbstractORMFilterTypeTest.php
  src/Kunstmaan/FormBundle/Tests/unit/AdminList/FormPageAdminListConfiguratorTest.php
  src/Kunstmaan/FormBundle/Tests/unit/AdminList/FormSubmissionAdminListConfiguratorTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/AbstractFormPagePartTest.php
  src/Kunstmaan/GeneratorBundle/Tests/unit/Generator/DefaultSiteGeneratorTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/File/PdfHandlerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/MediaManagerTest.php
  src/Kunstmaan/MenuBundle/Tests/unit/Entity/MenuItemTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/StructureNodeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/HeaderPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/LinePagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/LinkPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/RawHTMLPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/TextPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/ToTopPagePartAdminTypeTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Form/TocPagePartAdminTypeTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Importer/ImportCommandHandlerTest.php
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2408 [AdminBundle] Log console errors as critical instead of error
  src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionListener.php
  src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionSubscriber.php
  src/Kunstmaan/AdminBundle/Tests/unit/EventListener/ConsoleExceptionSubscriberTest.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#1836 [GeneratorBundle] Kuma install command
  docs/installation/index.md
  src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
  src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
Labels: Priority: Low, Profile: Backend, Target audience: Developers

#2395 [NodeSearchBundle] fix #2380 childs of structurenodes never get indexed and tests
  src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
  src/Kunstmaan/NodeSearchBundle/Resources/config/update_listener.yml
  src/Kunstmaan/NodeSearchBundle/Tests/unit/EventListener/NodeIndexUpdateEventListenerTest.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2409 [TranslatorBundle] Export fails to print non standard characters correctly.
  src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/CSVFileExporter.php
Labels: Profile: Backend, Target audience: Administrators, Type: Bugfix

#2411 [NodeBundle] Start page reorder weight at 1 instead of 0
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
Labels: Priority: High, Target audience: Developers, Type: Bugfix

#2410 [DashboardBundle] Mark google analytics helper service as public
  src/Kunstmaan/DashboardBundle/Resources/config/services.yml
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix, sf4-compatibility

#2412 [AllBundles] Added link script for development
  link
Labels: Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2413 [NodeBundle] Fix for missing validation of url/email link chooser
  src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserFormSubscriber.php
  src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserLinkTypeSubscriber.php
  src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2415 [NodeBundle] Import commands.yml to register command in sf4
  src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix
