Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-04, with the labels that each got.

#2414 [GeneratorBundle] Added config generator + improved install command
  src/Kunstmaan/GeneratorBundle/Command/GenerateConfigCommand.php
  src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/ConfigGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/config/fos_http_cache.yaml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/config/liip_imagine.yaml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/config/security.yaml
  src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
Labels: Profile: Backend, Target audience: Developers, Type: Feature, Type: Improvement, sf4-compatibility

#2417 [GeneratorBundle] Fix null check
  src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix, Type: Feature, sf4-compatibility

#2420 [NodeBundle] Remove old/incorrect doc about lock command
  docs/bundles/node-bundle/locking.md
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix, Type: Documentation

#2421 [AllBundles] Replace deprecated getRootDir calls
  src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateLayoutCommand.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
  src/Kunstmaan/MediaBundle/Helper/IconFont/AbstractIconFontLoader.php
  src/Kunstmaan/TranslatorBundle/Service/Command/AbstractCommandHandler.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
Labels: Priority: Normal, Target audience: Developers, Type: Improvement

#2422 [FormBundle] In newer versions of symfony the @templating service is replaced by the delegatingengine by default
  src/Kunstmaan/FormBundle/Helper/FormMailer.php
  src/Kunstmaan/FormBundle/Tests/unit/Helper/FormMailerTest.php
Labels: Type: Bugfix

#2423 [AdminBundle] fix typo in filename of wordcount
  src/Kunstmaan/AdminBundle/Resources/views/Default/_css.html.twig
Labels: Profile: Frontend, Target audience: Developers, Type: Bugfix, Type: Feature

#2418 [Documentation] KunstmaanCMS Installer documentation
  docs/images/article-generator.png
  docs/images/buildui.png
  docs/images/composer-skeleton.png
  docs/images/config-generator.png
  docs/images/database-setup.png
  docs/images/demosite.png
  docs/images/flex-configure.png
  docs/images/install_finished.png
  docs/images/installer-start.png
  docs/images/kunstmaancms.png
  docs/images/site-generator.png
  docs/installation/index.md
  docs/installation/standard-edition.md
  mkdocs.yml
Labels: Profile: Backend, Target audience: Developers, Type: Documentation, Type: Feature, sf4-compatibility

#2424 [AdminBundle] update Bootstrap v3.3 -> v3.4
  package-lock.json
  package.json
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js.map
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js.map
Labels: Profile: Frontend, Target audience: Developers, Type: Bugfix

#2375 [AdminBundle] dynamic breakpoint for top navbar in admin area
  package-lock.json
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_app-top-nav.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/app.js
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/vendors/bootstrap-components/_navbar.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/config/vendors/bootstrap/_bootstrap-vars.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__header.scss
  src/Kunstmaan/AdminBundle/Resources/views/Default/app_header.html.twig
Labels: Profile: Frontend, State: Waiting for feedback, Target audience: Administrators, Type: Bugfix, Type: Improvement

#2425 [AdminBundle] Fix FOSUserBundle config prepend
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2429 [NodeBundle] Allow entity as creator
  src/Kunstmaan/NodeBundle/Helper/Services/PageCreatorService.php
Labels: Profile: Backend, Target audience: Developers, Type: Feature

#2427 [GeneratorBundle] Added fos user config to generator
  docs/images/config-generator.png
  docs/installation/index.md
  src/Kunstmaan/GeneratorBundle/Command/GenerateConfigCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/ConfigGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/config/fos_user.yaml
Labels: Profile: Backend, Target audience: Developers, Type: Feature, Type: Improvement, sf4-compatibility

#2430 [NodeBundle] Register services that enable the node bundle entity tabs
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2432 [GeneratorBundle] fix admin test generator
  src/Kunstmaan/GeneratorBundle/Generator/AdminTestsGenerator.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2431 [AdminBundle] fix timepicker of publish & unpublish modals
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_datepicker.js
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_publish.html.twig
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_unpublish.html.twig
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix
