Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-10, with the labels that each got.

#2529 [NodeBundle] Feature/current url menu tab
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_slug-chooser.js
  src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
Labels: State: Waiting for feedback, Type: Feature

#2565 [MediaBundle] Fixed compatibility with new LiipImagine generateUrl() function
  src/Kunstmaan/MediaBundle/Helper/Imagine/CacheManager.php
Labels: Type: Bugfix

#2568 [TranslatorBundle] Fix import translations on symfony 3.4 installations
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
Labels: Type: Bugfix

#2570 [MediaBundle] Remove unnecessary raw filter on translations
  src/Kunstmaan/MediaBundle/Resources/views/Folder/delete-modal.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Folder/empty-modal.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Media/bulkUpload.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Media/create.html.twig
Labels: Type: Bugfix

#2571 [UserManagementBundle] The delete route should only allow post requests
  src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
  src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
Labels: Type: Bugfix, Type: Improvement

#2528 [GeneratorBundle] Remove incorrect docblock text
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/Pages/HomePageAdminType.php
Labels: Type: Improvement

#2559 [AllBundles] Deprecate remaining usages of symfony/templating
  UPGRADE-5.4.md
  src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
  src/Kunstmaan/ConfigBundle/Resources/config/services.yml
  src/Kunstmaan/FormBundle/Helper/FormMailer.php
  src/Kunstmaan/FormBundle/Resources/config/services.yml
  src/Kunstmaan/FormBundle/Tests/unit/Helper/FormMailerTest.php
Labels: Type: Deprecation, Type: Improvement

#2526 [AllBundles] Cleanup old @noinspection docblocks
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineDBALAdminListConfigurator.php
  src/Kunstmaan/NodeBundle/Controller/SlugController.php
  src/Kunstmaan/NodeBundle/Helper/PagesConfiguration.php
Labels: Type: Improvement

#2557 [AdminBundle] Forward compatible fix for the deprecated roles methods
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclHelperTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclNativeHelperTest.php
Labels: Target audience: Developers, Type: Improvement

#2546 [NodeSearchBundle] Trigger deprecation after container get
  src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
Labels: Target audience: Developers, Type: Improvement

#2465 [UtilitiesBundle] Code improvement found by static code analysis
  src/Kunstmaan/UtilitiesBundle/Helper/Cipher/UrlSafeCipher.php
  src/Kunstmaan/UtilitiesBundle/Helper/ClassLookup.php
  src/Kunstmaan/UtilitiesBundle/Helper/Shell/Shell.php
  src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
  src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
Labels: Priority: Normal, Target audience: Developers, Type: Improvement

#2472 [TranslatorBundle] Code improvement found by static code analysis
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
  src/Kunstmaan/TranslatorBundle/Command/TranslationCacheCommand.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPass.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
  src/Kunstmaan/TranslatorBundle/Entity/Translation.php
  src/Kunstmaan/TranslatorBundle/Model/Translation.php
  src/Kunstmaan/TranslatorBundle/Model/Translation/TranslationGroup.php
  src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
  src/Kunstmaan/TranslatorBundle/Service/Command/AbstractCommandHandler.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/CSVFileExporter.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/YamlFileExporter.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
  src/Kunstmaan/TranslatorBundle/Service/Menu/TranslatorMenuAdaptor.php
  src/Kunstmaan/TranslatorBundle/Service/Migrations/MigrationsService.php
  src/Kunstmaan/TranslatorBundle/Service/Translator/CacheValidator.php
  src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Repository/TranslationRepositoryTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Migrations/MigrationsServiceTest.php
Labels: Priority: Normal, Target audience: Developers, Type: Improvement
