Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-12, with the labels that each got.

#2594 [NodeBundle] Fix incompatibility with framework-extra-bundle 5.5.*
  src/Kunstmaan/NodeBundle/Controller/SlugController.php
  src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
Labels: Type: Bugfix

#2597 [NodeBundle] added translations for URL-chooser and Choose
  src/Kunstmaan/NodeBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.pl.yml
  src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
Labels: Type: Bugfix

#2599 [AllBundles] PHP 7.4 compatibility fixes
  .travis.yml
  src/Kunstmaan/AdminBundle/Tests/unit/EventListener/MappingListenerTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterBuilderTest.php
  src/Kunstmaan/MultiDomainBundle/Router/DomainBasedLocaleRouter.php
  src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagManagerTest.php
Labels: Type: Bugfix, Type: Improvement

#2604 [AllBundles] Use symfony/flex in travis build suite and improve test version ranges
  .travis.yml
  composer.json
  src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement
