Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-01, with the labels that each got.

#2207 [AdminBundle] Improve twig template deprecations
  composer.json
  src/Kunstmaan/AdminBundle/Resources/views/ChangePassword/changePassword.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/ChangePassword/changePassword_content.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/Resetting/checkEmail.html.twig
Labels: Priority: Normal, Target audience: Developers, Type: Improvement

#2218 [GeneratorBundle] Prepare generators for sf4 support
  src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
  src/Kunstmaan/GeneratorBundle/Helper/Sf4AppBundle.php
  src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/PagePartBundle/Resources/config/services.yml
  src/Kunstmaan/UtilitiesBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2217 [GeneratorBundle] Typehint againt interface instead of concrete class
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Twig/BikesTwigExtension.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2220 [GeneratorBundle] Symfony 4 support for default site generator
  src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/BikeAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/BikesListPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/PageBannerPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/ServicePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/UspPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/BehatTestPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/ContentPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/FormPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/HomePage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/SearchPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pageparts/form.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pageparts/header.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pageparts/main.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pageparts/section1.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pageparts/section2.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pageparts/section3.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pageparts/section4.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pageparts/section5.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pagetemplates/behat-test-page.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pagetemplates/contentpage-with-submenu.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pagetemplates/contentpage.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pagetemplates/formpage.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pagetemplates/homepage.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/pagetemplates/searchpage.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Error/error.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/ContentPage/pagetemplate.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/ContentPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/FormPage/pagetemplate.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/FormPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/HomePage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/SearchPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/KunstmaanSitemapBundle/views/SitemapPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/TwigBundle/views/Exception/error.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/TwigBundle/views/Exception/error404.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/TwigBundle/views/Exception/error500.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/TwigBundle/views/Exception/error503.html.twig
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2221 [GeneratorBundle] Symfony 4 support for default pagepart generator
  src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/DefaultPagePartGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/AbstractFormPagePart/AbstractFormPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/AudioPagePart/AudioPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ButtonPagePart/ButtonPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/CheckboxPagePart/CheckboxPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ChoicePagePart/ChoicePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/DownloadPagePart/DownloadPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/EmailPagePart/EmailPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ExtraFunctions.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/FileUploadPagePart/FileUploadPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/HeaderPagePart/HeaderPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ImagePagePart/ImagePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/IntroTextPagePart/IntroTextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/LinePagePart/LinePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/LinkPagePart/LinkPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/MultiLineTextPagePart/MultiLineTextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/RawHtmlPagePart/RawHtmlPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/SingleLineTextPagePart/SingleLineTextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/SubmitButtonPagePart/SubmitButtonPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/TextPagePart/TextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ToTopPagePart/ToTopPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/TocPagePart/TocPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/VideoPagePart/VideoPagePart.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2222 [GeneratorBundle] Symfony 4 support for the article generator
  src/Kunstmaan/GeneratorBundle/Generator/ArticleGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/PageAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/CategoryAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/TagAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/OverviewPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Helper/Menu/MenuAdaptor.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/pageparts/main.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/pagetemplates/overviewpage.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/pagetemplates/page.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/pagetemplate.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/Page/view.html.twig
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2223 [GeneratorBundle] Sf4 support for generate layout
  src/Kunstmaan/GeneratorBundle/Command/GenerateLayoutCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/LayoutGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Default/index.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_header.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Page/layout.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.admin-extra.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.app.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.styleguide.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/configured-tasks.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/gulpfile.babel.js
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2212 [TranslatorBundle] importer requires wrong locales
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsFromFileCommand.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
  src/Kunstmaan/TranslatorBundle/Resources/config/commands.yml
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
Labels: Type: Bugfix

#2213 [GeneratorBundle] Fixed broken composer.json
  src/Kunstmaan/GeneratorBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Administrators, Type: Bugfix

#2214 [AdminBundle] Enable automatic tagging of menu adaptor classes
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2215 [KunstmaanTranslatorBundle] improvements to import command
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
  src/Kunstmaan/TranslatorBundle/Resources/config/commands.yml
Labels: Type: Improvement

#2225 [GeneratorBundle] Enable generators that have support for sf4
  src/Kunstmaan/GeneratorBundle/DependencyInjection/KunstmaanGeneratorExtension.php
  src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2226 [GeneratorBundle] Remove password replace for sf4
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2228 [GeneratorBunde] Fix entity generator with repository class creation for sf4
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2227 [AllBundles] Fix code style issues merged in the master branch
  src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
  src/Kunstmaan/NodeBundle/Entity/PageTabInterface.php
  src/Kunstmaan/NodeBundle/EventListener/EntityTabListener.php
  src/Kunstmaan/NodeBundle/EventListener/NodeListener.php
  src/Kunstmaan/NodeBundle/EventListener/NodeTabListener.php
  src/Kunstmaan/NodeBundle/Tests/unit/Entity/NodeTest.php
  src/Kunstmaan/NodeBundle/Tests/unit/Helper/NodeHelperTest.php
  src/Kunstmaan/NodeBundle/ValueObject/PageTab.php
Labels: Priority: Normal, Target audience: Developers

#2224 [NodeBundle] Fixed url chooser for multidomain
  src/Kunstmaan/NodeBundle/Helper/URLHelper.php
  src/Kunstmaan/NodeBundle/Validation/URLValidator.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2182 [AdminBundle] Catch InvalidArgumentException in MediaTokenTransformer
  src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2233 [AllBundles] Set default menu adaptor priorities enabled bundle order doesn't matter
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/UserManagementBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2235 [GeneratorBundle] refactored page generator
  src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
  src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/PageGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php
  src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2240 [GeneratorBundle] refactored entity generator
  src/Kunstmaan/GeneratorBundle/Command/GenerateEntityCommand.php
  src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2229 [GeneratorBundle] Improve entity repository class output for symfony 4
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/Symfony4EntityRepositoryGenerator.php
Labels: Priority: Normal, Target audience: Developers, sf4-compatibility

#2231 [AdminBundle] Use correct parameter to retrieve website title
  src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers

#2241 [PagePartBundle] refactored parsers for sf4
  src/Kunstmaan/PagePartBundle/PagePartConfigurationReader/PagePartConfigurationParser.php
  src/Kunstmaan/PagePartBundle/PageTemplate/PageTemplateConfigurationParser.php
  src/Kunstmaan/PagePartBundle/Tests/unit/PagePartConfigurationReader/LocatingKernelStub.php
  src/Kunstmaan/PagePartBundle/Tests/unit/PagePartConfigurationReader/PagePartConfigurationParserTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/PageTemplate/PageTemplateConfigurationParserTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/PageTemplate/Resources/config/pagetemplates/test.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2239 [RedirectBundle] Removed Redirect entity update bug in RedirectRouter
  src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
Labels: Type: Bugfix

#2230 [AdminBundle] Provide twig globals with twig extension
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Twig/AdminBundleTwigExtension.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2232 [DashboardBundle] Enable esi by default for the dashboard bundle
  src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
Labels: Priority: Normal, Target audience: Developers, sf4-compatibility

#2238 [MediaBundle] Check if media metadata has width/height info
  src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix

#2245 [GeneratorBundle] refactored formpage generator
  src/Kunstmaan/GeneratorBundle/Command/GenerateFormPageCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/FormPageGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2247 [GeneratorBundle] update parent regex in article generator
  src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/ArticleGenerator.php
Labels: Type: Feature

#2243 [GeneratorBundle] Sf4 support for searchpage generator
  src/Kunstmaan/GeneratorBundle/Command/GenerateSearchPageCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/SearchPageGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Entity/Pages/SearchPage.php
  src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2244 [GeneratorBundle] Sf4 support for admintests generator
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminTestsCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/AdminTestsGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/FeatureContext.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/GroupContext.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/MediaContext.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/PageContext.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/PagePartContext.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/RoleContext.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/UserContext.php
  src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, sf4-compatibility

#2248 [UtilitiesBundle] Update composer json
  src/Kunstmaan/UtilitiesBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2249 [AdminBundle] update composer
  src/Kunstmaan/AdminBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2251 [Composer] Fix composer json for admin/adminlist/behat/media/node/pagepart bundle
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/ConfigBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/PagePartBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2252 [UtilitiesBundle] Fix missing dependency
  src/Kunstmaan/UtilitiesBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2253 [NodeBundle] Fix missing dependency
  src/Kunstmaan/NodeBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2254 [ArticleBundle] Fix article deps
  src/Kunstmaan/ArticleBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2255 [FormBundle] Fix dependencies
  src/Kunstmaan/FormBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2256 [MediaPagePartBundle] Fix dependencies
  src/Kunstmaan/MediaPagePartBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2258 [DashboardBundle] Fix dependencies
  src/Kunstmaan/DashboardBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2259 [CacheBundle] Added composer json
  src/Kunstmaan/CacheBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2257 [GeneratorBundle] Fix dependencies
  src/Kunstmaan/GeneratorBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2037 [UserManagementBundle] updated composer dependencies
  src/Kunstmaan/UserManagementBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2260 [MenuBundle] Fixed dependencies
  src/Kunstmaan/MenuBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2261 [MultiDominBundle] Added composer json + gitignore
  src/Kunstmaan/MultiDomainBundle/.gitignore
  src/Kunstmaan/MultiDomainBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2262 [SearchBundle] Fix dependencies
  src/Kunstmaan/SearchBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2034 [VotingBundle] updated dependencies
  src/Kunstmaan/VotingBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2263 [SearchBundle] Fix wrong dependency
  src/Kunstmaan/SearchBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2265 [NodeSearchBundle] Fix dependencies
  src/Kunstmaan/NodeSearchBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2267 [MediaBundle] Fix wrong dependency
  src/Kunstmaan/MediaBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#1983 [AdminListBundle] Allow sorting by association
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractDoctrineORMAdminListConfiguratorTest.php
Labels: Priority: Normal, Profile: Backend, Type: Feature

#2268 [SeoBundle] Fix dependencies + remove wrong test
  src/Kunstmaan/SeoBundle/Tests/unit/Entity/SeoTest.php
  src/Kunstmaan/SeoBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2092 [SiteMapBundle] update composer dependencies
  src/Kunstmaan/SitemapBundle/composer.json
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2082 [TaggingBundle] updated composer dependencies
  src/Kunstmaan/TaggingBundle/composer.json
Labels: Priority: Normal, Profile: Backend, sf4-compatibility

#2269 [RedirectBundle] Fix dependencies
  src/Kunstmaan/RedirectBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2084 [TranslatorBundle] update composer dependencies
  src/Kunstmaan/TranslatorBundle/Resources/config/repositories.yml
  src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
  src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/KunstmaanTaggingExtensionTest.php
  src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/KunstmaanTranslatorExtensionTest.php
  src/Kunstmaan/TranslatorBundle/composer.json
Labels: Priority: High, Profile: Backend, sf4-compatibility

#2270 [LeadGenerationBundle] update dependencies + fix autoload
  src/Kunstmaan/LeadGenerationBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2199 [AdminBundle] Update _form-group.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-group.scss
Labels: Type: Bugfix

#2272 [FixturesBundle] Update dependencies
  src/Kunstmaan/FixturesBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2275 [Composer] Cleanup + fix missing dependencies
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/GeneratorBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/RedirectBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Priority: High, Profile: Backend, Target audience: Developers, Type: Improvement, sf4-compatibility

#2277 [GeneratorBundle] Fix incorrect plural of certain table names
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Bugfix

#2271 [AdminBundle] composer update
  src/Kunstmaan/AdminBundle/Tests/unit/EventListener/ConsoleExceptionListenerTest.php
  src/Kunstmaan/AdminBundle/composer.json
Labels: Type: Feature

#2312 [AdminBundle] fixed bad merge in composer.json
  src/Kunstmaan/AdminBundle/composer.json
Labels: Priority: High, Profile: Backend, Type: Bugfix
