Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2019-07, with the labels that each got.

#2462 [GeneratorBundle] Fix webpack output path for admin-bundle-extra js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.admin-extra.js
Labels: Priority: Normal, Target audience: Developers, Type: Bugfix

#2493 [AdminBundle] Add string return typehint to be compatible with symfony 4.3
  src/Kunstmaan/AdminBundle/Entity/Role.php
Labels: Priority: Normal, Type: Bugfix, sf4-compatibility

#2510 [GeneratorBundle] Added missing import in admin js task
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.admin-extra.js
Labels: Priority: High, Type: Bugfix

#2497 [AllBundles] Upgrade jquery to fix security warning
  package-lock.json
  package.json
Labels: Type: Bugfix

#2500 [FixtureBundle] Inject the User Entity class name so the correct Repository can be used
  src/Kunstmaan/FixturesBundle/Builder/PageBuilder.php
  src/Kunstmaan/FixturesBundle/Resources/config/services.yml
Labels: Profile: Backend, Target audience: Developers, Type: Bugfix

#2502 [TranslatorBundle] Restored missing service alias for translator datacollector
  src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPass.php
Labels: Priority: Normal, Type: Bugfix

#2503 [NodeBundle] missing form error translations
  src/Kunstmaan/NodeBundle/Resources/translations/messages.nl.yml
Labels: Type: Bugfix

#2506 [AdminBundle] added support for anchor tags in MediaTokenTransformer
  src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
Labels: Type: Bugfix

#2530 [AdminListBundle] Fixed undefined entity when creating entity having itemActions
  src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
Labels: Type: Bugfix

#2518 [NodeBundle] Updated SlugType prefix build
  src/Kunstmaan/NodeBundle/Form/Type/SlugType.php
Labels: Type: Bugfix

#2531 [NodeBundle] Fix incorrect step in documentation
  src/Kunstmaan/NodeBundle/Resources/doc/Locking.md
Labels: Type: Bugfix, Type: Feature

#2534 [AdminListBundle] Fix missing date and time suffixes on form fields #…
  src/Kunstmaan/AdminListBundle/Resources/views/FilterType/dateTimeFilter.html.twig
Labels: Type: Bugfix
