Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2020-09, with the labels that each got.

#2717 [MediaBundle] Fix remote media not shown in icon view
  src/Kunstmaan/MediaBundle/Controller/ChooserController.php
Labels: Type: Bugfix

#2731 [UserManagementBundle] Remove incorrect class parameter deprecation
  src/Kunstmaan/UserManagementBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
  src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Type: Bugfix

#2730 [MediaBundle] Fix deprecated twig controller render notation
  src/Kunstmaan/MediaBundle/Resources/views/Folder/bulk-move-modal.html.twig
Labels: Type: Improvement

#2668 [MediaBundle] Refactor deprecated mimetypeguesser from symfony
  composer.json
  src/Kunstmaan/FixturesBundle/Builder/MediaBuilder.php
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaBundle/Helper/ExtensionGuesserFactory.php
  src/Kunstmaan/MediaBundle/Helper/ExtensionGuesserFactoryInterface.php
  src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
  src/Kunstmaan/MediaBundle/Helper/File/SVGExtensionGuesser.php
  src/Kunstmaan/MediaBundle/Helper/File/SVGMimeTypeGuesser.php
  src/Kunstmaan/MediaBundle/Helper/Image/ImageHandler.php
  src/Kunstmaan/MediaBundle/Helper/MimeTypeGuesserFactory.php
  src/Kunstmaan/MediaBundle/Helper/MimeTypeGuesserFactoryInterface.php
  src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
  src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/File/PdfHandlerTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/Image/ImageHandlerTest.php
  src/Kunstmaan/MediaBundle/Validator/Constraints/HasGuessableExtensionValidator.php
  src/Kunstmaan/MediaBundle/composer.json
Labels: Type: Deprecation

#2741 [AdminBundle] Replace deprecated getRootDir call
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/Permission/PermissionAdminTest.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateSearchPageCommand.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaBundle/Helper/File/PdfHandler.php
  src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
Labels: Type: Improvement

#2747 [AdminBundle] Change admin locale listener priority to after firewall listener
  src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
Labels: Type: Bugfix

#2745 [GeneratorBundle] Don't add deprecated logout_on_user_change config option
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/config/security.yaml
Labels: Type: Improvement

#2718 [GeneratorBundle] Preserve query parameters during redirect
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/DefaultController.php
Labels: Type: Improvement

#2740 [MediaBundle] Fix liip/imagine controller deprecation
  composer.json
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/MediaBundle/composer.json
Labels: Type: Improvement

#2742 [MediaBundle] Deprecate aviary related code
  UPGRADE-5.7.md
  src/Kunstmaan/MediaBundle/Controller/AviaryController.php
  src/Kunstmaan/MediaBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaBundle/Helper/Image/ImageHandler.php
  src/Kunstmaan/MediaBundle/Resources/views/Media/Image/aviary.html.twig
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/KunstmaanMediaExtensionTest.php
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/Image/ImageHandlerTest.php
Labels: Type: Deprecation

#2743 [AllBundles] Fix Event class and EventDispatcher argument order deprecations
  phpstan.neon
  src/Kunstmaan/AdminBundle/Event/AdaptSimpleFormEvent.php
  src/Kunstmaan/AdminBundle/Event/BcEvent.php
  src/Kunstmaan/AdminBundle/Event/DeepCloneAndSaveEvent.php
  src/Kunstmaan/AdminBundle/Helper/CloneHelper.php
  src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
  src/Kunstmaan/AdminListBundle/Event/AdminListEvent.php
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/FormBundle/Event/SubmissionEvent.php
  src/Kunstmaan/FormBundle/Helper/FormHandler.php
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
  src/Kunstmaan/NodeBundle/Controller/SlugController.php
  src/Kunstmaan/NodeBundle/Event/AdaptFormEvent.php
  src/Kunstmaan/NodeBundle/Event/ConfigureActionMenuEvent.php
  src/Kunstmaan/NodeBundle/Event/NodeEvent.php
  src/Kunstmaan/NodeBundle/Event/SlugEvent.php
  src/Kunstmaan/NodeBundle/Event/SlugSecurityEvent.php
  src/Kunstmaan/NodeBundle/EventListener/SlugListener.php
  src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
  src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
  src/Kunstmaan/NodeBundle/Helper/NodeHelper.php
  src/Kunstmaan/NodeBundle/Helper/PageCloningHelper.php
  src/Kunstmaan/NodeBundle/Tests/unit/Helper/NodeHelperTest.php
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
  src/Kunstmaan/NodeSearchBundle/Event/IndexNodeEvent.php
  src/Kunstmaan/NodeSearchBundle/composer.json
  src/Kunstmaan/PagePartBundle/Event/PagePartEvent.php
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
  src/Kunstmaan/PagePartBundle/composer.json
  src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
  src/Kunstmaan/VotingBundle/Controller/VotingController.php
  src/Kunstmaan/VotingBundle/Event/AbstractVoteEvent.php
Labels: Type: Improvement

#2754 [FormBundle] Inject correct service in form mailer
  src/Kunstmaan/FormBundle/Resources/config/services.yml
Labels: Type: Deprecation

#2758 [NodeBundle] Dont start session if not needed
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
Labels: Type: Bugfix

#2759 [AdminBundle] Add brands to font awesome imports
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/config/vendors/font-awesome/_font-awesome-imports.scss
Labels: Type: Bugfix

#2760 [MediaBundle] Add width and height to media show
  src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/MediaBundle/Resources/views/Media/show.html.twig
Labels: Type: Feature

#2746 [GeneratorBundle] Replace deprecation transchoice filter
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Resources/views/Pages/SearchPage/view.html.twig
Labels: Type: Improvement

#2738 [GeneratorBundle] Fix article fixture for articles without authors
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
Labels: Type: Bugfix

#2716 [NodeBundle] Rename incorrect named NodeTranslation repository method
  UPGRADE-5.7.md
  src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
Labels: Type: Deprecation

#2719 [AdminBundle] update fe packages
  .babelrc
  .nvmrc
  .travis.yml
  groundcontrol/admin-bundle.tasks.js
  groundcontrol/tasks/bundle.js
  gulpfile.babel.js
  package-lock.json
  package.json
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle-polyfills.js.map
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js.map
  src/Kunstmaan/DashboardBundle/Resources/public/css/dashboard.css
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/.babelrc
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/.nvmrc
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.default.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
Labels: Profile: Frontend, Type: Feature, Type: Needs work

#2766 [MediaBundle] Update bulk move translations
  src/Kunstmaan/MediaBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/MediaBundle/Resources/translations/messages.pl.yml
Labels: Type: Feature
