Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2020-12, with the labels that each got.

#2835 [NodeBundle] Fix: Wrong variable in PHPDoc
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
Labels: Type: Bugfix

#2830 [AllBundles] Switch from styleci to flintci
  .flintci.yml
Labels: Type: Improvement

#2832 [AllBundles] Switch CI setup from travisci to github actions
  .github/workflows/ci-frontend.yml
  .github/workflows/ci.yml
  .github/workflows/code-quality.yml
  .travis.yml
Labels: Type: Improvement

#2838 [AllBundles] Fix test failure for stable deps
  .github/workflows/ci.yml
  src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/FileFormSubmissionFieldTest.php
Labels: Type: Bugfix, Type: Improvement

#2837 [GeneratorBundle] Remove unnecessary form role
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/FormPage/pagetemplate.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/formpage/Resources/views/Pages/FormPage/pagetemplate.html.twig
Labels: Type: Feature
