Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2020-11, with the labels that each got.

#2800 [NodeSearchBundle] Allow include offline option get_parent twig function.
  src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
Labels: Type: Feature

#2801 [AdminBundle] Add media token transformer as service
  src/Kunstmaan/AdminBundle/Form/WysiwygType.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Tests/unit/Form/WysiwygTypeTest.php
  src/Kunstmaan/FormBundle/Tests/unit/Form/AbstractFormPageAdminTypeTest.php
Labels: Type: Feature, Type: Needs work

#2808 [AdminBundle] fix max-width textarea/wysiwyg
  package-lock.json
  package.json
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-group.scss
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/RawHtmlPagePart/RawHtmlPagePartAdminType.php
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2810 [MediaBundle] Fix media list without pagination
  src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
Labels: Type: Bugfix

#2824 [CacheBundle] Enhancement: Streamline tests
  src/Kunstmaan/CacheBundle/Tests/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
Labels: Type: Bugfix

#2816 [AdminBundle] fix path of sortablejs - fixes broken build
  groundcontrol/admin-bundle.tasks.js
Labels: Profile: Frontend, Target audience: Developers

#2822 [ArticleBundle] Enhancement: Streamline tests
  src/Kunstmaan/ArticleBundle/Tests/AdminList/AbstractArticleAuthorAdminListConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/AdminList/AbstractArticlePageAdminListConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/ArticleBundle/Tests/DependencyInjection/KunstmaanArticleExtensionTest.php
  src/Kunstmaan/ArticleBundle/Tests/Entity/AbstractArticleOverviewPageTest.php
  src/Kunstmaan/ArticleBundle/Tests/Entity/AbstractArticlePageTest.php
  src/Kunstmaan/ArticleBundle/Tests/Entity/AbstractAuthorTest.php
  src/Kunstmaan/ArticleBundle/Tests/Form/AbstractArticleOverviewPageAdminTypeTest.php
  src/Kunstmaan/ArticleBundle/Tests/Form/AbstractArticlePageAdminTypeTest.php
  src/Kunstmaan/ArticleBundle/Tests/Form/AbstractAuthorAdminTypeTest.php
  src/Kunstmaan/ArticleBundle/Tests/PagePartAdmin/AbstractArticleOverviewPagePagePartAdminConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/PagePartAdmin/AbstractArticlePagePagePartAdminConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/Repository/AbstractArticleOverviewPageRepositoryTest.php
Labels: Type: Bugfix

#2812 [NodeBundle] Change nodetranslation slug/url fields to text type to allow long values
  composer.json
  src/Kunstmaan/NodeBundle/Entity/NodeTranslation.php
  src/Kunstmaan/NodeBundle/composer.json
Labels: Type: Bugfix

#2815 [AdminBundle] allow slug input-group to use more space if available
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/_components.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_slug-chooser.scss
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
  src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix
