Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2020-06, with the labels that each got.

#2684 [GeneratorBundle] Use https by default to avoid any mixed content errors
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_webfonts.html.twig
Labels: Type: Bugfix

#2686 [NodeBundle] Allow duplicate with children
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
  src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
  src/Kunstmaan/NodeBundle/Entity/DuplicateSubPageInterface.php
  src/Kunstmaan/NodeBundle/Entity/Node.php
  src/Kunstmaan/NodeBundle/Event/Events.php
  src/Kunstmaan/NodeBundle/Event/NodeDuplicateEvent.php
  src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
  src/Kunstmaan/NodeBundle/Helper/PageCloningHelper.php
  src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_duplicate_with_children.html.twig
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
  src/Kunstmaan/NodeBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
Labels: Type: Feature

#2693 [NodeBundle] Refactored duplicate events for better usage
  src/Kunstmaan/NodeBundle/Event/PostNodeDuplicateEvent.php
  src/Kunstmaan/NodeBundle/Event/PreNodeDuplicateEvent.php
  src/Kunstmaan/NodeBundle/Helper/PageCloningHelper.php
Labels: Profile: Backend, Type: Feature

#2673 [MediaBundle] Aviariy does not exist anymore
  src/Kunstmaan/MediaBundle/Resources/doc/MediaBundle.md
Labels: Type: Bugfix, Type: Deprecation

#2675 [FormBundle] Cascade delete form submission fields when removing a form submission
  src/Kunstmaan/FormBundle/Entity/FormSubmission.php
  src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php
Labels: Type: Improvement

#2666 [AdminBundle] Remember editor content when dragging and dropping
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js
Labels: Type: Bugfix, Type: Needs work

#2660 [AllBundles] Integrate phpstan in travis build suite
  .travis.yml
  composer.json
  phpstan.neon
  src/Kunstmaan/AdminBundle/Controller/ExceptionController.php
  src/Kunstmaan/AdminBundle/Helper/AdminRouteHelper.php
  src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
  src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
  src/Kunstmaan/AdminListBundle/AdminList/FieldAlias.php
  src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/Symfony4EntityRepositoryGenerator.php
  src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
  src/Kunstmaan/NodeBundle/Helper/NodeMenu.php
  src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
  src/Kunstmaan/TranslatorBundle/Service/Translator/CacheValidator.php
Labels: Type: Improvement

#2692 [AdminBundle][AdminListBundle] translation in admin fixes
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminListBundle/Service/ExportService.php
Labels: Type: Bugfix

#2679 [AllBundles] Validate composer.json files in travis build
  .build/validate-composer.sh
  .gitattributes
  .travis.yml
  composer.json
Labels: Type: Improvement

#2678 [NodeBundle] Improve url helper by replacing full data load by specific lookup
  src/Kunstmaan/NodeBundle/Helper/URLHelper.php
  src/Kunstmaan/NodeBundle/Tests/unit/Helper/UrlHelperTest.php
Labels: Type: Improvement

#2695 [SearchBundle][NodeSearch] Add elastica/elasticsearch 7 support
  UPGRADE-5.6.md
  composer.json
  src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
  src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
  src/Kunstmaan/NodeSearchBundle/Search/AbstractElasticaSearcher.php
  src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
  src/Kunstmaan/NodeSearchBundle/Search/SearcherInterface.php
  src/Kunstmaan/SearchBundle/Provider/ElasticaProvider.php
Labels: Type: Feature

#2697 [SearchBundle] Updated ruflin/elastic version constraint in search bundle package
  src/Kunstmaan/SearchBundle/composer.json
Labels: Type: Bugfix

#2699 [AllBundles] Fix missing use statements
  src/Kunstmaan/DashboardBundle/Repository/AnalyticsSegmentRepository.php
  src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
Labels: Type: Bugfix

#2702 [AllBundles] Fix remaining phpstan issues
  .travis.yml
  src/Kunstmaan/MediaBundle/Repository/MediaRepository.php
  src/Kunstmaan/SearchBundle/Provider/ElasticaProvider.php
Labels: Type: Bugfix

#2700 [NodeBundle] Fix NodeRepository getNodeByInternalName return typehint
  src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
Labels: Type: Bugfix
