Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2020-08, with the labels that each got.

#2713 [AllBundles] Update styleci config for changes in symfony preset
  .styleci.yml
  src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/MaskBuilder.php
  src/Kunstmaan/AdminBundle/Repository/AclChangesetRepository.php
  src/Kunstmaan/AdminBundle/Tests/unit/Validator/Constraints/PasswordRestrictionsValidatorTest.php
  src/Kunstmaan/AdminListBundle/AdminList/BulkAction/SimpleBulkAction.php
  src/Kunstmaan/AdminListBundle/AdminList/Field.php
  src/Kunstmaan/AdminListBundle/AdminList/FilterType/AbstractFilterType.php
  src/Kunstmaan/AdminListBundle/AdminList/ItemAction/SimpleItemAction.php
  src/Kunstmaan/AdminListBundle/AdminList/ListAction/SimpleListAction.php
  src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
  src/Kunstmaan/DashboardBundle/Command/DashboardCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigFlushCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigsListCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataFlushCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsListCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsSegmentsListCommand.php
  src/Kunstmaan/FixturesBundle/Parser/Property/Method.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/Symfony4EntityRepositoryGenerator.php
  src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/MultiDomainBundle/Router/DomainBasedLocaleRouter.php
  src/Kunstmaan/NodeBundle/Entity/NodeVersionLock.php
  src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
  src/Kunstmaan/NodeBundle/Helper/NodeMenuItem.php
  src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
  src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
  src/Kunstmaan/NodeBundle/Router/SlugRouter.php
  src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
  src/Kunstmaan/SearchBundle/Command/DeleteIndexCommand.php
  src/Kunstmaan/SearchBundle/Command/PopulateIndexCommand.php
  src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
  src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
  src/Kunstmaan/VotingBundle/EventListener/AbstractVoteListener.php
Labels: Type: Bugfix

#2708 [NodeBundle] Sort node versions DESC
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
Labels: Type: Feature

#2672 [AdminBundle, MediaBundle] replace deprecated integer as errorcode in constraints
  UPGRADE-5.7.md
  src/Kunstmaan/AdminBundle/Validator/Constraints/PasswordRestrictions.php
  src/Kunstmaan/MediaBundle/Validator/Constraints/HasGuessableExtension.php
  src/Kunstmaan/MediaBundle/Validator/Constraints/Media.php
Labels: Type: Deprecation

#2707 [AdminBundle] advanced js select for enumeration filter
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_app-filter.js
  src/Kunstmaan/AdminListBundle/Resources/views/FilterType/enumerationFilter.html.twig
Labels: Type: Feature

#2712 [TranslatorBundle] Added missing validation on translation file
  src/Kunstmaan/TranslatorBundle/Form/TranslationsFileUploadType.php
Labels: Type: Bugfix
