Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2020-10, with the labels that each got.

#2772 [MediaBundle] getImageUrl has only 2 params
  src/Kunstmaan/MediaBundle/Resources/views/AdminList/ItemAction/select.html.twig
Labels: Type: Bugfix, Type: Improvement

#2756 [AdminBundle] Bump knplabs/knp-menu-bundle and remove default config
  composer.json
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/composer.json
Labels: Type: Improvement

#2757 [AllBundles] Bump doctrine/fixture-bundle to support symfony 5
  composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
Labels: Type: Improvement

#2744 [NodeSearchBundle] Introduce SearchViewRenderer service to deprecate/remove remaining templating usages
  UPGRADE-5.7.md
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
  src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
  src/Kunstmaan/NodeSearchBundle/Services/SearchViewRenderer.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Services/SearchViewRendererTest.php
Labels: Type: Deprecation, Type: Feature

#2739 [TranslatorBundle] Don't use temporary filename for spreadsheet translation imports
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
Labels: Type: Bugfix

#2762 [AdminBundle] Fix icons in url chooser
  src/Kunstmaan/AdminBundle/Resources/ui/js/_app-urlchooser-tree.js
Labels: Profile: Frontend, Type: Bugfix

#2771 [MediaBundle] Remove empty src set
  src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig
Labels: Type: Bugfix

#2785 [AdminBundle] Fix wrong PHPDoc
  src/Kunstmaan/AdminBundle/Helper/Menu/MenuAdaptorInterface.php
Labels: Type: Bugfix, Type: Improvement

#2778 [NodeBundle] Remove duplicate query order by
  src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
Labels: Type: Bugfix

#2779 [AdminBundle] Allow symfony/acl-bundle 2.0
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
Labels: Type: Improvement

#2770 [GeneratorBundle] Avoid extra questions during install command
  src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
Labels: Target audience: Developers, Type: Improvement

#2775 [AllBundles] Allow next majors of doctrine-bundle and doctrine-migrations-bundle to prepare symfony 5 support
  composer.json
  phpstan.neon
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/TranslatorBundle/Command/MigrationsDiffCommand.php
  src/Kunstmaan/TranslatorBundle/Service/Command/DiffCommand.php
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement

#2715 [MultidomainBundle] Fix getRootNode method to handle multiple calls with different hosts
  src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
Labels: Type: Bugfix

#2767 [GeneratorBundle] Fix demo site datafixtures url validation errors
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
  src/Kunstmaan/NodeBundle/Entity/Node.php
Labels: Type: Bugfix

#2761 [MediaBundle] Position sort by and limit
  src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
Labels: Profile: Frontend, Type: Improvement

#2769 [AllBundles] Use absolute_url twig function instead of using app.request data
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/DownloadPagePart/view.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Media/File/show.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Media/Image/show.html.twig
  src/Kunstmaan/MediaPagePartBundle/Resources/views/DownloadPagePart/view.html.twig
  src/Kunstmaan/MediaPagePartBundle/Resources/views/ImagePagePart/view.html.twig
  src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
Labels: Type: Feature

#2787 [AllBundles] Bump minimum supported symfony 4 version tot 4.4
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement

#2789 [AllBundles] Removed the unused ddeboer/data-import-bundle dependency
  composer.json
Labels: Type: Improvement

#2720 [AdminBundle][UserManagementBundle] Improve audit log for creating/deleting users
  UPGRADE-5.7.md
  composer.json
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
  src/Kunstmaan/AdminBundle/Entity/BaseUser.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
  src/Kunstmaan/NodeBundle/Tests/unit/Helper/NodeHelperTest.php
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
  src/Kunstmaan/UserManagementBundle/Event/AfterUserDeleteEvent.php
  src/Kunstmaan/UserManagementBundle/Event/UserEvents.php
  src/Kunstmaan/UserManagementBundle/EventSubscriber/UserDeleteEventSubscriber.php
  src/Kunstmaan/UserManagementBundle/Resources/config/services.yml
  src/Kunstmaan/UserManagementBundle/composer.json
Labels: Type: Feature

#2799 [AdminListBundle] disable sort arrows of first & last item
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/blocks/_tables.scss
  src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
Labels: Profile: Frontend, Target audience: Administrators, Type: Improvement

#2796 [SensioGeneratorBundle] Fixed typo in form class name
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/Pages/ContentPageAdminType.php
Labels: Type: Bugfix

#2798 [AdminBundle] autofocus search input when opening modal
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/pagepart-search/initSearch.js
Labels: Profile: Frontend, Target audience: Administrators, Type: Improvement

#2790 [DashboardBundle] Improve dashboarbundle dx
  src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
Labels: Type: Improvement

#2797 [GeneratorBundle] Remove buildCmsAssets from generated FE tasks - assets are compiled in git repo
  UPGRADE-5.7.md
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/gulpfile.babel.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
Labels: Profile: Frontend, Target audience: Developers, Type: Deprecation

#2791 [NodeBundle] Replace setter injection in node helper services
  UPGRADE-5.7.md
  src/Kunstmaan/NodeBundle/Helper/Services/ACLPermissionCreatorService.php
  src/Kunstmaan/NodeBundle/Helper/Services/PageCreatorService.php
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
Labels: Type: Improvement

#2803 [AdminBundle] use kunstmaan bundles logo in toolbar
  src/Kunstmaan/AdminBundle/Resources/views/Toolbar/Icon/kunstmaan.svg
  src/Kunstmaan/AdminBundle/Resources/views/Toolbar/Icon/time.svg
  src/Kunstmaan/AdminBundle/Resources/views/Toolbar/bundles_version.html.twig
Labels: Priority: Low, Profile: Frontend, Target audience: Administrators, Type: Improvement

#2751 [AdminBundle] Prepare code to remove deprecated doctrine/cache and replace with symfony/cache
  UPGRADE-5.7.md
  composer.json
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/VersionCheckerCacheBcPass.php
  src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
  src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/VersionCheck/VersionCheckTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/KunstmaanAdminBundleTest.php
  src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
  src/Kunstmaan/AdminBundle/composer.json
Labels: Type: Deprecation

#2805 [NodeBundle] Improve nodetranslation repository deprecation
  src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
  src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
Labels: Type: Improvement

#2807 [GeneratorBundle] Add missing interface to generated fixtures for auto service registration
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/SitemapFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/DataFixtures/ORM/SearchPageGenerator/SearchFixtures.php
Labels: Type: Bugfix

#2794 [GeneratorBundle] exit build if a build task throws an error
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/bundle.js
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/css.js
Labels: Profile: Frontend, Target audience: Developers, Type: Improvement

#2806 [LeadGenerationBundle] fixed doc, getAdminType should be string
  docs/cookbook/using-the-leadgenerationbundle.md
Labels: Type: Needs work

#2792 [AdminBundle] Force dropdown to remain open after selection
  src/Kunstmaan/AdminBundle/Resources/ui/js/_advanced-select.js
Labels: Profile: Frontend, Target audience: Administrators, Type: Feature

#2804 [AdminBundle] setup CSS Next
  .eslintrc
  .stylelintrc
  groundcontrol/admin-bundle.tasks.js
  groundcontrol/start-local.task.js
  gulpfile.babel.js
  package-lock.json
  package.json
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/public/cssnext/style.css
  src/Kunstmaan/AdminBundle/Resources/public/icons/selection.json
  src/Kunstmaan/AdminBundle/Resources/public/icons/symbol-defs.svg
  src/Kunstmaan/AdminBundle/Resources/ui/icons/selection.json
  src/Kunstmaan/AdminBundle/Resources/ui/icons/symbol-defs.svg
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/config.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/index.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/pagepart-search/initSearch.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/pagepart-search/resetSearch.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser/pagepart-search/updateSearch.js
  src/Kunstmaan/AdminBundle/Resources/ui/jsnext/app.js
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/00-bootstrap/_all.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/00-bootstrap/config/_breakpoints.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/00-bootstrap/config/_easings.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/00-bootstrap/config/_z-indexes.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/00-bootstrap/helpers/_deep-get.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/00-bootstrap/helpers/_text.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/00-bootstrap/snipsonian/_snipsonian-imports.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/00-bootstrap/utils/_base.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/01-quarks/_all.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/01-quarks/_colors.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/02-atoms/_all.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/03-molecules/_all.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/style.scss
  src/Kunstmaan/AdminBundle/Resources/views/Default/_css_next.html.twig
Labels: Profile: Frontend, Target audience: Developers, Type: Needs work
