Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2020-05, with the labels that each got.

#2669 [AdminBundle] Remove monolog main handler configuration
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
Labels: Type: Improvement

#2671 [MediaBundle] Fix php 7.4 incompatibility
  src/Kunstmaan/MediaBundle/Helper/Image/ImageHandler.php
  src/Kunstmaan/MediaBundle/Tests/unit/Fixtures/sample.svg
  src/Kunstmaan/MediaBundle/Tests/unit/Helper/Image/ImageHandlerTest.php
Labels: Type: Bug

#2658 [GeneratorBundle] Fix doctrine fixtures error during install command
  src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
Labels: Type: Bugfix

#2659 [AllBundles] Rework travis-ci test setup
  .travis.yml
Labels: Type: Improvement

#2676 [AllBundles] Fix incorrect typecast in UrlHelper
  src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/AdminBundle/Helper/DomainConfigurationInterface.php
  src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/NodeBundle/Helper/URLHelper.php
Labels: Priority: High, Type: Bug
