Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2020-01, with the labels that each got.

#2607 [MediaBundle] Fix typo in template path
  src/Kunstmaan/MediaBundle/AdminList/ItemAction/MediaSelectItemAction.php
Labels: Type: Bugfix, Type: Feature

#2605 [NodeBundle] Fixed default page icon
  src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
Labels: Type: Bugfix

#2550 [AllBundles] Replaced deprecated spaceless tag
  composer.json
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/PermissionsAdminTwigExtension/widget.html.twig
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Form/fields.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig
  src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
  src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/widget.html.twig
  src/Kunstmaan/TaggingBundle/Resources/views/Form/fields.html.twig
Labels: Target audience: Developers, Type: Improvement

#2576 [FormBundle] Deprecate and replace container injection in form mailer
  UPGRADE-5.4.md
  src/Kunstmaan/FormBundle/Helper/FormMailer.php
  src/Kunstmaan/FormBundle/Tests/unit/Helper/FormMailerTest.php
Labels: Priority: Normal, Target audience: Developers, Type: Deprecation

#2595 [AdminListBundle] Don't call deprecated setters in ExportService
  UPGRADE-5.4.md
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminListBundle/Resources/config/services.yml
Labels: Type: Bugfix, Type: Feature

#2600 [AllBundles] Commands should return an integer exitcode
  src/Kunstmaan/AdminBundle/Command/ApplyAclCommand.php
  src/Kunstmaan/AdminBundle/Command/CreateGroupCommand.php
  src/Kunstmaan/AdminBundle/Command/CreateRoleCommand.php
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
  src/Kunstmaan/AdminBundle/Command/ExceptionCommand.php
  src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
  src/Kunstmaan/DashboardBundle/Command/DashboardCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigFlushCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigsListCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataFlushCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsListCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsSegmentsListCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminTestsCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateConfigCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultPagePartsCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateEntityCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateFormPageCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateFormPagePartsCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateLayoutCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GeneratePagePartCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateSearchPageCommand.php
  src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
  src/Kunstmaan/MediaBundle/Command/CleanDeletedMediaCommand.php
  src/Kunstmaan/MediaBundle/Command/CreatePdfPreviewCommand.php
  src/Kunstmaan/MediaBundle/Command/RebuildFolderTreeCommand.php
  src/Kunstmaan/MediaBundle/Command/RenameSoftDeletedCommand.php
  src/Kunstmaan/NodeBundle/Command/CronUpdateNodeCommand.php
  src/Kunstmaan/NodeBundle/Command/InitAclCommand.php
  src/Kunstmaan/SearchBundle/Command/DeleteIndexCommand.php
  src/Kunstmaan/SearchBundle/Command/PopulateIndexCommand.php
  src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
  src/Kunstmaan/TranslatorBundle/Command/ExportTranslationsCommand.php
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsFromFileCommand.php
  src/Kunstmaan/TranslatorBundle/Command/MigrationsDiffCommand.php
  src/Kunstmaan/TranslatorBundle/Command/TranslationFlagCommand.php
  src/Kunstmaan/TranslatorBundle/Service/Command/DiffCommand.php
  src/Kunstmaan/UtilitiesBundle/Command/CipherCommand.php
Labels: Type: Improvement

#2601 [AllBundles] BC layer for deprecated event classes
  src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
  src/Kunstmaan/AdminBundle/EventListener/ExceptionSubscriber.php
  src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
  src/Kunstmaan/AdminBundle/EventListener/SessionSecurityListener.php
  src/Kunstmaan/AdminBundle/EventListener/ToolbarListener.php
  src/Kunstmaan/MultiDomainBundle/EventListener/HostOverrideListener.php
  src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
  src/Kunstmaan/NodeBundle/EventListener/SlugListener.php
Labels: Type: Improvement

#2549 [GeneratorBundle] Improve code style and code quality of generated classes
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/AdminList/AdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/Controller/EntityAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/Form/EntityAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/AuthorAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/CategoryAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/PageAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/TagAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/CategoryAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/TagAdminListController.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Author.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Category.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Category.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/OverviewPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Tag.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/AuthorAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/CategoryAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/OverviewPageAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/TagAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Helper/Menu/MenuAdaptor.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/OverviewPageRepository.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/PageRepositoryPartial.php.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/common/Form/EntityAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/entity/Entity.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Entity/Pages/SearchPage.php
Labels: Target audience: Developers, Type: Improvement

#2602 [AllBundles] Fix symfony event class deprecation
  src/Kunstmaan/AdminBundle/Event/AdaptSimpleFormEvent.php
  src/Kunstmaan/AdminBundle/Event/BcEvent.php
  src/Kunstmaan/AdminBundle/Event/DeepCloneAndSaveEvent.php
  src/Kunstmaan/AdminListBundle/Event/AdminListEvent.php
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/FormBundle/Event/SubmissionEvent.php
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/NodeBundle/Event/AdaptFormEvent.php
  src/Kunstmaan/NodeBundle/Event/ConfigureActionMenuEvent.php
  src/Kunstmaan/NodeBundle/Event/NodeEvent.php
  src/Kunstmaan/NodeBundle/Event/SlugEvent.php
  src/Kunstmaan/NodeBundle/Event/SlugSecurityEvent.php
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/Event/IndexNodeEvent.php
  src/Kunstmaan/NodeSearchBundle/composer.json
  src/Kunstmaan/PagePartBundle/Event/PagePartEvent.php
  src/Kunstmaan/PagePartBundle/composer.json
  src/Kunstmaan/VotingBundle/Event/AbstractVoteEvent.php
Labels: Type: Improvement

#2542 [AllBundles] Mark classes extending twig final
  UPGRADE-5.4.md
  src/Kunstmaan/AdminBundle/Twig/AdminBundleTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/AdminPermissionsTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/AdminRouteHelperTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/DateByLocaleExtension.php
  src/Kunstmaan/AdminBundle/Twig/FormToolsExtension.php
  src/Kunstmaan/AdminBundle/Twig/GoogleSignInTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/LocaleSwitcherTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/MenuTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/SidebarTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/TabsTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/ToolbarTwigExtension.php
  src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
  src/Kunstmaan/ArticleBundle/Twig/ArticleTwigExtension.php
  src/Kunstmaan/ConfigBundle/Twig/ConfigTwigExtension.php
  src/Kunstmaan/LeadGenerationBundle/Twig/PopupTwigExtension.php
  src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php
  src/Kunstmaan/MultiDomainBundle/Twig/MultiDomainTwigExtension.php
  src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
  src/Kunstmaan/NodeBundle/Twig/PagesConfigurationTwigExtension.php
  src/Kunstmaan/NodeBundle/Twig/UrlReplaceTwigExtension.php
  src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
  src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartAdminTwigExtension.php
  src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
  src/Kunstmaan/PagePartBundle/Twig/Extension/PageTemplateTwigExtension.php
  src/Kunstmaan/SeoBundle/Twig/GoogleAnalyticsTwigExtension.php
  src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
  src/Kunstmaan/SitemapBundle/Twig/SitemapTwigExtension.php
  src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
Labels: Target audience: Developers, Type: Improvement

#2524 [AllBundles] Remove support for unmaintained symfony versions
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Priority: Normal, Target audience: Developers

#2525 [AllBundles] Provide autowire aliases for frequently injected classes
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
  src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
Labels: Target audience: Developers, Type: Improvement

#2522 [SitemapBundle] Allow to include other items in the sitemap
  composer.json
  src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
  src/Kunstmaan/SitemapBundle/Event/PreSitemapRenderEvent.php
  src/Kunstmaan/SitemapBundle/Model/SitemapUrl.php
  src/Kunstmaan/SitemapBundle/Resources/views/Sitemap/view.xml.twig
  src/Kunstmaan/SitemapBundle/Resources/views/SitemapIndex/view.xml.twig
  src/Kunstmaan/SitemapBundle/Tests/unit/Model/SitemapUrlTest.php
  src/Kunstmaan/SitemapBundle/composer.json
Labels: Priority: Normal, Target audience: Developers, Type: Feature

#2466 [AllBundles] Replace internal loadTemplate twig method
  src/Kunstmaan/AdminBundle/Twig/AdminPermissionsTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/LocaleSwitcherTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/TabsTwigExtension.php
  src/Kunstmaan/AdminBundle/Twig/ToolbarTwigExtension.php
  src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
  src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartAdminTwigExtension.php
  src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
  src/Kunstmaan/PagePartBundle/Twig/Extension/PageTemplateTwigExtension.php
  src/Kunstmaan/SeoBundle/Twig/GoogleAnalyticsTwigExtension.php
  src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
Labels: Priority: Normal, Target audience: Developers, Type: Improvement

#2516 [AllBundles] Deprecate old flash "error" type
  UPGRADE-5.4.md
  src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
  src/Kunstmaan/AdminBundle/FlashMessages/FlashTypes.php
  src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
  src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
  src/Kunstmaan/MediaBundle/Controller/FolderController.php
  src/Kunstmaan/MediaBundle/Controller/MediaController.php
Labels: Priority: Normal, Target audience: Administrators, Type: Deprecation, Type: Improvement

#2464 [AdminBundle] Code improvement found by static code analysis
  src/Kunstmaan/AdminBundle/Command/ApplyAclCommand.php
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
  src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
  src/Kunstmaan/AdminBundle/Controller/DefaultController.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Entity/BaseUser.php
  src/Kunstmaan/AdminBundle/Entity/GroupPropertiesTrait.php
  src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
  src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionListener.php
  src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionSubscriber.php
  src/Kunstmaan/AdminBundle/EventListener/ExceptionSubscriber.php
  src/Kunstmaan/AdminBundle/EventListener/SessionSecurityListener.php
  src/Kunstmaan/AdminBundle/Helper/AdminPanel/AdminPanel.php
  src/Kunstmaan/AdminBundle/Helper/AdminRouteHelper.php
  src/Kunstmaan/AdminBundle/Helper/CloneHelper.php
  src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/AdminBundle/Helper/FormHelper.php
  src/Kunstmaan/AdminBundle/Helper/FormWidgets/FormWidget.php
  src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/Tab.php
  src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
  src/Kunstmaan/AdminBundle/Helper/Menu/MenuBuilder.php
  src/Kunstmaan/AdminBundle/Helper/Menu/MenuItem.php
  src/Kunstmaan/AdminBundle/Helper/Menu/ModulesMenuAdaptor.php
  src/Kunstmaan/AdminBundle/Helper/Menu/SettingsMenuAdaptor.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/MaskBuilder.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionDefinition.php
  src/Kunstmaan/AdminBundle/Helper/UserProcessor.php
  src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
  src/Kunstmaan/AdminBundle/Repository/UserRepository.php
  src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
  src/Kunstmaan/AdminBundle/Service/AclManager.php
  src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/KunstmaanAdminExtensionTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Entity/AclChangesetTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Entity/GroupTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Form/MediaTokenTransformerTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/MenuBuilderTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/MenuItemTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/Permission/PermissionAdminTest.php
  src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
  src/Kunstmaan/AdminBundle/Twig/DateByLocaleExtension.php
  src/Kunstmaan/AdminBundle/Validator/Constraints/PasswordRestrictionsValidator.php
Labels: Priority: Normal, Target audience: Developers, Type: Improvement

#2453 [AdminBundle] Deprecate container access in adminbundle classes
  UPGRADE-5.4.md
  src/Kunstmaan/AdminBundle/Helper/Menu/MenuBuilder.php
  src/Kunstmaan/AdminBundle/Helper/UserProcessor.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/MenuBuilderTest.php
  src/Kunstmaan/AdminBundle/Tests/unit/Helper/UserProcessorTest.php
Labels: Priority: Normal, Profile: Backend, Target audience: Developers, Type: Deprecation

#2452 [AdminListBundle] Improve the quality of the phpunit testcases
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/ExportListTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FieldTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterBuilderTest.php
  src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Helper/DoctrineDBALAdapterTest.php
Labels: Priority: Normal, Target audience: Developers, Type: Improvement

#2589 [MenuBundle] added class for menu item with active subnode
  src/Kunstmaan/MenuBundle/Resources/views/menu-item.html.twig
  src/Kunstmaan/MenuBundle/Service/RenderService.php
Labels: Type: Feature

#2580 [AdminBundle] add option to colorpicker to add predefined colors
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/_components.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/vendors/mjolnic-bootstrap-colorpicker/_mjolnic-bootstrap-colorpicker.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/config/_config.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/config/vendors/bootstrap-colorpicker/_bootstrap-colorpicker-imports.scss
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
Labels: Target audience: Administrators, Type: Improvement

#2603 [TranslatorBundle] use the common export logic instead of a custom export
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.de.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.es.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.fr.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.hu.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.it.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/TranslatorBundle/Resources/translations/messages.pl.yml
  src/Kunstmaan/TranslatorBundle/Resources/views/Translator/inline_edit.html.twig
  src/Kunstmaan/TranslatorBundle/Resources/views/Translator/list.html.twig
Labels: Priority: Normal, Type: Feature

#2613 [FormBundle] fix export formsubmissions if pagepart order got changed on the form page
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
Labels: Type: Bugfix

#2614 [FormBundle] previous bugfix to avoid empty rows caused another bug
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
Labels: Type: Bugfix

#2617 [AllBundles] Temporary revert event class BC layer
  src/Kunstmaan/AdminBundle/Event/AdaptSimpleFormEvent.php
  src/Kunstmaan/AdminBundle/Event/BcEvent.php
  src/Kunstmaan/AdminBundle/Event/DeepCloneAndSaveEvent.php
  src/Kunstmaan/AdminListBundle/Event/AdminListEvent.php
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/FormBundle/Event/SubmissionEvent.php
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/NodeBundle/Event/AdaptFormEvent.php
  src/Kunstmaan/NodeBundle/Event/ConfigureActionMenuEvent.php
  src/Kunstmaan/NodeBundle/Event/NodeEvent.php
  src/Kunstmaan/NodeBundle/Event/SlugEvent.php
  src/Kunstmaan/NodeBundle/Event/SlugSecurityEvent.php
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/Event/IndexNodeEvent.php
  src/Kunstmaan/NodeSearchBundle/composer.json
  src/Kunstmaan/PagePartBundle/Event/PagePartEvent.php
  src/Kunstmaan/PagePartBundle/composer.json
  src/Kunstmaan/VotingBundle/Event/AbstractVoteEvent.php
Labels: Type: Bugfix

#2616 [AllBundles] Switch code coverage to latest php + codecoverage speed up
  .travis.yml
Labels: Type: Improvement

#2618 [AdminListBundle] Fixed missing translator property set in constructor
  src/Kunstmaan/AdminListBundle/Service/ExportService.php
Labels: Type: Bugfix

#2588 [PagepartBundle] Fixed not being able to search for translated names of PageParts
  src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/modal.html.twig
Labels: Type: Bugfix

#2615 [AdminBundle] Fix unnecessary collapsing of top-nav when zooming
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.min.js
  src/Kunstmaan/AdminBundle/Resources/ui/js/_app-top-nav.js
Labels: Profile: Frontend, Target audience: Administrators, Type: Bugfix

#2621 [NodeBundle] Always defined the prefix variable
  src/Kunstmaan/NodeBundle/Form/Type/SlugType.php
Labels: Type: Bugfix

#2624 [AllBundles] Fixed remaining template path using the old notation
  src/Kunstmaan/ArticleBundle/AdminList/AbstractArticlePageAdminListConfigurator.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractArticleOverviewPage.php
  src/Kunstmaan/ArticleBundle/Tests/unit/AdminList/AbstractArticlePageAdminListConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/unit/Entity/AbstractArticleOverviewPageTest.php
  src/Kunstmaan/DashboardBundle/Controller/DashboardController.php
  src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
  src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/FileFormSubmissionField.php
  src/Kunstmaan/FormBundle/Entity/PageParts/AbstractFormPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/SubmitButtonPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/KunstmaanSitemapBundle/views/SitemapPage/view.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/AudioPagePart/view.html.twig
  src/Kunstmaan/LeadGenerationBundle/AdminList/PopupAdminListConfigurator.php
  src/Kunstmaan/LeadGenerationBundle/AdminList/RulesAdminListConfigurator.php
  src/Kunstmaan/LeadGenerationBundle/Controller/AbstractNewsletterController.php
  src/Kunstmaan/LeadGenerationBundle/Controller/AbstractRedirectController.php
  src/Kunstmaan/LeadGenerationBundle/Resources/views/Newsletter/index.html.twig
  src/Kunstmaan/LeadGenerationBundle/Twig/PopupTwigExtension.php
  src/Kunstmaan/MediaPagePartBundle/Entity/AudioPagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/DownloadPagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/ImagePagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/SlidePagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/VideoPagePart.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/AudioPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/DownloadPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/ImagePagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/SlidePagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/unit/Entity/VideoPagePartTest.php
  src/Kunstmaan/MenuBundle/AdminList/MenuItemAdminListConfigurator.php
  src/Kunstmaan/MenuBundle/Service/RenderService.php
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
  src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
  src/Kunstmaan/NodeSearchBundle/Entity/AbstractSearchPage.php
  src/Kunstmaan/NodeSearchBundle/Tests/unit/Entity/AbstractSearchPageTest.php
  src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
  src/Kunstmaan/PagePartBundle/Entity/HeaderPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/LinePagePart.php
  src/Kunstmaan/PagePartBundle/Entity/LinkPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/RawHTMLPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/TextPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/ToTopPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/TocPagePart.php
  src/Kunstmaan/PagePartBundle/Resources/views/TocPagePart/view.html.twig
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/HeaderPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/LinePagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/LinkPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/RawHTMLPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/TextPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/ToTopPagePartTest.php
  src/Kunstmaan/PagePartBundle/Tests/unit/Entity/TocPagePartTest.php
  src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
  src/Kunstmaan/SitemapBundle/Entity/SitemapPage.php
  src/Kunstmaan/SitemapBundle/Resources/views/Sitemap/entry.xml.twig
  src/Kunstmaan/SitemapBundle/Tests/unit/Entity/SiteMapPageTest.php
  src/Kunstmaan/VotingBundle/Controller/VotingController.php
Labels: Priority: High, Type: Bugfix

#2629 [NodeBundle] Fix php 7.4 incompatibilities in the url chooser
  src/Kunstmaan/AdminBundle/Helper/DomainConfigurationInterface.php
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
  src/Kunstmaan/NodeBundle/Helper/URLHelper.php
Labels: Type: Bugfix
