Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2021-03, with the labels that each got.

#2851 [GeneratorBundle] Fix php syntax errors in generator skeleton files
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/PageBannerPagePartAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/ServicePagePartAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/UspPagePartAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/UspItemAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/AudioPagePart/AudioPagePartAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/DownloadPagePart/DownloadPagePartAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ImagePagePart/ImagePagePartAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/VideoPagePart/VideoPagePartAdminType.php
  src/Kunstmaan/NodeBundle/Command/CronUpdateNodeCommand.php
Labels: Type: Bugfix

#2854 [AllBundles] Setup deprecations baseline
  .build/deprecations-baseline.json
  .github/workflows/ci.yml
  composer.json
Labels: Type: Improvement

#2847 [MediaBundle] Bump imagine dependencies
  composer.json
  src/Kunstmaan/MediaBundle/Helper/Imagine/CacheManager.php
  src/Kunstmaan/MediaBundle/composer.json
Labels: Type: Improvement

#2845 [NodeBundle] fixed unpublish later
  src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_unpublish.html.twig
Labels: Type: Bugfix

#2849 [All bundles] added postgres support
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclWalker.php
  src/Kunstmaan/AdminBundle/Repository/ExceptionRepository.php
  src/Kunstmaan/AdminBundle/Repository/UserRepository.php
  src/Kunstmaan/AdminBundle/Resources/doc/Permissions.md
  src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclHelperTest.php
  src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclNativeHelperTest.php
  src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclWalkerTest.php
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractPageAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/Helper/DoctrineDBALAdapter.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Configurator/AbstractDoctrineDBALAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Helper/DoctrineDBALAdapterTest.php
  src/Kunstmaan/ArticleBundle/AdminList/AbstractArticlePageAdminListConfigurator.php
  src/Kunstmaan/ArticleBundle/Repository/AbstractArticleOverviewPageRepository.php
  src/Kunstmaan/ArticleBundle/Tests/Repository/AbstractArticleOverviewPageRepositoryTest.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Category.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Category.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Tag.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/PageRepositoryPartial.php.twig
  src/Kunstmaan/MediaBundle/AdminList/MediaAdminListConfigurator.php
  src/Kunstmaan/MediaBundle/Repository/FolderRepository.php
  src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
  src/Kunstmaan/MenuBundle/Repository/MenuItemRepository.php
  src/Kunstmaan/NodeBundle/AdminList/NodeAdminListConfigurator.php
  src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php
  src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
  src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
  src/Kunstmaan/TaggingBundle/Entity/TagManager.php
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
  src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
Labels: Type: Feature

#2855 [AllBundles] Bump minimum stof/doctrine-extensions-bundle version
  composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
Labels: Type: Improvement
