Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2021-04, with the labels that each got.

#2848 [MultiDomainBundle] Fix keying of host configurations
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/MultiDomainBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/DependencyInjection/KunstmaanMultiDomainExtensionTest.php
Labels: Type: Bugfix

#2856 [RedirectBundle] Fix broken wildcard redirects
  src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
  src/Kunstmaan/RedirectBundle/Tests/Router/RedirectRouterTest.php
Labels: Type: Bugfix

#2865 [GeneratorBundle] Switch to new doctrine inflector api
  composer.json
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
  src/Kunstmaan/GeneratorBundle/composer.json
Labels: Type: Improvement

#2866 [AdminlistBundle] Deprecate setter methods in EntityVersionLockService
  UPGRADE-5.9.md
  src/Kunstmaan/AdminListBundle/Service/EntityVersionLockService.php
  src/Kunstmaan/AdminListBundle/Tests/Service/EntityVersionLockServiceTest.php
Labels: Type: Deprecation, Type: Improvement

#2862 [NodeSearchBundle] Deprecate direct instantiation of the abstractSearchPage
  UPGRADE-5.9.md
  src/Kunstmaan/NodeSearchBundle/Entity/AbstractSearchPage.php
  src/Kunstmaan/NodeSearchBundle/Tests/Entity/AbstractSearchPageTest.php
Labels: Type: Deprecation

#2863 [Dashboardbundle] Rework dashboard command calls
  UPGRADE-5.9.md
  src/Kunstmaan/DashboardBundle/Command/DashboardCommand.php
  src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsAJAXController.php
  src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
  src/Kunstmaan/DashboardBundle/Resources/config/services.yml
  src/Kunstmaan/DashboardBundle/Tests/DependencyInjection/KunstmaanDashboardExtensionTest.php
  src/Kunstmaan/DashboardBundle/Tests/Widget/DashboardWidgetTest.php
  src/Kunstmaan/DashboardBundle/Widget/DashboardWidget.php
Labels: Type: Deprecation, Type: Improvement

#2860 [UserManagementBundle] Move user adminlist configurator class override to config
  UPGRADE-5.9.md
  src/Kunstmaan/UserManagementBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/UserManagementBundle/DependencyInjection/KunstmaanUserManagementExtension.php
  src/Kunstmaan/UserManagementBundle/Resources/config/services.yml
  src/Kunstmaan/UserManagementBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/UserManagementBundle/Tests/DependencyInjection/KunstmaanUserManagementExtensionTest.php
Labels: Type: Deprecation, Type: Feature

#2861 [AllBundles] Mark event classes final
  UPGRADE-5.9.md
  src/Kunstmaan/AdminBundle/Event/AdaptSimpleFormEvent.php
  src/Kunstmaan/AdminBundle/Event/DeepCloneAndSaveEvent.php
  src/Kunstmaan/AdminBundle/Event/Events.php
  src/Kunstmaan/AdminListBundle/Event/AdminListEvent.php
  src/Kunstmaan/AdminListBundle/Event/AdminListEvents.php
  src/Kunstmaan/FormBundle/Event/SubmissionEvent.php
  src/Kunstmaan/NodeBundle/Event/AdaptFormEvent.php
  src/Kunstmaan/NodeBundle/Event/ConfigureActionMenuEvent.php
  src/Kunstmaan/NodeBundle/Event/CopyPageTranslationNodeEvent.php
  src/Kunstmaan/NodeBundle/Event/Events.php
  src/Kunstmaan/NodeBundle/Event/RecopyPageTranslationNodeEvent.php
  src/Kunstmaan/NodeBundle/Event/RevertNodeAction.php
  src/Kunstmaan/NodeBundle/Event/SlugEvent.php
  src/Kunstmaan/NodeSearchBundle/Event/IndexNodeEvent.php
  src/Kunstmaan/PagePartBundle/Event/Events.php
  src/Kunstmaan/PagePartBundle/Event/PagePartEvent.php
  src/Kunstmaan/UserManagementBundle/Event/UserEvents.php
  src/Kunstmaan/VotingBundle/Event/Events.php
  src/Kunstmaan/VotingBundle/Event/Facebook/FacebookLikeEvent.php
  src/Kunstmaan/VotingBundle/Event/Facebook/FacebookSendEvent.php
  src/Kunstmaan/VotingBundle/Event/LinkedIn/LinkedInShareEvent.php
  src/Kunstmaan/VotingBundle/Event/UpDown/DownVoteEvent.php
  src/Kunstmaan/VotingBundle/Event/UpDown/UpVoteEvent.php
Labels: Type: Improvement
