Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2021-05, with the labels that each got.

#2864 [GeneratorBundle] Deprecate generate bundle and entity commands
  UPGRADE-5.9.md
  src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateEntityCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/BundleGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/DefaultEntityGenerator.php
Labels: Type: Deprecation

#2859 [RedirectBundle] Move redirect entity class override to config
  UPGRADE-5.9.md
  src/Kunstmaan/RedirectBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/RedirectBundle/DependencyInjection/KunstmaanRedirectExtension.php
  src/Kunstmaan/RedirectBundle/Resources/config/services.yml
  src/Kunstmaan/RedirectBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/RedirectBundle/Tests/DependencyInjection/KunstmaanRedirectExtensionTest.php
Labels: Type: Deprecation, Type: Feature

#2857 [AdminBundle] Add config option to disabled exception logging module
  UPGRADE-5.9.md
  src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Helper/Menu/SettingsMenuAdaptor.php
  src/Kunstmaan/AdminBundle/Resources/config/console_listener.yml
  src/Kunstmaan/AdminBundle/Resources/views/Toolbar/exception.html.twig
  src/Kunstmaan/AdminBundle/Tests/DependencyInjection/ConfigurationTest.php
Labels: Type: Deprecation, Type: Feature

#2782 [MediaBundle] Use parameter instead of hardcoded media path
  UPGRADE-5.9.md
  src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
  src/Kunstmaan/MediaBundle/Helper/File/FileHelper.php
  src/Kunstmaan/MediaBundle/Tests/Helper/File/FileHelperTest.php
Labels: Type: Feature

#2875 [FormBundle] Add length validation to form fields
  src/Kunstmaan/FormBundle/Entity/PageParts/AbstractFormPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/SubmitButtonPagePart.php
  src/Kunstmaan/FormBundle/Form/CheckboxPagePartAdminType.php
  src/Kunstmaan/FormBundle/Form/ChoicePagePartAdminType.php
  src/Kunstmaan/FormBundle/Form/FileUploadPagePartAdminType.php
  src/Kunstmaan/FormBundle/Form/MultiLineTextPagePartAdminType.php
  src/Kunstmaan/FormBundle/Form/SingleLineTextPagePartAdminType.php
  src/Kunstmaan/FormBundle/Tests/Form/CheckboxPagePartAdminTypeTest.php
  src/Kunstmaan/FormBundle/Tests/Form/FileUploadPagePartAdminTypeTest.php
  src/Kunstmaan/FormBundle/Tests/Form/MultiLineTextPagePartAdminTypeTest.php
  src/Kunstmaan/FormBundle/Tests/Form/SingleLineTextPagePartAdminTypeTest.php
Labels: Type: Bugfix

#2773 [AdminListBundle] Change pagerfanta dependencies to require the minimum needed packages
  UPGRADE-5.9.md
  composer.json
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/PagerfantaBridgePass.php
  src/Kunstmaan/AdminBundle/DependencyInjection/PagerfantaConfiguration.php
  src/Kunstmaan/AdminBundle/DependencyInjection/PagerfantaExtension.php
  src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
  src/Kunstmaan/AdminBundle/Tests/DependencyInjection/Compiler/PagerfantaBridgePassTest.php
  src/Kunstmaan/AdminBundle/Tests/DependencyInjection/PagerfantaExtensionTest.php
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Helper/DoctrineDBALAdapterTest.php
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/ArticleBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/composer.json
Labels: Type: Improvement

#2876 [AllBundles] Forward compatibility fixes for symfony 5
  src/Kunstmaan/AdminBundle/Tests/EventListener/AdminLocaleListenerTest.php
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
  src/Kunstmaan/MultiDomainBundle/EventListener/HostOverrideListener.php
  src/Kunstmaan/MultiDomainBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/EventListener/HostOverrideListenerTest.php
  src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
Labels: Type: Improvement

#2877 [DashboardBundle] Deprecate remaining container usages in command
  UPGRADE-5.9.md
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
  src/Kunstmaan/DashboardBundle/Resources/config/commands.yml
Labels: Type: Deprecation
