Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2021-07, with the labels that each got.

#2895 [TranslatorBundle] Increase max length for translation domain
  src/Kunstmaan/TranslatorBundle/Entity/Translation.php
Labels: Type: Improvement

#2891 [MediaBundle] Use oembed url for vimeo thumbnail
  src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php
Labels: Type: Bugfix

#2892 [AllBundles] Update sortablejs back to 1.8.1
  package.json
Labels: Type: Bugfix

#2900 [AllBundles] Fix phpstan errors for checks added in 0.12.92
  phpstan.neon
  src/Kunstmaan/AdminBundle/Entity/BaseUser.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
  src/Kunstmaan/RedirectBundle/Entity/Redirect.php
Labels: Type: Improvement

#2902 [AllBundles] Fix branch alias of separate packages
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/ArticleBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/CacheBundle/composer.json
  src/Kunstmaan/ConfigBundle/composer.json
  src/Kunstmaan/DashboardBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/GeneratorBundle/composer.json
  src/Kunstmaan/LeadGenerationBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/MediaPagePartBundle/composer.json
  src/Kunstmaan/MenuBundle/composer.json
  src/Kunstmaan/MultiDomainBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/composer.json
  src/Kunstmaan/PagePartBundle/composer.json
  src/Kunstmaan/RedirectBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/SeoBundle/composer.json
  src/Kunstmaan/SitemapBundle/composer.json
  src/Kunstmaan/TaggingBundle/composer.json
  src/Kunstmaan/TranslatorBundle/composer.json
  src/Kunstmaan/UserManagementBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Feature

#2904 [AllBundles] Backport phpstan 0.12.92 fixes
  phpstan.neon
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
  src/Kunstmaan/RedirectBundle/Entity/Redirect.php
Labels: Type: Improvement

#2899 [AllBundles] Fix doctrine common deprecations and resolve doctrine bundle v2 incompatibility
  composer.json
  src/Kunstmaan/AdminBundle/Service/GroupManager.php
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
  src/Kunstmaan/AdminListBundle/Controller/EntityLockCheckController.php
  src/Kunstmaan/AdminListBundle/Service/EntityVersionLockService.php
  src/Kunstmaan/AdminListBundle/Tests/Service/EntityVersionLockServiceTest.php
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/FixturesBundle/Builder/BuildingSupervisor.php
  src/Kunstmaan/FixturesBundle/Loader/FixtureLoader.php
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/GroupFixtures.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/RoleFixtures.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
  src/Kunstmaan/GeneratorBundle/Generator/ArticleGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/ConfigGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/Symfony4EntityRepositoryGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/OverviewPage.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/SitemapFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/DataFixtures/ORM/SearchPageGenerator/SearchFixtures.php
  src/Kunstmaan/GeneratorBundle/composer.json
  src/Kunstmaan/MediaBundle/DataFixtures/ORM/FolderFixtures.php
  src/Kunstmaan/MediaBundle/Form/Type/IdToMediaTransformer.php
  src/Kunstmaan/MediaBundle/Form/Type/MediaType.php
  src/Kunstmaan/MediaBundle/Tests/Form/AbstractTypeTest.php
  src/Kunstmaan/MediaBundle/Tests/Helper/FolderManagerTest.php
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
  src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeVersionLockHelper.php
  src/Kunstmaan/NodeBundle/Tests/Helper/NodeHelperTest.php
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/PagePartBundle/Tests/Form/PagePartAdminTypeTestCase.php
  src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
  src/Kunstmaan/RedirectBundle/Tests/Router/RedirectRouterTest.php
  src/Kunstmaan/RedirectBundle/composer.json
  src/Kunstmaan/TranslatorBundle/DataFixtures/ORM/TranslationFixtures.php
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement

#2901 [AllBundle] Replace abanoned faker package
  UPGRADE-5.9.md
  composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/GeneratorBundle/composer.json
  src/Kunstmaan/TranslatorBundle/Tests/Fixtures/TranslationDataFixture.php
  src/Kunstmaan/TranslatorBundle/Tests/WebTestCase.php
  src/Kunstmaan/TranslatorBundle/composer.json
Labels: Type: Improvement

#2897 [AllBundles] Bump gedmo/doctrine-extensions to prepare for php8 support
  composer.json
  src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclWalkerTest.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
Labels: Type: Improvement

#2907 [AdminBundle] Fix redirect loop for installation without new authentication setup
  src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
Labels: Type: Bugfix

#2908 [NodeSearchBundle] Add missing deprecation for change in searcher lookup
  src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
Labels: Type: Deprecation, Type: Improvement

#2909 [AdminBundle] Fix remaining usages of deprecated admin_exception_excludes config
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Tests/DependencyInjection/KunstmaanAdminExtensionTest.php
Labels: Type: Deprecation, Type: Improvement

#2910 [AdminBundle] Fix symfony/security-acl 3.2 test errors
  src/Kunstmaan/AdminBundle/Tests/Helper/Creators/ACLPermissionCreatorTest.php
Labels: Type: Bugfix, Type: Improvement

#2888 [AdminBundle] New login styling
  src/Kunstmaan/AdminBundle/Form/Authentication/NewPasswordType.php
  src/Kunstmaan/AdminBundle/Form/Authentication/PasswordRequestType.php
  src/Kunstmaan/AdminBundle/Resources/public/css/style.css
  src/Kunstmaan/AdminBundle/Resources/public/cssnext/style.css
  src/Kunstmaan/AdminBundle/Resources/public/default-theme/img/kunstmaan/default-login-bg.jpg
  src/Kunstmaan/AdminBundle/Resources/public/default-theme/img/kunstmaan/logo-cms-color.svg
  src/Kunstmaan/AdminBundle/Resources/public/img/general/logo_kunstmaan_cms.png
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js
  src/Kunstmaan/AdminBundle/Resources/public/js/admin-bundle.next.js.map
  src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
  src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml
  src/Kunstmaan/AdminBundle/Resources/ui/img/authentication/btn_google_signin_light_normal_web.png
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/01-quarks/_colors.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/02-atoms/_all.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/02-atoms/_buttons.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/02-atoms/forms/_all.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/02-atoms/forms/_form-control.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/02-atoms/forms/_form-group.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/03-molecules/_all.scss
  src/Kunstmaan/AdminBundle/Resources/ui/scssnext/03-molecules/_login.scss
  src/Kunstmaan/AdminBundle/Resources/views/Default/_css.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/authentication/email/password_reset.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/authentication/forced_change_password/form.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/authentication/forced_change_password/success.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/authentication/layout.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/authentication/login.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/authentication/password_reset/confirm.twig
  src/Kunstmaan/AdminBundle/Resources/views/authentication/password_reset/request.html.twig
  src/Kunstmaan/AdminBundle/Service/AuthenticationMailer/SwiftmailerService.php
  src/Kunstmaan/AdminBundle/Service/AuthenticationMailer/SymfonyMailerService.php
  src/Kunstmaan/DashboardBundle/Resources/public/css/dashboard.css
  src/Kunstmaan/TranslatorBundle/Resources/public/css/style.css
Labels: Type: Feature

#2912 [AdminBundle] Finish version checker deprecations
  .gitignore
  UPGRADE-5.9.md
  src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Tests/Helper/VersionCheck/VersionCheckTest.php
  src/Kunstmaan/AdminBundle/Tests/Helper/VersionCheck/testdata/composer_broken/composer.lock
  src/Kunstmaan/AdminBundle/Tests/Helper/VersionCheck/testdata/composer_bundleless/composer.lock
  src/Kunstmaan/AdminBundle/Tests/Helper/VersionCheck/testdata/composer_ok/composer.lock
Labels: Type: Deprecation, Type: Improvement

#2911 [TranslatorBundle] Remove forced import from admin interface
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
  src/Kunstmaan/TranslatorBundle/Resources/views/Translator/list.html.twig
Labels: Type: Feature, Type: Improvement

#2913 [AdminBundle] Remove deprecated code from version collector classes
  src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
  src/Kunstmaan/AdminBundle/Tests/Helper/VersionCheck/VersionCheckTest.php
  src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
Labels: Type: BC break
