Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2022-10, with the labels that each got.

#3169 [AllBundles] Replace old doctrine entity notations with fqcn
  src/Kunstmaan/AdminBundle/Resources/doc/Permissions.md
  src/Kunstmaan/CookieBundle/AdminList/CookieAdminListConfigurator.php
  src/Kunstmaan/CookieBundle/Helper/LegalCookieHelper.php
  src/Kunstmaan/CookieBundle/Resources/skeleton/legal/DataFixtures/ORM/LegalGenerator/DefaultFixtures.php
  src/Kunstmaan/CookieBundle/Twig/CookieTwigExtension.php
  src/Kunstmaan/FormBundle/Helper/FormHandler.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/SitemapFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/DataFixtures/ORM/SearchPageGenerator/SearchFixtures.php
  src/Kunstmaan/MediaBundle/Helper/Services/MediaCreatorService.php
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
  src/Kunstmaan/NodeBundle/Helper/PageCloningHelper.php
  src/Kunstmaan/NodeBundle/Resources/doc/ProgrammaticallyCreateNodes.md
  src/Kunstmaan/TaggingBundle/Entity/TagManager.php
  src/Kunstmaan/TaggingBundle/EventListener/CloneListener.php
  src/Kunstmaan/TranslatorBundle/DataFixtures/ORM/TranslationFixtures.php
  src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
  src/Kunstmaan/TranslatorBundle/Service/Migrations/MigrationsService.php
  src/Kunstmaan/VotingBundle/Services/RepositoryResolver.php
Labels: Type: Improvement

#3171 [AllBundles] Move dependency to correct bundle
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
Labels: Type: Improvement

#3175 [GeneratorBundle] Improve return types in generated files
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/AdminList/AdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/Form/EntityAdminType.php
Labels: Type: Improvement

#3176 [AllBundles] Drop symfony 4 support and remove BC layers
  .github/workflows/ci.yml
  composer.json
  src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/AdminBundle/Entity/Role.php
  src/Kunstmaan/AdminBundle/Entity/RolePropertiesTrait.php
  src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
  src/Kunstmaan/AdminBundle/EventListener/ExceptionSubscriber.php
  src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
  src/Kunstmaan/AdminBundle/EventListener/SessionSecurityListener.php
  src/Kunstmaan/AdminBundle/EventListener/ToolbarListener.php
  src/Kunstmaan/AdminBundle/Helper/CloneHelper.php
  src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
  src/Kunstmaan/AdminBundle/Helper/EventdispatcherCompatibilityUtil.php
  src/Kunstmaan/AdminBundle/Service/PasswordResetService.php
  src/Kunstmaan/AdminBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/AdminBundle/Tests/EventListener/AdminLocaleListenerTest.php
  src/Kunstmaan/AdminBundle/Tests/EventListener/PasswordCheckListenerTest.php
  src/Kunstmaan/AdminBundle/Tests/EventListener/SessionSecurityListenerTest.php
  src/Kunstmaan/AdminBundle/Tests/Helper/AdminPanel/DefaultAdminPanelAdapterTest.php
  src/Kunstmaan/AdminBundle/Tests/Helper/DomainConfigurationTest.php
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/Controller/AbstractAdminListController.php
  src/Kunstmaan/ArticleBundle/ViewDataProvider/ArticlePageViewDataProvider.php
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/CookieBundle/EventSubscriber/CookieBarEventSubscriber.php
  src/Kunstmaan/CookieBundle/ViewDataProvider/LegalPageViewDataProvider.php
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/Helper/FormHandler.php
  src/Kunstmaan/FormBundle/ViewDataProvider/FormPageViewDataProvider.php
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/GeneratorBundle/Generator/ArticleGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/ViewDataProvider/PageViewDataProvider.php
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/MultiDomainBundle/EventListener/HostOverrideListener.php
  src/Kunstmaan/MultiDomainBundle/Tests/EventListener/HostOverrideListenerTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/Helper/DomainConfigurationTest.php
  src/Kunstmaan/MultiDomainBundle/Tests/Router/DomainBasedLocaleRouterTest.php
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
  src/Kunstmaan/NodeBundle/Controller/SlugController.php
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
  src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
  src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
  src/Kunstmaan/NodeBundle/Helper/NodeHelper.php
  src/Kunstmaan/NodeBundle/Helper/PageCloningHelper.php
  src/Kunstmaan/NodeBundle/Router/SlugRouter.php
  src/Kunstmaan/NodeBundle/Tests/Router/SlugRouterTest.php
  src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
  src/Kunstmaan/NodeSearchBundle/ViewDataProvider/SearchPageViewDataProvider.php
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/Controller/VotingController.php
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Feature, Type: Improvement

#3177 [AdminBundle] Enable automatic password upgrades by symfony security/hashers
  src/Kunstmaan/AdminBundle/Entity/BaseUser.php
  src/Kunstmaan/AdminBundle/Repository/UserRepository.php
Labels: Type: Feature

#3178 [AdminBundle] Fix current request check for forwarded error page requests
  src/Kunstmaan/AdminBundle/Helper/AdminRouteHelper.php
  src/Kunstmaan/AdminBundle/Tests/Helper/AdminRouteHelperTest.php
Labels: Type: Bugfix

#3173 [AdminBundle] AsMenuAdaptor attribute to easily define menu adaptors with custom priorities
  src/Kunstmaan/AdminBundle/Attribute/AsMenuAdaptor.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
Labels: Type: Feature

#3179 [GeneratorBundle] Make other cms bundles optional
  src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/PagePartGenerator.php
  src/Kunstmaan/GeneratorBundle/composer.json
Labels: Type: Improvement

#3180 [AllBundles] Replace old style doctrine entity notation by fqcn
  src/Kunstmaan/AdminBundle/Form/GroupType.php
  src/Kunstmaan/AdminBundle/Form/UserType.php
  src/Kunstmaan/AdminBundle/Repository/UserRepository.php
  src/Kunstmaan/ArticleBundle/Repository/AbstractArticleOverviewPageRepository.php
  src/Kunstmaan/DashboardBundle/Repository/AnalyticsSegmentRepository.php
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
  src/Kunstmaan/MediaBundle/Form/AbstractRemoteType.php
  src/Kunstmaan/MediaBundle/Form/File/FileType.php
  src/Kunstmaan/MediaBundle/Form/FolderType.php
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
  src/Kunstmaan/PagePartBundle/Resources/config/services.yml
  src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
  src/Kunstmaan/VotingBundle/Helper/Facebook/FacebookLikeHelper.php
  src/Kunstmaan/VotingBundle/Helper/Facebook/FacebookSendHelper.php
  src/Kunstmaan/VotingBundle/Helper/LinkedIn/LinkedInShareHelper.php
  src/Kunstmaan/VotingBundle/Helper/UpDown/DownVoteHelper.php
  src/Kunstmaan/VotingBundle/Helper/UpDown/UpVoteHelper.php
Labels: Type: Improvement

#3181 [Dashboardbundle] Explicit int cast to avoid php 8.1 warning
  src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/MetricsCommandHelper.php
Labels: Type: Bugfix

#3155 [AdminlistBundle][TranslatorBundle] fix box/spout deprecated in favour of openspout/openspout
  composer.json
  src/Kunstmaan/AdminListBundle/Service/ExportService.php
  src/Kunstmaan/AdminListBundle/Tests/Service/ExportServiceTest.php
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
  src/Kunstmaan/TranslatorBundle/composer.json
Labels: Type: Improvement

#3185 [AllBundles] Codestyle fixes
  src/Kunstmaan/AdminBundle/Event/AdaptSimpleFormEvent.php
  src/Kunstmaan/AdminBundle/Helper/Toolbar/AbstractDataCollector.php
  src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/GoalCommandHelper.php
  src/Kunstmaan/FixturesBundle/Parser/Property/PropertyParserInterface.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
  src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
  src/Kunstmaan/GeneratorBundle/Helper/GeneratorUtils.php
  src/Kunstmaan/GeneratorBundle/Helper/InputAssistant.php
  src/Kunstmaan/NodeBundle/Event/AdaptFormEvent.php
  src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
  src/Kunstmaan/PagePartBundle/PageTemplate/PageTemplateConfigurationParser.php
  src/Kunstmaan/PagePartBundle/PageTemplate/PageTemplateConfigurationParserInterface.php
  src/Kunstmaan/SearchBundle/Provider/SearchProviderInterface.php
  src/Kunstmaan/SeoBundle/Helper/Order.php
  src/Kunstmaan/SeoBundle/Helper/OrderItem.php
  src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
  src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
  src/Kunstmaan/TaggingBundle/Entity/Tag.php
  src/Kunstmaan/TaggingBundle/Entity/TagManager.php
  src/Kunstmaan/TaggingBundle/Entity/Tagging.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
  src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/ExportCommandHandler.php
  src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
  src/Kunstmaan/UtilitiesBundle/Helper/Cipher/CipherInterface.php
  src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
Labels: Type: Improvement

#3184 [FormBundle] Fix incorrect field name in column attribute
  src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php
Labels: Type: Bugfix

#3186 [AllBundles] Enable dependabot to update the used github action versions
  .github/dependabot.yml
Labels: Type: Improvement

#3192 [NodeBundle] Fix retreiving the page type for both post and get requests with query string
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
Labels: Type: Bugfix

#3193 [AllBundles] Add php 8.2 to build matrix
  .github/workflows/ci.yml
  src/Kunstmaan/AdminBundle/Tests/Helper/FormWidgets/ListWidgetTest.php
  src/Kunstmaan/TranslatorBundle/Tests/Service/Translator/LoaderTest.php
Labels: Type: Improvement

#3199 [NodeBundle] Register gemdo tree listener to let bundle work without media bundle
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
Labels: Type: Improvement

#3201 [MediaBundle] Fix pdf handler priority override of parent service value
  src/Kunstmaan/MediaBundle/Helper/File/PdfHandler.php
  src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
Labels: Type: Bugfix
