Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2022-11, with the labels that each got.

#3211 [AllBundles] Move command defintion to AsCommand attribute to prepare symfony 6 support
  src/Kunstmaan/AdminBundle/Command/ApplyAclCommand.php
  src/Kunstmaan/AdminBundle/Command/ChangePasswordCommand.php
  src/Kunstmaan/AdminBundle/Command/CreateGroupCommand.php
  src/Kunstmaan/AdminBundle/Command/CreateRoleCommand.php
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
  src/Kunstmaan/AdminBundle/Command/ExceptionCommand.php
  src/Kunstmaan/AdminBundle/Command/PromoteUserCommand.php
  src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
  src/Kunstmaan/DashboardBundle/Command/DashboardCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigFlushCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigsListCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataFlushCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsListCommand.php
  src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsSegmentsListCommand.php
  src/Kunstmaan/MediaBundle/Command/CleanDeletedMediaCommand.php
  src/Kunstmaan/MediaBundle/Command/CreatePdfPreviewCommand.php
  src/Kunstmaan/MediaBundle/Command/RebuildFolderTreeCommand.php
  src/Kunstmaan/MediaBundle/Command/RenameSoftDeletedCommand.php
  src/Kunstmaan/NodeBundle/Command/CronUpdateNodeCommand.php
  src/Kunstmaan/NodeBundle/Command/InitAclCommand.php
  src/Kunstmaan/SearchBundle/Command/DeleteIndexCommand.php
  src/Kunstmaan/SearchBundle/Command/PopulateIndexCommand.php
  src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
  src/Kunstmaan/TranslatorBundle/Command/ExportTranslationsCommand.php
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
  src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsFromFileCommand.php
  src/Kunstmaan/TranslatorBundle/Command/TranslationCacheCommand.php
  src/Kunstmaan/TranslatorBundle/Command/TranslationFlagCommand.php
  src/Kunstmaan/UtilitiesBundle/Command/CipherCommand.php
Labels: sf6-compatibility

#3213 [AllBundles] General fixes
  src/Kunstmaan/AdminBundle/Helper/Toolbar/AbstractDataCollector.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
Labels: Type: Improvement

#3216 [AdminBundle] Add support for form help text in fields
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
Labels: Type: Feature

#3215 [UtilitiesBundle] Deprecate custom new relic naming strategy
  UPGRADE-6.3.md
  src/Kunstmaan/UtilitiesBundle/Helper/UrlTransactionNamingStrategy.php
  src/Kunstmaan/UtilitiesBundle/Tests/Helper/UrlTransactionNamingStrategyTest.php
Labels: Type: Deprecation

#3220 [SeoBundle] Fix saving robots
  src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
Labels: Type: Bugfix

#3222 [BehatBundle] Fix php version requirement
  src/Kunstmaan/BehatBundle/composer.json
Labels: Type: Bugfix

#3223 [BehatBundle] Fix php version requirement
  src/Kunstmaan/BehatBundle/composer.json
Labels: Type: Bugfix

#3225 Store original url so images have the correct url when previewing in editor
  src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
Labels: Type: Bugfix
