Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2022-03, with the labels that each got.

#3079 [AdminBundle] Add php8 attribute support in entities
  src/Kunstmaan/AdminBundle/Entity/AbstractEntity.php
  src/Kunstmaan/AdminBundle/Entity/AclChangeset.php
  src/Kunstmaan/AdminBundle/Entity/BaseUser.php
  src/Kunstmaan/AdminBundle/Entity/DashboardConfiguration.php
  src/Kunstmaan/AdminBundle/Entity/Exception.php
  src/Kunstmaan/AdminBundle/Entity/Group.php
  src/Kunstmaan/AdminBundle/Entity/Role.php
  src/Kunstmaan/AdminBundle/Entity/RolePropertiesTrait.php
  src/Kunstmaan/AdminBundle/Entity/User.php
Labels: Type: Feature

#3081 [ArticleBundle] Add php8 attribute support in entities
  src/Kunstmaan/ArticleBundle/Entity/AbstractArticlePage.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractAuthor.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractCategory.php
  src/Kunstmaan/ArticleBundle/Entity/AbstractTag.php
Labels: Type: Feature

#3082 [DashboardBundle] Add php8 attribute support in entities
  src/Kunstmaan/DashboardBundle/Entity/AnalyticsConfig.php
  src/Kunstmaan/DashboardBundle/Entity/AnalyticsGoal.php
  src/Kunstmaan/DashboardBundle/Entity/AnalyticsOverview.php
  src/Kunstmaan/DashboardBundle/Entity/AnalyticsSegment.php
Labels: Type: Feature

#3083 [FormBundle] Add php8 attribute support in entities
  src/Kunstmaan/FormBundle/Entity/AbstractFormPage.php
  src/Kunstmaan/FormBundle/Entity/FormSubmission.php
  src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php
  src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/BooleanFormSubmissionField.php
  src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/ChoiceFormSubmissionField.php
  src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/EmailFormSubmissionField.php
  src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/FileFormSubmissionField.php
  src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/StringFormSubmissionField.php
  src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/TextFormSubmissionField.php
  src/Kunstmaan/FormBundle/Entity/PageParts/AbstractFormPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/SubmitButtonPagePart.php
Labels: Type: Feature

#3084 [CookieBundle] Add php8 attribute support in entities
  src/Kunstmaan/CookieBundle/Entity/Cookie.php
  src/Kunstmaan/CookieBundle/Entity/CookieConfig.php
  src/Kunstmaan/CookieBundle/Entity/CookieLog.php
  src/Kunstmaan/CookieBundle/Entity/CookieType.php
Labels: Type: Feature

#3085 [LeadGenerationBundle] Add php8 attribute support in entities
  src/Kunstmaan/LeadGenerationBundle/Entity/Popup/AbstractPopup.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/AbstractRule.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/AfterXScrollPercentRule.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/AfterXSecondsRule.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/LocaleBlacklistRule.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/LocaleWhitelistRule.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/MaxXTimesRule.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/OnExitIntentRule.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/RecurringEveryXTimeRule.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/UrlBlacklistRule.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/UrlWhitelistRule.php
Labels: Type: Feature

#3086 [MediaBundle] Add php8 attribute support in entities
  src/Kunstmaan/MediaBundle/Entity/EditableMediaWrapper.php
  src/Kunstmaan/MediaBundle/Entity/Folder.php
  src/Kunstmaan/MediaBundle/Entity/Media.php
Labels: Type: Feature

#3088 [MenuBundle] Add php8 attribute support in entities
  src/Kunstmaan/MenuBundle/Entity/BaseMenu.php
  src/Kunstmaan/MenuBundle/Entity/BaseMenuItem.php
  src/Kunstmaan/MenuBundle/Entity/Menu.php
  src/Kunstmaan/MenuBundle/Entity/MenuItem.php
Labels: Type: Feature

#3089 [NodeBundle] Add php8 attribute support in entities
  src/Kunstmaan/NodeBundle/Entity/AbstractControllerAction.php
  src/Kunstmaan/NodeBundle/Entity/AbstractPage.php
  src/Kunstmaan/NodeBundle/Entity/Node.php
  src/Kunstmaan/NodeBundle/Entity/NodeTranslation.php
  src/Kunstmaan/NodeBundle/Entity/NodeVersion.php
  src/Kunstmaan/NodeBundle/Entity/NodeVersionLock.php
  src/Kunstmaan/NodeBundle/Entity/QueuedNodeTranslationAction.php
Labels: Type: Feature

#3090 [NodeSearchBundle] Add php8 attribute support in entities
  src/Kunstmaan/NodeSearchBundle/Entity/NodeSearch.php
Labels: Type: Feature

#3091 [PagePartBundle] Add php8 attribute support in entities
  src/Kunstmaan/PagePartBundle/Entity/HeaderPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/LinePagePart.php
  src/Kunstmaan/PagePartBundle/Entity/LinkPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/PagePartRef.php
  src/Kunstmaan/PagePartBundle/Entity/PageTemplateConfiguration.php
  src/Kunstmaan/PagePartBundle/Entity/RawHTMLPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/TextPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/ToTopPagePart.php
  src/Kunstmaan/PagePartBundle/Entity/TocPagePart.php
Labels: Type: Feature

#3092 [VotingBundle] Add php8 attribute support in entities
  src/Kunstmaan/VotingBundle/Entity/AbstractVote.php
  src/Kunstmaan/VotingBundle/Entity/Facebook/FacebookLike.php
  src/Kunstmaan/VotingBundle/Entity/Facebook/FacebookSend.php
  src/Kunstmaan/VotingBundle/Entity/LinkedIn/LinkedInShare.php
  src/Kunstmaan/VotingBundle/Entity/UpDown/DownVote.php
  src/Kunstmaan/VotingBundle/Entity/UpDown/UpVote.php
Labels: Type: Feature

#3093 [RedirectBundle][SeoBundle][SitemapBundle][TaggingBundle][TranslatorBundle] Add php8 attribute support in entities
  src/Kunstmaan/RedirectBundle/Entity/Redirect.php
  src/Kunstmaan/SeoBundle/Entity/Robots.php
  src/Kunstmaan/SeoBundle/Entity/Seo.php
  src/Kunstmaan/SitemapBundle/Entity/SitemapPage.php
  src/Kunstmaan/TaggingBundle/Entity/Tag.php
  src/Kunstmaan/TaggingBundle/Entity/Tagging.php
  src/Kunstmaan/TranslatorBundle/Entity/Translation.php
Labels: Type: Feature

#3080 [AdminListBundle] Add php8 attribute support in entities
  src/Kunstmaan/AdminListBundle/Entity/EntityVersionLock.php
  src/Kunstmaan/AdminListBundle/Entity/LockableEntity.php
Labels: Type: Feature

#3099 [UserManagementBundle] Restore user edit/delete initialize events
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
  src/Kunstmaan/UserManagementBundle/Event/DeleteUserInitializeEvent.php
  src/Kunstmaan/UserManagementBundle/Event/EditUserInitializeEvent.php
Labels: Type: Bugfix

#3101 [AdminBundle] Fix compatibility with mysql ONLY_FULL_GROUP_BY sql mode
  src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
Labels: Type: Feature

#3104 [AdminBundle] Unique must be a boolean
  src/Kunstmaan/AdminBundle/Entity/BaseUser.php
Labels: Type: Bugfix

#3106 [CookieBundle] Fix php8 deprecation for passing null to stripos
  src/Kunstmaan/CookieBundle/EventSubscriber/CookieBarEventSubscriber.php
Labels: Type: Improvement

#3094 [MediaBundle] Upgraded constraints to enable named arguments and attributes
  src/Kunstmaan/MediaBundle/Tests/Validator/Constraints/MediaValidatorTest.php
  src/Kunstmaan/MediaBundle/Validator/Constraints/HasGuessableExtension.php
  src/Kunstmaan/MediaBundle/Validator/Constraints/Media.php
Labels: Type: Feature

#3112 [NodeBundle][SeoBundle] Fix php8 deprecation `Passing null to parameter #1 xxxx is deprecated`
  src/Kunstmaan/NodeBundle/Validation/URLValidator.php
  src/Kunstmaan/SeoBundle/Form/SeoType.php
Labels: Type: Bugfix, Type: Improvement

#3113 [NodeSearchBundle] Check if tokenstorage has valid token before retrieving user
  src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
Labels: Type: Bugfix

#3115 [AllBundles] Remove deprecated entitymanger flush parameter
  src/Kunstmaan/AdminBundle/Controller/DefaultController.php
  src/Kunstmaan/FixturesBundle/Builder/PagePartBuilder.php
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
  src/Kunstmaan/NodeBundle/Helper/Services/PageCreatorService.php
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
  src/Kunstmaan/PagePartBundle/Repository/PagePartRefRepository.php
  src/Kunstmaan/SeoBundle/EventListener/CloneListener.php
Labels: Type: Improvement

#3116 [NodeSearchBundle] Out of the box query limit
  src/Kunstmaan/NodeSearchBundle/ViewDataProvider/SearchPageViewDataProvider.php
Labels: Type: Feature

#3111 [AllBundles] Replace @Template annotation with controller render
  src/Kunstmaan/AdminBundle/Controller/DefaultController.php
  src/Kunstmaan/AdminBundle/Controller/ModulesController.php
  src/Kunstmaan/AdminBundle/Controller/SettingsController.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/CacheBundle/Controller/VarnishController.php
  src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
  src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
  src/Kunstmaan/LeadGenerationBundle/Controller/AbstractNewsletterController.php
  src/Kunstmaan/MediaBundle/Controller/ChooserController.php
  src/Kunstmaan/MediaBundle/Controller/FolderController.php
  src/Kunstmaan/MediaBundle/Controller/IconFontController.php
  src/Kunstmaan/MediaBundle/Controller/MediaController.php
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
  src/Kunstmaan/PagePartBundle/Controller/PagePartAdminController.php
  src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
  src/Kunstmaan/SeoBundle/Controller/RobotsController.php
  src/Kunstmaan/SeoBundle/Resources/config/services.yml
  src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
  src/Kunstmaan/SitemapBundle/Resources/config/services.yml
  src/Kunstmaan/TaggingBundle/Controller/TagAdminListController.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
  src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
  src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
  src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
  src/Kunstmaan/VotingBundle/Controller/VotingController.php
  src/Kunstmaan/VotingBundle/Resources/config/services.yml
Labels: Type: Improvement

#2890 [NodeBundle] Fix node order in url chooser
  src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
Labels: Type: Bugfix, needs-review

#3117 [NodeBundle] NodetranslationListener should use masterrequest to set …
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
Labels: Type: Bugfix

#3122 [CacheBundle] Fix cachebundle to actually work again with dependency updates
  src/Kunstmaan/CacheBundle/DependencyInjection/KunstmaanCacheExtension.php
  src/Kunstmaan/CacheBundle/EventListener/VarnishListener.php
  src/Kunstmaan/CacheBundle/Form/Varnish/BanType.php
  src/Kunstmaan/CacheBundle/Resources/config/services.yml
  src/Kunstmaan/CacheBundle/Resources/views/Varnish/ban.html.twig
Labels: Type: Improvement

#3123 [AllBundles] Setup subtree split github actions
  .build/subtree-splitter-config.json
  .github/workflows/subtree-split.yml
Labels: Type: Improvement

#3124 [AdminListBundle] Use label for item action when icon is null
  src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
Labels: Type: Bugfix, Type: Improvement
