Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2023-12, with the labels that each got.

#3292 [PagePartBundle] Allow deleting nested sub-entities
  src/Kunstmaan/PagePartBundle/Dto/PagePartDeleteInfo.php
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
Labels: Type: Feature

#3304 [FormBundle] Fix draft version form page
  src/Kunstmaan/FormBundle/ViewDataProvider/FormPageViewDataProvider.php
Labels: Type: Improvement

#3300 [RedirectBundle] Add order by to redirect admin list
  src/Kunstmaan/RedirectBundle/AdminList/RedirectAdminListConfigurator.php
Labels: Type: Improvement

#3322 [AllBundles] Symfony 6 compatibility fixes
  src/Kunstmaan/AdminBundle/EventListener/ToolbarListener.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
  src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/Permission/PermissionAdminTest.php
  src/Kunstmaan/ConfigBundle/Resources/config/routing.yml
  src/Kunstmaan/NodeBundle/Resources/config/routing.yml
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
Labels: Type: Improvement, sf6-compatibility

#3324 [AllBundles] Fix symfony 6.4 deprecations
  .php-cs-fixer.dist.php
  src/Kunstmaan/AdminBundle/Tests/Entity/GroupTest.php
  src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
  src/Kunstmaan/TranslatorBundle/Tests/app/AppKernel.php
  src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
Labels: Type: Improvement

#3120 [AllBundle] Add compatibility for new PUBLIC_ACCESS role
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
  src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
  src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclHelperTest.php
  src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclNativeHelperTest.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/GroupFixtures.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/RoleFixtures.php
  src/Kunstmaan/NodeBundle/Command/InitAclCommand.php
  src/Kunstmaan/NodeBundle/Helper/Services/ACLPermissionCreatorService.php
  src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
  src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
Labels: Type: Feature, Type: Improvement
