Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2023-05, with the labels that each got.

#3267 trim(null) is not allowed
  .github/workflows/ci.yml
  .github/workflows/subtree-split.yml
  src/Kunstmaan/AdminBundle/Entity/BaseUser.php
  src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
  src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
Labels: Type: Bugfix, Type: Improvement

#3269 [AdminBundle] TabPane can be nullable
  src/Kunstmaan/AdminBundle/Event/AdaptSimpleFormEvent.php
Labels: Type: Improvement

#3274 [AllBundles] Add missing phpdoc return types on dependency injection classes
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/AddLogProcessorsCompilerPass.php
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/AdminPanelCompilerPass.php
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/DataCollectorPass.php
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/EnablePermissionsPass.php
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/MenuCompilerPass.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminListBundle/DependencyInjection/KunstmaanAdminListExtension.php
  src/Kunstmaan/ArticleBundle/DependencyInjection/KunstmaanArticleExtension.php
  src/Kunstmaan/CacheBundle/DependencyInjection/KunstmaanCacheExtension.php
  src/Kunstmaan/ConfigBundle/DependencyInjection/KunstmaanConfigExtension.php
  src/Kunstmaan/CookieBundle/DependencyInjection/KunstmaanCookieExtension.php
  src/Kunstmaan/DashboardBundle/DependencyInjection/Compiler/WidgetCompilerPass.php
  src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
  src/Kunstmaan/FixturesBundle/DependencyInjection/Compiler/BuilderCompilerPass.php
  src/Kunstmaan/FixturesBundle/DependencyInjection/Compiler/ParserCompilerPass.php
  src/Kunstmaan/FixturesBundle/DependencyInjection/Compiler/PopulatorCompilerPass.php
  src/Kunstmaan/FixturesBundle/DependencyInjection/Compiler/ProviderCompilerPass.php
  src/Kunstmaan/FixturesBundle/DependencyInjection/KunstmaanFixturesExtension.php
  src/Kunstmaan/FormBundle/DependencyInjection/KunstmaanFormExtension.php
  src/Kunstmaan/GeneratorBundle/DependencyInjection/KunstmaanGeneratorExtension.php
  src/Kunstmaan/LeadGenerationBundle/DependencyInjection/KunstmaanLeadGenerationExtension.php
  src/Kunstmaan/MediaBundle/DependencyInjection/Compiler/MediaHandlerCompilerPass.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaPagePartBundle/DependencyInjection/KunstmaanMediaPagePartExtension.php
  src/Kunstmaan/MenuBundle/DependencyInjection/KunstmaanMenuExtension.php
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/KunstmaanMultiDomainExtension.php
  src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/Compiler/NodeSearcherCompilerPass.php
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
  src/Kunstmaan/PagePartBundle/DependencyInjection/KunstmaanPagePartExtension.php
  src/Kunstmaan/RedirectBundle/DependencyInjection/KunstmaanRedirectExtension.php
  src/Kunstmaan/SearchBundle/DependencyInjection/Compiler/SearchConfigurationCompilerPass.php
  src/Kunstmaan/SearchBundle/DependencyInjection/Compiler/SearchProviderCompilerPass.php
  src/Kunstmaan/SearchBundle/DependencyInjection/KunstmaanSearchExtension.php
  src/Kunstmaan/SeoBundle/DependencyInjection/KunstmaanSeoExtension.php
  src/Kunstmaan/SitemapBundle/DependencyInjection/KunstmaanSitemapExtension.php
  src/Kunstmaan/TaggingBundle/DependencyInjection/KunstmaanTaggingExtension.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPass.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
  src/Kunstmaan/UserManagementBundle/DependencyInjection/KunstmaanUserManagementExtension.php
  src/Kunstmaan/UtilitiesBundle/DependencyInjection/KunstmaanUtilitiesExtension.php
  src/Kunstmaan/VotingBundle/DependencyInjection/KunstmaanVotingExtension.php
Labels: Type: Improvement

#3273 [AllBundles] Add symfony 6 required php typehints (part 2)
  src/Kunstmaan/NodeBundle/Helper/Routing/DynamicUrlMatcher.php
  src/Kunstmaan/NodeSearchBundle/PagerFanta/Adapter/SearcherRequestAdapter.php
  src/Kunstmaan/TaggingBundle/DependencyInjection/KunstmaanTaggingExtension.php
Labels: Type: Improvement

#3275 [MultidomainBundle] Deprecation logout handler
  UPGRADE-6.3.md
  src/Kunstmaan/MultiDomainBundle/Helper/HostOverrideCleanupHandler.php
  src/Kunstmaan/MultiDomainBundle/Tests/Helper/HostOverrideCleanupHandlerTest.php
Labels: Type: Deprecation

#3276 [FormBundle] Replace container access with dependency injection in FormHandler
  UPGRADE-6.3.md
  src/Kunstmaan/FormBundle/Helper/FormHandler.php
  src/Kunstmaan/FormBundle/Resources/config/services.yml
  src/Kunstmaan/FormBundle/Tests/Helper/FormHandlerTest.php
Labels: Type: Deprecation

#3200 [AllBundles] Deprecate swiftmailer dependency
  UPGRADE-6.3.md
  src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Service/AuthenticationMailer/SwiftmailerService.php
  src/Kunstmaan/AdminBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/AdminBundle/Tests/DependencyInjection/KunstmaanAdminExtensionTest.php
  src/Kunstmaan/FormBundle/Helper/FormMailer.php
  src/Kunstmaan/FormBundle/Resources/config/services.yml
  src/Kunstmaan/FormBundle/Tests/Helper/FormMailerTest.php
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
Labels: Type: Deprecation, sf6-compatibility

#3279 [AllBundles] Improve php/phpdoc return types
  src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
  src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
  src/Kunstmaan/AdminBundle/Security/UserChecker.php
  src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
  src/Kunstmaan/AdminBundle/Toolbar/ExceptionDataCollector.php
  src/Kunstmaan/AdminBundle/Validator/Constraints/PasswordRestrictionsValidator.php
  src/Kunstmaan/MediaBundle/Validator/Constraints/MediaValidator.php
  src/Kunstmaan/NodeBundle/Router/SlugRouter.php
  src/Kunstmaan/NodeBundle/Toolbar/NodeDataCollector.php
  src/Kunstmaan/NodeBundle/Validator/Constraint/ValidExternalUrlValidator.php
  src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
  src/Kunstmaan/TranslatorBundle/KunstmaanTranslatorBundle.php
  src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
  src/Kunstmaan/TranslatorBundle/Toolbar/TranslatorDataCollector.php
Labels: Type: Improvement, sf6-compatibility

#3280 [AllBundles] Bump sensio/framework-extra-bundle to ^6.0
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement, sf6-compatibility

#3281 [AllBundles] Symfony 6 compatibility fixes
  src/Kunstmaan/AdminBundle/Helper/UserProcessor.php
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/DashboardBundle/KunstmaanDashboardBundle.php
  src/Kunstmaan/FixturesBundle/KunstmaanFixturesBundle.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminTestsCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateConfigCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultPagePartsCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateFormPageCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateFormPagePartsCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateLayoutCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GeneratePagePartCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateSearchPageCommand.php
  src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
  src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/SitemapFixtures.php
  src/Kunstmaan/MediaBundle/KunstmaanMediaBundle.php
  src/Kunstmaan/MediaBundle/Validator/Constraints/HasGuessableExtensionValidator.php
  src/Kunstmaan/NodeBundle/KunstmaanNodeBundle.php
  src/Kunstmaan/NodeSearchBundle/KunstmaanNodeSearchBundle.php
  src/Kunstmaan/SearchBundle/KunstmaanSearchBundle.php
Labels: Type: Improvement, sf6-compatibility

#3283 [AllBundles] Bump pagerfanta to v3
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/ArticleBundle/composer.json
  src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/composer.json
Labels: Type: Feature

#3284 [PagePartBundle] Fix parameter bag retriaval of array params
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
Labels: sf6-compatibility

#3285 [AllBundles] Bump twig dependency and replace abandoned twig/extensions package
  UPGRADE-6.3.md
  composer.json
  src/Kunstmaan/AdminBundle/Twig/AdminBundleTwigExtension.php
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/SearchPage/pagetemplate.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Resources/views/Pages/SearchPage/view.html.twig
  src/Kunstmaan/NodeSearchBundle/Resources/views/AbstractSearchPage/view.html.twig
  src/Kunstmaan/NodeSearchBundle/composer.json
  src/Kunstmaan/SearchBundle/Resources/config/services.yml
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
Labels: Type: Improvement

#3286 [AllBundles] Bump support php version to ^8.1
  .github/workflows/ci.yml
  .github/workflows/code-quality.yml
  composer.json
  src/Kunstmaan/AdminBundle/Tests/Helper/FormWidgets/ListWidgetTest.php
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/ArticleBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/CacheBundle/composer.json
  src/Kunstmaan/ConfigBundle/composer.json
  src/Kunstmaan/CookieBundle/composer.json
  src/Kunstmaan/DashboardBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/GeneratorBundle/composer.json
  src/Kunstmaan/LeadGenerationBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/MediaPagePartBundle/composer.json
  src/Kunstmaan/MenuBundle/composer.json
  src/Kunstmaan/MultiDomainBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/composer.json
  src/Kunstmaan/PagePartBundle/composer.json
  src/Kunstmaan/RedirectBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/SeoBundle/composer.json
  src/Kunstmaan/SitemapBundle/composer.json
  src/Kunstmaan/TaggingBundle/composer.json
  src/Kunstmaan/TranslatorBundle/Tests/Service/Translator/LoaderTest.php
  src/Kunstmaan/TranslatorBundle/composer.json
  src/Kunstmaan/UserManagementBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement

#3288 [AllBundles] Allow symfony 6 and fix compatibility issues
  composer.json
  src/Kunstmaan/AdminBundle/Service/PasswordResetService.php
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/ArticleBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/CacheBundle/composer.json
  src/Kunstmaan/ConfigBundle/composer.json
  src/Kunstmaan/DashboardBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/GeneratorBundle/Generator/ConfigGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/config/security_sf6.yaml
  src/Kunstmaan/GeneratorBundle/composer.json
  src/Kunstmaan/LeadGenerationBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/MediaPagePartBundle/composer.json
  src/Kunstmaan/MenuBundle/composer.json
  src/Kunstmaan/MultiDomainBundle/composer.json
  src/Kunstmaan/NodeBundle/Command/CronUpdateNodeCommand.php
  src/Kunstmaan/NodeBundle/Tests/Helper/NodeHelperTest.php
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/PagePartBundle/composer.json
  src/Kunstmaan/RedirectBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/SeoBundle/composer.json
  src/Kunstmaan/SitemapBundle/composer.json
  src/Kunstmaan/TaggingBundle/composer.json
  src/Kunstmaan/TranslatorBundle/Tests/app/AppKernel.php
  src/Kunstmaan/TranslatorBundle/composer.json
  src/Kunstmaan/UserManagementBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: sf6-compatibility
