Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2023-01, with the labels that each got.

#3236 [TranslatorBundle] change in doctrine querybuilder on php8 systems caused our faulty expression to generate a non working query
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
Labels: Type: Bugfix

#3242 [MediaPagePartBundle] Add admin view for media pageparts
  src/Kunstmaan/MediaPagePartBundle/Entity/AudioPagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/DownloadPagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/ImagePagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/SlidePagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/VideoPagePart.php
  src/Kunstmaan/MediaPagePartBundle/Resources/views/AudioPagePart/admin-view.html.twig
  src/Kunstmaan/MediaPagePartBundle/Resources/views/DownloadPagePart/admin-view.html.twig
  src/Kunstmaan/MediaPagePartBundle/Resources/views/ImagePagePart/admin-view.html.twig
  src/Kunstmaan/MediaPagePartBundle/Resources/views/SlidePagePart/admin-view.html.twig
  src/Kunstmaan/MediaPagePartBundle/Resources/views/VideoPagePart/admin-view.html.twig
  src/Kunstmaan/MediaPagePartBundle/Tests/Entity/AudioPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/Entity/DownloadPagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/Entity/ImagePagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/Entity/SlidePagePartTest.php
  src/Kunstmaan/MediaPagePartBundle/Tests/Entity/VideoPagePartTest.php
Labels: Type: Feature

#3243 [UtilitiesBundle] Change docblock for slugifier
  src/Kunstmaan/UtilitiesBundle/Helper/SlugifierInterface.php
Labels: Type: Improvement
