Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2024-03, with the labels that each got.

#3345 [AdminListBundle] Fix doctrine related unit tests
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Configurator/AbstractDoctrineDBALAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/FilterType/DBAL/BaseDbalFilterTest.php
Labels: Type: Improvement

#3342 [AdminBundle] Add extra blocks to authentication layout
  src/Kunstmaan/AdminBundle/Resources/views/authentication/login.html.twig
Labels: Type: Feature

#3337 [MediaBundle] - allow custom view vars in chooser
  src/Kunstmaan/MediaBundle/Controller/ChooserController.php
Labels: Type: Feature

#3333 [AdminBundle] Add hide sidebar configuration
  src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig
  src/Kunstmaan/AdminBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/AdminBundle/Twig/SidebarTwigExtension.php
Labels: Type: Feature

#3334 [NodeBundle] View parent nodes from list
  src/Kunstmaan/NodeBundle/AdminList/NodeAdminListConfigurator.php
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
  src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
Labels: Type: Feature

#3344 Refactor service definitions replacing removed classes
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
Labels: Type: Improvement, Type: Needs work

#3347 [AdminListBundle] Deprecate configurator getBundleName/getEntityName methods
  src/Kunstmaan/AdminBundle/AdminList/ExceptionAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractPageAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/Controller/AbstractAdminListController.php
  src/Kunstmaan/AdminListBundle/Resources/doc/PageAdminListBundle.md
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Configurator/AbstractAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Configurator/AbstractDoctrineDBALAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Configurator/AbstractDoctrineORMAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Utils/EntityDetails.php
  src/Kunstmaan/ArticleBundle/AdminList/AbstractArticleAuthorAdminListConfigurator.php
  src/Kunstmaan/ArticleBundle/AdminList/AbstractArticlePageAdminListConfigurator.php
  src/Kunstmaan/ArticleBundle/Tests/AdminList/AbstractArticleAuthorAdminListConfiguratorTest.php
  src/Kunstmaan/ArticleBundle/Tests/AdminList/AbstractArticlePageAdminListConfiguratorTest.php
  src/Kunstmaan/CookieBundle/AdminList/CookieAdminListConfigurator.php
  src/Kunstmaan/FormBundle/AdminList/FormPageAdminListConfigurator.php
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionAdminListConfigurator.php
  src/Kunstmaan/FormBundle/Tests/AdminList/FormPageAdminListConfiguratorTest.php
  src/Kunstmaan/FormBundle/Tests/AdminList/FormSubmissionAdminListConfiguratorTest.php
  src/Kunstmaan/GeneratorBundle/Generator/AdminListGenerator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/AdminList/AdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/AuthorAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/CategoryAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/PageAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/TagAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/AdminList/BikeAdminListConfigurator.php
  src/Kunstmaan/LeadGenerationBundle/AdminList/PopupAdminListConfigurator.php
  src/Kunstmaan/LeadGenerationBundle/AdminList/RulesAdminListConfigurator.php
  src/Kunstmaan/MediaBundle/AdminList/MediaAdminListConfigurator.php
  src/Kunstmaan/MenuBundle/AdminList/MenuAdminListConfigurator.php
  src/Kunstmaan/MenuBundle/AdminList/MenuItemAdminListConfigurator.php
  src/Kunstmaan/NodeBundle/AdminList/NodeAdminListConfigurator.php
  src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeVersionLockHelper.php
  src/Kunstmaan/NodeBundle/Tests/AdminList/NodeAdminListConfiguratorTest.php
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/RedirectBundle/AdminList/RedirectAdminListConfigurator.php
  src/Kunstmaan/RedirectBundle/Tests/AdminList/RedirectAdminListConfiguratorTest.php
  src/Kunstmaan/TaggingBundle/AdminList/TagAdminListConfigurator.php
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
Labels: Type: Feature, Type: Deprecation

#3352 [AdminList] Fix AdminLists
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/Controller/AbstractAdminListController.php
  src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/sure-modal.html.twig
  src/Kunstmaan/MenuBundle/AdminList/MenuAdminListConfigurator.php
  src/Kunstmaan/UserManagementBundle/AdminList/AbstractSettingsAdminListConfigurator.php
  src/Kunstmaan/UserManagementBundle/AdminList/GroupAdminListConfigurator.php
  src/Kunstmaan/UserManagementBundle/AdminList/RoleAdminListConfigurator.php
  src/Kunstmaan/UserManagementBundle/AdminList/UserAdminListConfigurator.php
Labels: Type: Bugfix

#3353 [AllBundles] Fix php-cs-fixer issues
  src/Kunstmaan/AdminBundle/AdminList/ExceptionAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/Controller/EntityLockCheckController.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/FilterType/DBAL/EnumerationFilterTypeTest.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/FilterType/ORM/DateTimeFilterTypeTest.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/FilterType/ORM/EnumerationFilterTypeTest.php
  src/Kunstmaan/DashboardBundle/Helper/Google/Analytics/ConfigHelper.php
  src/Kunstmaan/DashboardBundle/Repository/AnalyticsConfigRepository.php
  src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultPagePartsCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateSearchPageCommand.php
  src/Kunstmaan/LeadGenerationBundle/Tests/DependencyInjection/KunstmaanLeadGenerationExtensionTest.php
  src/Kunstmaan/MediaBundle/AdminList/ItemAction/MediaDeleteItemAction.php
  src/Kunstmaan/MediaBundle/AdminList/ItemAction/MediaEditItemAction.php
  src/Kunstmaan/MediaPagePartBundle/Form/AudioPagePartAdminType.php
  src/Kunstmaan/MediaPagePartBundle/Form/DownloadPagePartAdminType.php
  src/Kunstmaan/MediaPagePartBundle/Form/ImagePagePartAdminType.php
  src/Kunstmaan/MediaPagePartBundle/Form/SlidePagePartAdminType.php
  src/Kunstmaan/MediaPagePartBundle/Form/VideoPagePartAdminType.php
  src/Kunstmaan/NodeBundle/Form/PageAdminType.php
  src/Kunstmaan/PagePartBundle/Form/HeaderPagePartAdminType.php
  src/Kunstmaan/PagePartBundle/Form/LinePagePartAdminType.php
  src/Kunstmaan/PagePartBundle/PagePartAdmin/Builder.php
  src/Kunstmaan/SeoBundle/Form/SeoType.php
  src/Kunstmaan/TaggingBundle/Form/TagsAdminType.php
Labels: Type: Improvement

#3354 [AllBundles] Fix issues with adminlist configurator deprecations
  src/Kunstmaan/AdminListBundle/Controller/AbstractAdminListController.php
  src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/sure-modal.html.twig
  src/Kunstmaan/AdminListBundle/Resources/views/Default/list.html.twig
  src/Kunstmaan/ArticleBundle/AdminList/AbstractArticleCategoryAdminListConfigurator.php
  src/Kunstmaan/ArticleBundle/AdminList/AbstractArticleTagAdminListConfigurator.php
  src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
  src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
  src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
  src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
Labels: Type: Bugfix

#3356 [AllBundles] Fix gedmo sibblings deprecation
  src/Kunstmaan/MediaBundle/Entity/Folder.php
  src/Kunstmaan/NodeBundle/Entity/Node.php
Labels: Type: Improvement

#3360 [AllBundles] Various phpdoc return type fixes
  src/Kunstmaan/AdminBundle/Entity/Group.php
  src/Kunstmaan/AdminBundle/Entity/UserInterface.php
  src/Kunstmaan/AdminBundle/Helper/AdminPanel/AdminPanelActionInterface.php
  src/Kunstmaan/AdminBundle/Helper/AdminPanel/AdminPanelLogoutAction.php
  src/Kunstmaan/AdminBundle/Helper/FormWidgets/FormWidgetInterface.php
  src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/Tab.php
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineDBALAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/ExportListConfiguratorInterface.php
  src/Kunstmaan/AdminListBundle/AdminList/ItemAction/ItemActionInterface.php
  src/Kunstmaan/AdminListBundle/AdminList/ItemAction/SimpleItemAction.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Configurator/AbstractAdminListConfiguratorTest.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Configurator/AbstractDoctrineDBALAdminListConfiguratorTest.php
  src/Kunstmaan/FormBundle/AdminList/FormSubmissionAdminListConfigurator.php
  src/Kunstmaan/FormBundle/Entity/FormSubmission.php
  src/Kunstmaan/FormBundle/Helper/FormHandlerInterface.php
  src/Kunstmaan/FormBundle/Tests/AdminList/FormSubmissionAdminListConfiguratorTest.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
  src/Kunstmaan/LeadGenerationBundle/Entity/Rule/AbstractRule.php
  src/Kunstmaan/MediaBundle/Helper/Remote/AbstractRemoteHelper.php
  src/Kunstmaan/MediaBundle/Helper/Remote/RemoteInterface.php
  src/Kunstmaan/MediaBundle/Helper/Transformer/PdfTransformer.php
  src/Kunstmaan/NodeBundle/Helper/FormWidgets/PermissionsFormWidget.php
  src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
Labels: Type: Improvement

#3361 [NodeBundle] Fix php8 deprecation in ExternalUrlValidator
  src/Kunstmaan/NodeBundle/Tests/Validator/Constraint/ValidExternalUrlValidatorTest.php
  src/Kunstmaan/NodeBundle/Validator/Constraint/ValidExternalUrlValidator.php
Labels: Type: Improvement

#3349 [FormBundle] Remove empty_data from ChoiceFormSubmissionType
  src/Kunstmaan/FormBundle/Form/ChoiceFormSubmissionType.php
Labels: Type: Bugfix

#3368 [AdminBundle] Restore undefined encore twig function handler
  src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/ReplaceSymfonyEnvironmentConfiguratorCompilerPass.php
  src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
  src/Kunstmaan/AdminBundle/Twig/Configurator/EnvironmentConfigurator.php
  src/Kunstmaan/AdminBundle/Twig/UndefinedSymfonyEncoreFunctionHandler.php
Labels: Type: Bugfix

#3348 [RedirectBundle] Configure redirect admin list configurator as service
  src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
  src/Kunstmaan/RedirectBundle/Resources/config/services.yml
Labels: Type: Needs work

#3369 [RedirectBundle] Cleanup redirect adminlist deprecation
  src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
Labels: Type: Improvement

#3371 [GeneratorBundle] Fix incorrect getEntityClass declaration of bike adminlist
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/AdminList/BikeAdminListConfigurator.php
Labels: Type: Bugfix

#3372 [DashboardBundle] Fix incorrect return type in analytics config helper
  src/Kunstmaan/DashboardBundle/Helper/Google/Analytics/ConfigHelper.php
Labels: Type: Bugfix

#3373 [GeneratorBundle] FE setup fixes for cms-skeleton install
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/frontend-config/.nvmrc
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/webpack-encore/package.json
Labels: Type: Bugfix

#3374 [NodeBundle][MediaBundle] Prepend required stof/doctrine-extensions config instead of manually registering services
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
  src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
  src/Kunstmaan/NodeBundle/Resources/config/services.yml
Labels: Type: Improvement

#3375 [AllBundles] Fix doctrine orm 3 deprecations and allow doctrine/persistence v3
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/DashboardBundle/Repository/AnalyticsConfigRepository.php
  src/Kunstmaan/DashboardBundle/Repository/AnalyticsOverviewRepository.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/PageRepositoryPartial.php.twig
  src/Kunstmaan/PagePartBundle/Repository/PagePartRefRepository.php
Labels: Type: Improvement

#3376 [MenuBundle] Fix doctrine 2.16/3.0 incompatibility in menu entities
  src/Kunstmaan/MenuBundle/Entity/BaseMenu.php
  src/Kunstmaan/MenuBundle/Entity/BaseMenuItem.php
Labels: Type: Improvement

#3377 [GeneratorBundle] Don't trigger liip imagine deprecation with default config
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/config/liip_imagine.yaml
Labels: Type: Improvement

#3379 [AllBundles] Bump minimum symfony and kunstmaan dependencies
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/ArticleBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/CacheBundle/composer.json
  src/Kunstmaan/ConfigBundle/composer.json
  src/Kunstmaan/CookieBundle/composer.json
  src/Kunstmaan/DashboardBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/GeneratorBundle/composer.json
  src/Kunstmaan/LeadGenerationBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/MediaPagePartBundle/composer.json
  src/Kunstmaan/MenuBundle/composer.json
  src/Kunstmaan/MultiDomainBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/composer.json
  src/Kunstmaan/PagePartBundle/composer.json
  src/Kunstmaan/RedirectBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/SeoBundle/composer.json
  src/Kunstmaan/SitemapBundle/composer.json
  src/Kunstmaan/TaggingBundle/composer.json
  src/Kunstmaan/TranslatorBundle/composer.json
  src/Kunstmaan/UserManagementBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement

#3381 [AllBundles] Drop Symfony 5.4 support
  .github/workflows/ci.yml
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/TranslatorBundle/Tests/app/AppKernel.php
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement

#3378 [AllBundles] Replace sensio/framework-extra-bundle with built-in symfony attributes
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/Resources/doc/AdminListBundle.md
  src/Kunstmaan/CookieBundle/Controller/LegalController.php
  src/Kunstmaan/DashboardBundle/Widget/DashboardWidget.php
  src/Kunstmaan/NodeBundle/Controller/SlugController.php
  src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement
