Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2024-11, with the labels that each got.

#3456 [MediaPagePartBundle] Add missing notblank constraint to media pageparts
  src/Kunstmaan/MediaPagePartBundle/Entity/AudioPagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/DownloadPagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/ImagePagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/SlidePagePart.php
  src/Kunstmaan/MediaPagePartBundle/Entity/VideoPagePart.php
Labels: Type: Improvement

#3453 [PagePart] (fix) skip checking for not persisted sub entites delete c…
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
Labels: Type: Bugfix

#3454 [RedirectBundle] Add support for redirect origin wildcard, excluding root path
  src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
  src/Kunstmaan/RedirectBundle/Tests/Router/RedirectRouterTest.php
Labels: Type: Feature

#3459 [AllBundles] Fix fixture deprecations
  src/Kunstmaan/FixturesBundle/Loader/FixtureLoader.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/GroupFixtures.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/RoleFixtures.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/DataFixtures/ORM/SearchPageGenerator/SearchFixtures.php
  src/Kunstmaan/MediaBundle/DataFixtures/ORM/FolderFixtures.php
  src/Kunstmaan/TranslatorBundle/DataFixtures/ORM/TranslationFixtures.php
  src/Kunstmaan/TranslatorBundle/Tests/Fixtures/TranslationDataFixture.php
Labels: Type: Improvement

#3464 [FormBundle] Forward compatibility fix for symfony 7.2 in tests
  src/Kunstmaan/FormBundle/Tests/Form/AbstractFormPageAdminTypeTest.php
Labels: Type: Improvement, sf7-compatibility

#3444 [MultidomainBundle] Improve domain based locale router performance
  UPGRADE-7.2.md
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/MultiDomainBundle/Router/DomainBasedLocaleRouter.php
  src/Kunstmaan/MultiDomainBundle/Tests/Router/DomainBasedLocaleRouterTest.php
  src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
  src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
  src/Kunstmaan/NodeBundle/Router/SlugRouter.php
  src/Kunstmaan/NodeBundle/Tests/DependencyInjection/ConfigurationTest.php
  src/Kunstmaan/NodeBundle/Tests/DependencyInjection/KunstmaanNodeExtensionTest.php
Labels: Type: Improvement, Type: Needs work, performance

#3467 [TranslatorBundle] Backport fixtures load deprecation fix
  src/Kunstmaan/TranslatorBundle/DataFixtures/ORM/TranslationFixtures.php
  src/Kunstmaan/TranslatorBundle/Tests/Fixtures/TranslationDataFixture.php
Labels: Type: Improvement

#3466 [AllBundles] Upgrade phpstan to 2.0
  composer.json
  phpstan.neon
Labels: Type: Improvement

#3468 [GeneratorBundle] Remove kunstmaan/sensio-generator-bundle dependency
  UPGRADE-7.3.md
  composer.json
  src/Kunstmaan/GeneratorBundle/Command/AbstractGeneratorCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminTestsCommand.php
  src/Kunstmaan/GeneratorBundle/Command/GenerateSearchPageCommand.php
  src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
  src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
  src/Kunstmaan/GeneratorBundle/Generator/AbstractGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/AdminListGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/AdminTestsGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/FormPageGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
  src/Kunstmaan/GeneratorBundle/Generator/SearchPageGenerator.php
  src/Kunstmaan/GeneratorBundle/Helper/Command/Validators.php
  src/Kunstmaan/GeneratorBundle/Helper/CommandAssistant.php
  src/Kunstmaan/GeneratorBundle/Helper/GeneratorUtils.php
  src/Kunstmaan/GeneratorBundle/Helper/InputAssistant.php
  src/Kunstmaan/GeneratorBundle/Helper/QuestionHelper.php
  src/Kunstmaan/GeneratorBundle/composer.json
Labels: Type: Improvement, sf7-compatibility

#3470 [TranslatorBundle] Add Symfony 7 forward compatibility
  src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
Labels: sf7-compatibility
