Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2024-04, with the labels that each got.

#3385 [AllBundles] Fix incorrect return types
  src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php
  src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
Labels: Type: Bugfix

#3386 [MenuBundle] Fix menu entities
  src/Kunstmaan/MenuBundle/Entity/BaseMenu.php
  src/Kunstmaan/MenuBundle/Entity/BaseMenuItem.php
Labels: Type: Bugfix

#3387 [AllBundles] Set correct routing yaml attribute type
  src/Kunstmaan/AdminBundle/Resources/config/routing.yml
  src/Kunstmaan/AdminListBundle/Resources/config/routing.yml
  src/Kunstmaan/AdminListBundle/Resources/doc/AdminListBundle.md
  src/Kunstmaan/AdminListBundle/Resources/doc/PageAdminListBundle.md
  src/Kunstmaan/CacheBundle/Resources/config/routing.yml
  src/Kunstmaan/CookieBundle/Resources/config/routing.yml
  src/Kunstmaan/DashboardBundle/Resources/config/routing.yml
  src/Kunstmaan/FormBundle/Resources/config/routing.yml
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/routing_multilanguage.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/routing_partial.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/routing_singlelanguage.yml
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/routing.yml
  src/Kunstmaan/LeadGenerationBundle/Resources/config/routing.yml
  src/Kunstmaan/MediaBundle/Resources/config/routing.yml
  src/Kunstmaan/MenuBundle/Resources/config/routing.yml
  src/Kunstmaan/MultiDomainBundle/Resources/config/routing.yml
  src/Kunstmaan/NodeBundle/Resources/config/routing.yml
  src/Kunstmaan/PagePartBundle/Resources/config/routing.yml
  src/Kunstmaan/RedirectBundle/Resources/config/routing.yml
  src/Kunstmaan/SeoBundle/Resources/config/routing.yml
  src/Kunstmaan/SitemapBundle/Resources/config/routing.yml
  src/Kunstmaan/TaggingBundle/Resources/config/routing.yml
  src/Kunstmaan/TranslatorBundle/Resources/config/routing.yml
  src/Kunstmaan/UserManagementBundle/Resources/config/routing.yml
  src/Kunstmaan/VotingBundle/Resources/config/routing.yml
Labels: Type: Improvement

#3389 [MediaBundle] Prepend gedmo translatable doctrine mapping with attributes
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
Labels: Type: Improvement

#3390 [GeneratorBundle] Update encore package.json for webpack-encore-bundle 2
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/webpack-encore/package.json
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/webpack-encore/webpack.config.js
Labels: Type: Improvement

#3396 [NodeBundle] Fix incorrect requeststack method for symfony 6.4
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
Labels: Type: Bugfix

#3398 [AdminBundle] Fix monolog-bridge logger deprecation
  composer.json
  src/Kunstmaan/AdminBundle/Resources/config/services.yml
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/NodeBundle/EventListener/LogPageEventsSubscriber.php
  src/Kunstmaan/TranslatorBundle/Tests/app/TranslatorBundleTest/bundles.php
Labels: Type: Improvement

#3388 [AllBundles] Fix doctrine related deprecations
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineDBALAdminListConfigurator.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/FilterType/DBAL/BaseDbalFilterTest.php
  src/Kunstmaan/MediaBundle/EventListener/DoctrineMediaListener.php
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
  src/Kunstmaan/TranslatorBundle/Tests/app/AppKernel.php
  src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Improvement

#3397 [AllBundles] Refactor fixtures to dependency injection
  src/Kunstmaan/CookieBundle/Resources/skeleton/legal/DataFixtures/ORM/LegalGenerator/DefaultFixtures.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/SitemapFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/DataFixtures/ORM/SearchPageGenerator/SearchFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
  src/Kunstmaan/PagePartBundle/Resources/config/services.yml
Labels: Type: Improvement

#3400 [NodeBundle] Fix incorrect event type in doctrine listener
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
Labels: Type: Bugfix

#3399 [MediaBundle] Add missing autowire service alias
  src/Kunstmaan/MediaBundle/Resources/config/services.yml
Labels: Type: Improvement

#3408 [NodeBundle] Fix node reorder
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
Labels: Type: Bugfix

#3405 [AdminBundle] Added missing security translations de (german)
  src/Kunstmaan/AdminBundle/Resources/translations/messages.de.yml
Labels: Type: Improvement

#3404 [TaggingBundle] fixed base route name
  src/Kunstmaan/TaggingBundle/AdminList/TagAdminListConfigurator.php
Labels: Type: Bugfix

#3403 [LeadGenerationBundle] fixed route and type handling
  src/Kunstmaan/LeadGenerationBundle/AdminList/PopupAdminListConfigurator.php
  src/Kunstmaan/LeadGenerationBundle/Controller/PopupsAdminListController.php
  src/Kunstmaan/LeadGenerationBundle/Controller/RulesAdminListController.php
Labels: Type: Bugfix

#3409 [AllBundles] More fixes of deprecations in doctrine event listeners
  src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
  src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
  src/Kunstmaan/TaggingBundle/EventListener/TagsListener.php
Labels: Type: Improvement

#3410 [FormBundle] Fix form pagepart view variable with symfony template attribute
  UPGRADE-7.2.md
  src/Kunstmaan/FormBundle/Helper/FormHandler.php
  src/Kunstmaan/FormBundle/Resources/views/CheckboxPagePart/view.html.twig
  src/Kunstmaan/FormBundle/Resources/views/ChoicePagePart/view.html.twig
  src/Kunstmaan/FormBundle/Resources/views/EmailPagePart/view.html.twig
  src/Kunstmaan/FormBundle/Resources/views/FileUploadPagePart/view.html.twig
  src/Kunstmaan/FormBundle/Resources/views/MultiLineTextPagePart/view.html.twig
  src/Kunstmaan/FormBundle/Resources/views/SingleLineTextPagePart/view.html.twig
Labels: Type: Bugfix

#3411 [AllBundles] Symfony 7 forward compatibility fixes
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminListBundle/DependencyInjection/KunstmaanAdminListExtension.php
  src/Kunstmaan/ArticleBundle/DependencyInjection/KunstmaanArticleExtension.php
  src/Kunstmaan/CacheBundle/DependencyInjection/KunstmaanCacheExtension.php
  src/Kunstmaan/ConfigBundle/DependencyInjection/KunstmaanConfigExtension.php
  src/Kunstmaan/CookieBundle/DependencyInjection/KunstmaanCookieExtension.php
  src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
  src/Kunstmaan/FixturesBundle/DependencyInjection/KunstmaanFixturesExtension.php
  src/Kunstmaan/FormBundle/DependencyInjection/KunstmaanFormExtension.php
  src/Kunstmaan/LeadGenerationBundle/DependencyInjection/KunstmaanLeadGenerationExtension.php
  src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
  src/Kunstmaan/MediaPagePartBundle/DependencyInjection/KunstmaanMediaPagePartExtension.php
  src/Kunstmaan/MenuBundle/DependencyInjection/KunstmaanMenuExtension.php
  src/Kunstmaan/MultiDomainBundle/DependencyInjection/KunstmaanMultiDomainExtension.php
  src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
  src/Kunstmaan/NodeBundle/Validator/Constraint/ValidExternalUrlValidator.php
  src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
  src/Kunstmaan/PagePartBundle/DependencyInjection/KunstmaanPagePartExtension.php
  src/Kunstmaan/RedirectBundle/DependencyInjection/KunstmaanRedirectExtension.php
  src/Kunstmaan/SearchBundle/DependencyInjection/KunstmaanSearchExtension.php
  src/Kunstmaan/SeoBundle/DependencyInjection/KunstmaanSeoExtension.php
  src/Kunstmaan/SitemapBundle/DependencyInjection/KunstmaanSitemapExtension.php
  src/Kunstmaan/TaggingBundle/DependencyInjection/KunstmaanTaggingExtension.php
  src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
  src/Kunstmaan/UserManagementBundle/DependencyInjection/KunstmaanUserManagementExtension.php
  src/Kunstmaan/UtilitiesBundle/DependencyInjection/KunstmaanUtilitiesExtension.php
  src/Kunstmaan/VotingBundle/DependencyInjection/KunstmaanVotingExtension.php
Labels: Type: Improvement

#3412 [AllBundles] Improve tests
  src/Kunstmaan/AdminBundle/Tests/EventListener/AdminLocaleListenerTest.php
  src/Kunstmaan/AdminBundle/Tests/EventListener/PasswordCheckListenerTest.php
  src/Kunstmaan/AdminListBundle/Tests/AdminList/Configurator/AbstractDoctrineORMAdminListConfiguratorTest.php
  src/Kunstmaan/NodeBundle/Tests/Helper/NodeHelperTest.php
  src/Kunstmaan/NodeSearchBundle/Tests/Services/SearchServiceTest.php
Labels: Type: Improvement

#3407 [PagePartBundle] Add page to PagePartEvent
  UPGRADE-7.2.md
  src/Kunstmaan/PagePartBundle/Event/PagePartEvent.php
  src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
Labels: Type: Feature

#3413 [NodeBundle] Fix node reorder parents
  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
Labels: Type: Bugfix

#3414 [AdminBundle] fixed base route name for exception admin lists
  src/Kunstmaan/AdminBundle/AdminList/ExceptionAdminListConfigurator.php
Labels: Type: Bugfix

#3415 [TranslatorBundle] Fixed MessageCatalogue strict type (string) parameters in Translator Loader
  src/Kunstmaan/TranslatorBundle/Service/Translator/Loader.php
Labels: Type: Bugfix

#3417 [AdminBundle] Menu order
  src/Kunstmaan/AdminBundle/Helper/Menu/MenuBuilder.php
Labels: Type: Feature
