Repository Kunstmaan/KunstmaanBundlesCMS, pull requests merged in 2025-02, with the labels that each got.

#3485 [AllBundles] Fix symfony 7.3 deprecations
  src/Kunstmaan/AdminBundle/Entity/BaseUser.php
  src/Kunstmaan/CookieBundle/Resources/skeleton/legal/Entity/PageParts/LegalOptInPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
  src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/CheckboxPagePart/CheckboxPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ChoicePagePart/ChoicePagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/EmailPagePart/EmailPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/FileUploadPagePart/FileUploadPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/MultiLineTextPagePart/MultiLineTextPagePart.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/SingleLineTextPagePart/SingleLineTextPagePart.php
  src/Kunstmaan/LeadGenerationBundle/Form/NewsletterSubscriptionType.php
  src/Kunstmaan/NodeBundle/Form/NodeMenuTabTranslationAdminType.php
  src/Kunstmaan/NodeBundle/Validator/Constraint/ValidExternalUrlValidator.php
  src/Kunstmaan/PagePartBundle/Entity/HeaderPagePart.php
  src/Kunstmaan/TranslatorBundle/Tests/app/AppKernel.php
Labels: sf7-compatibility

#3484 [AllBundles] Allow symfony 7
  .build/deprecations-baseline.json
  composer.json
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: Type: Feature, Type: Improvement, sf7-compatibility

#3475 [AdminBundle] Remove session security listener if values are not enabled
  src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
  src/Kunstmaan/AdminBundle/Tests/DependencyInjection/KunstmaanAdminExtensionTest.php
Labels: Type: Improvement

#3487 Update remaining packages for Symfony 7 support
  src/Kunstmaan/AdminBundle/composer.json
  src/Kunstmaan/AdminListBundle/composer.json
  src/Kunstmaan/ArticleBundle/composer.json
  src/Kunstmaan/BehatBundle/composer.json
  src/Kunstmaan/CacheBundle/composer.json
  src/Kunstmaan/ConfigBundle/composer.json
  src/Kunstmaan/DashboardBundle/composer.json
  src/Kunstmaan/FixturesBundle/composer.json
  src/Kunstmaan/FormBundle/composer.json
  src/Kunstmaan/GeneratorBundle/composer.json
  src/Kunstmaan/LeadGenerationBundle/composer.json
  src/Kunstmaan/MediaBundle/composer.json
  src/Kunstmaan/MediaPagePartBundle/composer.json
  src/Kunstmaan/MenuBundle/composer.json
  src/Kunstmaan/MultiDomainBundle/composer.json
  src/Kunstmaan/NodeBundle/composer.json
  src/Kunstmaan/NodeSearchBundle/composer.json
  src/Kunstmaan/PagePartBundle/composer.json
  src/Kunstmaan/RedirectBundle/composer.json
  src/Kunstmaan/SearchBundle/composer.json
  src/Kunstmaan/SeoBundle/composer.json
  src/Kunstmaan/SitemapBundle/composer.json
  src/Kunstmaan/TaggingBundle/composer.json
  src/Kunstmaan/TranslatorBundle/composer.json
  src/Kunstmaan/UserManagementBundle/composer.json
  src/Kunstmaan/UtilitiesBundle/composer.json
  src/Kunstmaan/VotingBundle/composer.json
Labels: sf7-compatibility

#3489 [GeneratorBundle] Add correct return type for Symfony 7 support
  src/Kunstmaan/GeneratorBundle/Command/GenerateAdminTestsCommand.php
Labels: sf7-compatibility

#3491 Symfony 7 compatibility fixes
  src/Kunstmaan/AdminBundle/Toolbar/ExceptionDataCollector.php
  src/Kunstmaan/MediaBundle/Form/Type/IdToMediaTransformer.php
  src/Kunstmaan/NodeBundle/Toolbar/NodeDataCollector.php
  src/Kunstmaan/TranslatorBundle/Toolbar/TranslatorDataCollector.php
Labels: sf7-compatibility

#3492 [AllBundle] PHP 8.4 deprecation fixes
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Helper/Menu/MenuAdaptor.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/PageRepositoryPartial.php.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/AdminList/BikeAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Helper/Menu/AdminMenuAdaptor.php
  src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
Labels: Type: Improvement

#3493 [AllBundles] Various dependency deprecation fixes
  src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineDBALAdminListConfigurator.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/GroupFixtures.php
  src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
Labels: Type: Improvement

#3494 [GeneratorBundle] Bugfix incorrect form type class in article generator
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminType.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminTypePartial.php.twig
Labels: Type: Bugfix

#3495 [GeneratorBundle] Fix fixture load return type deprecation
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/SitemapFixtures.php
Labels: Type: Improvement

#3496 [AllBundles] Remove deprecated twig spaceless tag
  src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
  src/Kunstmaan/AdminBundle/Resources/views/PermissionsAdminTwigExtension/widget.html.twig
  src/Kunstmaan/CookieBundle/Resources/views/Components/CookieBar.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Form/fields.html.twig
  src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
  src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig
  src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
  src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/widget.html.twig
  src/Kunstmaan/TaggingBundle/Resources/views/Form/fields.html.twig
  src/Kunstmaan/TranslatorBundle/Resources/views/Translator/inline_edit.html.twig
Labels: Type: Improvement

#3498 [AllBundles] Add php 8.4 to CI workflow
  .github/workflows/ci.yml
Labels: Type: Improvement
